### ISSUE TITLE
Getting driver.init.retry.timeout error while executing Appium scripts on Perfecto devices

### ISSUE THREAD

**Issue by venkatramanmushyam** [qmetry/qaf#104]
Hi,

I'm getting this error while executing the TestNG tests locally and through Jenkins jobs:

**Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure. java.lang.reflect.InvocationTargetException Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'SF1-QAVM156', ip: '10.46.109.187', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_85' Driver info: driver.version: unknown**

I'm getting this issue while trying to run Appium test scripts on Perfecto devices. The proxy is being set properly and the properties remote.server, driver.name, and appium.additional.capabilities are all set as shown below.

- driver.name=appiumDriver
- remote.server=https://[host]:[password]=@[domain].perfectomobile.com/nexperience/wd/hub
- device.runmode=browser
- automation.mechanism=PERFECTO
- appium.additional.capabilities={'deviceName':'756807AD','automationName':'Appium','browserName':'','platform':'ANY','driverClass':'io.appium.java_client.android.AndroidDriver'}

**Comment by cjayswal** [comment]
which version of QAF you are using? Will you also attach log file?

**Comment by venkatramanmushyam** [comment]
QAF-Standalone-2.1.10
QAF-Support-2.1.9

I've attached the stacktrace which is minimal and completely vague. I'm also giving that driver.class capability to the driver. I believe it may be occurring whenever a device is "Opened" in Perfecto. I'll be verifying that soon.

[Uploading error2.txt…]()

**Comment by cjayswal** [comment]
It looks like either you haven't added appium dependency or it is not compatible. Which version of appium client you are using?

**Comment by cjayswal** [comment]
Please reach out to your company's Core team.

**Comment by cjayswal** [comment]
Closing inactive issue. Please post in [user group](https://groups.google.com/forum/#!forum/qaf-users).
