### ISSUE TITLE
Multi devices - Setting env.resources per device close the first device

### ISSUE THREAD

**Issue by hadasshani** [qmetry/qaf#105]
When switching between drivers, if I'm setting the env.resources the first device closes.

TestBaseProvider.instance().get().setDriver(driverName+"RemoteDriver");
String envResources = ConfigurationManager.getBundle().getString(driverName + ".env.resources");
ConfigurationManager.getBundle().setProperty("env.resources",envResources);

**Comment by cjayswal** [comment]
Make sure that not of the resource set/change driver capability.

**Comment by hadasshani** [comment]
Moving some capabilities to the application.properties solve the issue.
I used "other".capabilities and not the generic driver.capabilities.xxxx. Placing spesific capabilities in the env.resource will help keep the project organized.

**Comment by cjayswal** [comment]
Does it resolve your problem? can we close this?
