### ISSUE TITLE
With Jar files 2.1.11, Test cases are skipped while executing bdd steps with arguments as "Unable to invoke JavaStep with given arguments"

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#106]
With new Jar files 2.1.11 (**qaf-2.1.11-standalone.jar**), test cases are skipped with below error when executing bdd test steps with arguments.
These arguments are passed from xml.The same step is working fine with Jar files "**qaf-2.1.11-RC1-standalone.jar**".

**BDD step:**
Given I am a hot user having '${hotuser2.user.email}' and '${hotuser2.user.password}' credential

**Error:**
Unable to invoke JavaStep with given arguments: iAmAHotUserHavingAndCredential[${hotuser2.user.email}, ${hotuser2.user.password}] at 

**Data from XML:**
<?xml version="1.0" encoding="UTF-8"?>
<testdata>
	<hotuser2>
		<user>
			<email>test02@xxx.com</email>
			<password>password1</password>
		</user>
	</hotuser2>
</testdata>

**Comment by cjayswal** [comment]
this will be the case where your property provided with key represents map. For example:
```
hotuser2.user.email=some value
hotuser2.user.email.something=value of something
```
In above case you can notice that `hotuser2.user.email` is prefix in `hotuser2.user.email.something` so `hotuser2.user.email` represents map 
hotuser2.user.email = {"":"some value","something":"value of something"}

To fix it you can avoid key name to be prefix of other key if you are not providing map.

I am marking as bug to avoid such error where unknowingly property value results in map

**Comment by Priya335021** [comment]
Thanks for the update.

This is "hotuser2.user.email=some value" an unique key in my data file. 

And I dont have another key as "hotuser2.user.email.something=value of something".

Still getting error as

"Unable to invoke JavaStep with given arguments: iAmAHotUserHavingAndCredential[${hotuser2.user.email}, ${hotuser2.user.password}] at "

Hence unable to process bdd steps with arguments. Please fix this with priority.
