### ISSUE TITLE
How to Pass a String Array in JSON body- #API Automation using #QAF

### ISSUE THREAD

**Issue by APrem** [qmetry/qaf#107]
**Eg: We can Pass the JSON Array as below:

Body Content with JSON Array**

{"searchParams":[
        "elementName": "elementValue"

    ],
    "totalTime":"0|30",
    "noOfRecordsPerPage":"5",

}

**Script:**

		**JsonArray objArray = new JsonArray();
		objArray.add("elementName","elementValue");**

		JsonObject objTestBody = new JsonObject();
		objTestBody.add("searchParams",objArray  );
		objTestBody.addProperty("totalTime", "0|30");
		objTestBody.addProperty("noOfRecordsPerPage", "5");

**Now**

**Body content with String Array:**

{"searchParams":[
        "Value1",
        "Value2"

    ],
    "totalTime":"0|30",
    "noOfRecordsPerPage":"5",

}

**Please Any suggestions??**

Regards,
Prem

**Comment by cjayswal** [comment]
You can use [jersey-json](https://mvnrepository.com/artifact/com.sun.jersey/jersey-json) and use Java POJOs. Here is [good example](http://buraktas.com/jersey-client-example-with-json-support/). With [qaf-support-ws](https://github.com/qmetry/qaf-support-ws) you can provide request call and other test data outside the code.

**Comment by cjayswal** [comment]
Closing inactive issue. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
