### ISSUE TITLE
Screen shot for API failure step

### ISSUE THREAD

**Issue by nitindixit14** [qmetry/qaf#108]
Hi,

I have two BDD scenarions, first BDD for UI screen which has code to takes screen shot for Pass/fail BDD step. However,Second BDD is about to API steps automation. If we find API test case failure then failure step shows screenshot of earlier last screen shot of first BDD step.

**Comment by cjayswal** [comment]
As quick work around you can cleanup screenshot in step listener before execution method.

`TestBaseProvider.instance().get().setLastCapturedScreenShot("");`
