### ISSUE TITLE
Ivy:Unresolved Dependency error apache#xml-apis;1.0.b2: not found

### ISSUE THREAD

**Issue by garp360** [qmetry/qaf#109]
I am very new to your application and I am trying to run the blank-project demo tests but I have run into a road block:

[ivy:resolve] 	namespace not found for aopalliance#aopalliance;1.0: maven2
[ivy:resolve] 	namespace not found for asm#asm;3.1: maven2
[ivy:resolve] 	namespace not found for dom4j#dom4j;1.6.1: maven2
[ivy:resolve] 		module not found: apache#xml-apis;1.0.b2
[ivy:resolve] 	==== central: tried
[ivy:resolve] 	  https://repo1.maven.org/maven2/apache/xml-apis/1.0.b2/xml-apis-1.0.b2.pom
[ivy:resolve] 	  -- artifact apache#xml-apis;1.0.b2!xml-apis.jar:
[ivy:resolve] 	  https://repo1.maven.org/maven2/apache/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
[ivy:resolve] 	==== QAF: tried
[ivy:resolve] 	  https://qmetry.github.io/qaf/dist/apache/xml-apis/1.0.b2/xml-apis-1.0.b2.pom
[ivy:resolve] 	  -- artifact apache#xml-apis;1.0.b2!xml-apis.jar:
[ivy:resolve] 	  https://qmetry.github.io/qaf/dist/apache/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
[ivy:resolve] 	==== jai: tried
[ivy:resolve] 	  https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/apache/xml-apis/1.0.b2/xml-apis-1.0.b2.pom
[ivy:resolve] 	  -- artifact apache#xml-apis;1.0.b2!xml-apis.jar:
[ivy:resolve] 	  https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/apache/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 		::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 		:: apache#xml-apis;1.0.b2: not found
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::

**Comment by cjayswal** [comment]
I just give it try and worked for me. i can see resolved `xml-apis-1.3.03.jar` (not xml-apis-1.0.b2.jar) will you try again cleaning your ivy cache? This is dependency from third party and may be it get updated.

**Comment by cjayswal** [comment]
@garp360 are you still facing issue?

**Comment by cjayswal** [comment]
Closing issue as no response. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
