### ISSUE TITLE
ChromeDriver sessions close before all tests can complete in parallel mode.

### ISSUE THREAD

**Issue by ygsh** [qmetry/qaf#111]
Hi,

I am trying to run tests in parallel on my local using QAF 2.10.0 and Chrome browser. I am seeing that all the Chrome instances are closed as soon as the fastest test is completed. This causes the longer test to not complete as the browser is already closed.

Scenario:

1. Create three tests, all with differing execution duration.
2. Set testsng to run tests in parallel with thread-count as 2. Example below
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Mercury Demo" verbose="0" parallel="tests"
	thread-count="2">
	<test name="Registration">
		<classes>
			<class
				name="com.testdemo.mercury.full.testsuites.ResgitrationWithDataProvider" />
		</classes>
	</test> <!-- Test -->

	<test name="Login">
		<classes>
			<class name="com.testdemo.mercury.full.testsuites.LoginTest" />
		</classes>
	</test> <!-- Test -->

	<test name="Itinreary">
		<classes>
			<class name="com.testdemo.mercury.full.testsuites.ItineraryTest" />
		</classes>
	</test> <!-- Test -->
</suite> <!-- Suite -->
```
3. Execute test, as soon as the shortest test completes, all the chrome browsers are getting closed.

I see all the instances are closed when the below ChromeDriverHelper.teardownService() in com.qmetry.qaf.automation.ui.UiDriverFactory is called. 

```
	public void tearDown(UiDriver driver) {
		try {
			driver.stop();
			ChromeDriverHelper.teardownService();
			logger.info("UI-driver tear down complete...");
		} catch (Throwable t) {
			logger.error(t.getMessage());
		}
	}
```

Please check.

**Comment by cjayswal** [comment]
It looks like related to #69 which get fixed in 2.1.11. Will you please check with 2.1.11?

**Comment by ygsh** [comment]
Thank you for the update, I will update after testing with version 2.1.11.

**Comment by ygsh** [comment]
Working fine with 2.1.11
