### ISSUE TITLE
When importing in eclipse and executing already existing QAF project (using QAS), scenarios not get executed

### ISSUE THREAD

**Issue by githubdilip** [qmetry/qaf#112]
Hi Team, Please help with the below issue:

In eclipse  installed TestNG plugin, BDD editor plugin, Apache IvyDE plugin
And imported already existing QAF project using QAS

When I execute the config file, scenarios not getting executed.  Please let me know what are the other files I need to add or update.

Thanks,
Dilip

**Comment by githubdilip** [comment]
PFB the config file used:

<?xml version="1.0" encoding="UTF-8"?>
<suite name="DeMo">
  <parameter name="driver.name" value="chromedriver" />
	<parameter name="step.provider.pkg"
		value="com.automation.web;com.automation.common"></parameter>
	<parameter name="wd.command.listeners"
		value="com.automation.common.SeleniumWebDriverListener"></parameter>
		
  <parameter name="scenario.file.loc" value="scenarios/Registration.bdd"/>
  <test verbose="2" name="BDD Test">
  <parameter name="driver.name" value="chromedriver"/>
    <groups>
      <run>
        <include name="SMOKE"/>
      </run>
    </groups>
        <classes>
      <class name="com.infostretch.automation.step.client.text.BDDTestFactory"/>
    </classes>
    
  </test> 
</suite>

**Comment by amitbhoraniya** [comment]
Can you share console log which error you are facing?

**Comment by githubdilip** [comment]
Hi Amit,

PFB the console output. We don’t see any errors, but the scenarios now getting considered while execution.

[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
log4j:WARN No appenders could be found for logger (com.infostretch.automation.testng.pro.QAFAnnotationTransformer2).
log4j:WARN Please initialize the log4j system properly.
include groups [SMOKE]
exclude groups: [] Scanarios location: scenarios/Registration.bdd
[TestNG] Running:
  D:\HEB automation\EclipseProject1\config\registeration_config.xml


===============================================
    BDD Test
    Tests run: 0, Failures: 0, Skips: 0
===============================================


===============================================
HEBDeMo
Total tests run: 0, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@1cab519: 62 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@102b3b1: 0 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@1567f1: 5 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@e92674: 44 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 5 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@d4004b: 3 ms
Preparing For Shut Down...


Thanks,
Dilip

**Comment by githubdilip** [comment]
Hi Amit,

We are getting the following error in console:

/**
* Auto-generated code snippet by QMetry Automation Framework.
*/
@QAFTestStep(description="I click Register on landing page")
public void iClickRegisterOnLandingPage(){
	//TODO: remove NotYetImplementedException and call test steps
	throw new NotYetImplementedException();
}

===============================================
DeMo
Total tests run: 1, Failures: 0, Skips: 1
===============================================

Please do the needful.

Thanks,
Dilip

**Comment by infoneershalin** [comment]
This is because step is not found.
Please check the step.provider.pkg property value.
It should point to proper package where your steps are implemented.

If step.provider.pkg is proper then please provide bdd scenario and java file, which will help to debug.

**Comment by cjayswal** [comment]
Closing inactive issue. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
