### ISSUE TITLE
Unable to trigger @AfterMethod, @BeforeMethod calls using QAF BDD tests.

### ISSUE THREAD

**Issue by ygsh** [qmetry/qaf#114]
Hi,

We are looking to automate BDD scenarios and have written scenario file and we are able to run the test cases fine.

`<!DOCTYPE`` suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Bdd demo TestApp Application" verbose="0">
	<test name="Bdd demo TestApp Application Tests" enabled="true">
		<parameter name="scenario.file.loc" value="scenarios\TestApp.bdd" />
		<parameter name="step.provider.pkg" value="com.bdddemo.TestApp.full.steps" />
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory"></class>
		</classes>
	</test>
</suite>
`
The big requirement is we need to do data conditioning before each complete test case (BDD Scenario) is executed using TestNG annotations @BeforeMethod and once this is done we need to call @AfterMethod to do driver management. How do we achieve this since tests steps are getting passed as parameter rather than TestNG methods and the TestNG.xml can only pass one class (com.qmetry.qaf.automation.step.client.text.BDDTestFactory) name inside as TestNG class?

Also, if we implement QAFTestStepListener, actions are performed after every step, what I need is to execute after and before one complete scenario is executed (I want to set parameters before one secnario starts and I want to close the browser at the end of scenario)

**Comment by cjayswal** [comment]
You can create and use TestNG listener.
In BDD if you have some precondition for each scenario you can use `background` refer https://github.com/qmetry/qaf/blob/master/test/resources/scenarios/scenariosWithBackground.bdd

In order to close browser (tear down driver) after each testcase you can set property `selenium.singletone=method` this will tear down driver after each testcase (will result in increased execution time because for each testcase it will create new driver session).

**Comment by ygsh** [comment]
Thank you. I am exploring using TestNG listeners. 
When I use background in the scenario file, background action of all scenarios are executed before the start of tests, I was actually looking to trigger background before each scenario. 
Setting selenium.singleton=method works well in order to close the browser after test execution.

**Comment by cjayswal** [comment]
Background will executed before each scenario

**Comment by ygsh** [comment]
Thank you. We have implemented ITestListener and are doing our setup actions in "onStart" and "onTest/Success/Failure/Skipped" since we want to do actions before each test (scenario) starts and also after each test completes.

**Comment by AnbarasuMurugesan** [comment]
> Thank you. We have implemented ITestListener and are doing our setup actions in "onStart" and "onTest/Success/Failure/Skipped" since we want to do actions before each test (scenario) starts and also after each test completes.

@ygsh  @cjayswal  I am new to testNG and QAF framework. Our existing automation framework has @BeforeMethod and @AfterMethod ( store ITestResult ). How to trigger those methods when I use BBD2TestFactory2? 
Please share me sample ITestListener to refer?

**Comment by amitbhoraniya** [comment]
Create a new TestNG listener class.
```java
public class TestListener implements ITestListener {
  @Override
  public void onTestStart(ITestResult result) {
    // this method will be called before each scenario
  }

  @Override
  public void onTestSuccess(ITestResult result) {
    tearDown(result);
  }

  @Override
  public void onTestFailure(ITestResult result) {
    tearDown(result);
  }

  @Override
  public void onTestSkipped(ITestResult result) {
    tearDown(result);
  }

  @Override
  public void onTestFailedButWithinSuccessPercentage(ITestResult result) {
    tearDown(result);
  }

  private void tearDown(ITestResult result) {
    // this method will be called after each scenario
  }

  @Override
  public void onStart(ITestContext context) {}

  @Override
  public void onFinish(ITestContext context) {}
}
```

Then register listener class in your testng_config.xml
```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="QAF Demo">
    <listeners>
        <listener class-name="<yourpackage>.TestListener"/>
    </listeners>
    <test name="Sample Test">
        <classes>
            <class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory2"/>
        </classes>
    </test>
</suite>
```

**Comment by AnbarasuMurugesan** [comment]
> Create a new TestNG listener class.
> 
> ```java
> public class TestListener implements ITestListener {
>   @Override
>   public void onTestStart(ITestResult result) {
>     // this method will be called before each scenario
>   }
> 
>   @Override
>   public void onTestSuccess(ITestResult result) {
>     tearDown(result);
>   }
> 
>   @Override
>   public void onTestFailure(ITestResult result) {
>     tearDown(result);
>   }
> 
>   @Override
>   public void onTestSkipped(ITestResult result) {
>     tearDown(result);
>   }
> 
>   @Override
>   public void onTestFailedButWithinSuccessPercentage(ITestResult result) {
>     tearDown(result);
>   }
> 
>   private void tearDown(ITestResult result) {
>     // this method will be called after each scenario
>   }
> 
>   @Override
>   public void onStart(ITestContext context) {}
> 
>   @Override
>   public void onFinish(ITestContext context) {}
> }
> ```
> 
> Then register listener class in your testng_config.xml
> 
> ```
> <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
> <suite name="QAF Demo">
>     <listeners>
>         <listener class-name="<yourpackage>.TestListener"/>
>     </listeners>
>     <test name="Sample Test">
>         <classes>
>             <class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory2"/>
>         </classes>
>     </test>
> </suite>
> ```

Thanks for Sharing. In my automation framework, I have existing TestListenerImpl, Can I reuse those listener class in testng xml as listener  to invoke @BeforeSUite, @BeforeMethod ? 

OR 

In my automation framework, @BeforeSuite, @BeforeMethod, @AfterMethod and @BeforeMethod are mentioned in more than two class files. Do I need to copy those code into TestListener class (OnStart/OnTestStart/tearDown) ?
