### ISSUE TITLE
Execution is not kick starting if we execute with PMReportListenr in config file

### ISSUE THREAD

**Issue by githubdilip** [qmetry/qaf#116]
Execution is not kick starting if we execute with PMReportListenr in config file.
We are getting error as "org.testng.internal.TestNGMethod cannot be cast to com.qmetry.qaf.automation.step.client.TestNGScenario"

Config file used:
<?xml version="1.0" encoding="UTF-8"?>
<suite name="CERT1: iOS Smoke Suite" parallel="tests"
	thread-count="1">
	<parameter name="driver.name" value="appiumDriver" />

	<parameter name="appium.additional.capabilities"
		value="{'automationName':'PerfectoMobile','platformName':'iOS','driver.class':'io.appium.java_client.ios.IOSDriver','applicationName':'Beta'}" />

	<parameter name="env.resources" value="resources/qa/ios;resources/users/ios/cert1"></parameter>

	<parameter name="step.provider.pkg"
		value="com.heb.automation.common;com.heb.automation.ios"></parameter>
	<parameter name="wd.command.listeners"
		value="com.heb.automation.common.IOSPerfectoDriverListener"></parameter>
	<parameter name="we.command.listeners"
		value="com.heb.automation.common.IOSWebElementListener"></parameter>
![with pm listener](https://user-images.githubusercontent.com/22323975/26867629-bc64b256-4b83-11e7-8291-58cf222b6140.PNG)

	<parameter name="scenario.file.loc" value="scenarios/test.bdd" />

 	<listeners>
		<listener class-name="com.heb.automation.common.PMReportListenr" />
	</listeners>  

	<test verbose="2" name="iOS: Browse module">
		<parameter name="driver.capabilities.deviceName" value="XXXXXX"></parameter>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
	</test>

</suite>

**Comment by cjayswal** [comment]
Please check/debug your PMReportListenr listener implementation. Also make sure that the QAF jar has precedence order in class path.

**Comment by cjayswal** [comment]
Closing inactive issue. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
