### ISSUE TITLE
How to set different additional capabilites of driver in same suite execution ?

### ISSUE THREAD

**Issue by SaiPriyanka** [qmetry/qaf#117]
Switching driver.additional.capabilites at run time in TestNG Test Tag level is not working, what is best way to set driver capabilities at run time. 
Driver object need to created when switching desired capabilites ?

Example TestNG Config.xml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="1" name="Testing Capabilites" >
  <parameter name="application" value="XXXX"/>
 

<test name="Mobile">
   <parameter name="chrome.additional.capabilities" value="{'chromeOptions':{'args':['--user-agent=Mozilla/5.0 (iPhone\\; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36\']}}"/>
    <classes>
      <class name="com.XXX.regression.mobile.XX">
      
    
	</class> 
	</classes>
 </test>
    
  <test name="Desktop">
  <parameter name="chrome.additional.capabilities" value="{'chromeOptions':{'args':['--user-agent=Mozilla/5.0 (Windows NT 6.1\; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36']}}"/>
    <classes>
      <class name="com.XXX.regression.desktop.XX">
      
		</class>     
		
	
    </classes>
  </test>

**Comment by cjayswal** [comment]
Will you please provide QAF version and other related information?

**Comment by SaiPriyanka** [comment]
QAF Version - 2.1.10
Steps To Reproduce:
1. Write a test case that opens any URL 
2. Add this test case to TestNG.xml in two different test tags with different "chrome.additional.capabilites" one for mobile and browser as specified in above
3. Run the testNG xml file 

Actual:
- Both test cases open in chrome.additional.capabilites set initially instead of overriding in second test tag.

**Comment by cjayswal** [comment]
Does you config file looks like below and it is not working?

```
<test name="TS-1" >
	<parameter name="chrome.additional.capabilities" value="{capability-map1}"></parameter>
	<classes>
		<class name=""></class>
	</classes>
</test>

<test name="TS-2" >
	<parameter name="chrome.additional.capabilities" value="{capability-map2_or_empty_for_default_capabilities}"></parameter>
	<classes>
		<class name=""></class>
	</classes>
</test>

```
Also keep in mind that <driverName>.capabilities.<capabilityName> has highest priority.

**Comment by SaiPriyanka** [comment]
Yes i am aware that .capabilities has high priority and which we never use.
Above example doesn't work.

**Comment by cjayswal** [comment]
@SaiPriyanka will you please share xml config file? We did try to reproduce the issue and found working fine at our end with qaf-2.1.10.

**Comment by cjayswal** [comment]
Closing inactive issue. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
