### ISSUE TITLE
Issue with Web Drivers

### ISSUE THREAD

**Issue by Vishnu3012** [qmetry/qaf#120]
Hi , 
We are using QAF to automate both mobile (via PerfectoMobile) & Desktop -web based applications.
For Web, I am able to launch Chrome browser but the IE Driver is not being launched.

For IE Driver - The Below error
**TestNG: Initializing Driver...browser_str:iExplorerDriver,base_url:,sel_server:localhost,port:4444 
TestNG: Driver: iExplorerDriver 
Unable to create driver instance in 1st attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for iexplorer: java.lang.NoSuchMethodException: org.openqa.selenium.ie.InternetExplorerDriver.<init>(java.net.URL, org.openqa.selenium.Capabilities)
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'xxxxxxxx', ip: '1.2.3.4', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: unknown**

For Chrome Driver: 
Before the launch of browser,  I get an Error Loading Extension Pop Up

![image](https://user-images.githubusercontent.com/29592596/27373770-30133232-5687-11e7-910e-4ece70aaba64.png)

Can you help me with the IEDriver thing?

**Comment by cjayswal** [comment]
This looks like your local environment or settings issue and not specific to QAF. You can refer [throubleshooting-internetexplorerdriver](https://github.com/seleniumQuery/seleniumQuery/wiki/seleniumQuery-and-IE-Driver#throubleshooting-internetexplorerdriver). From the message it seems that you may need to connect to your administrator to for few permissions.

**Comment by Vishnu3012** [comment]
Thanks Chirag.
I have taken a look at the troubleshooting link you have provided.
It appears to me that due to Org wide IT restrictions, we cannot modify the settings ( are disabled).
In the link you have provided, I see a code snippet to help overcome this handicap via code

ieCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);

However, I am clueless where to update this in Quantum. Can you tell me how to ? Should I update this in application.properties or update in mainscreenpage.java file?

**Comment by cjayswal** [comment]
You can do that by setting driver capabilities using [properties](https://qmetry.github.io/qaf/latest/setting_driver_capabilities.html) or using [webdriver-listener](https://qmetry.github.io/qaf/latest/qaf_listeners.html#webdriver-listener) in `beforeInitialize(Capabilities)`

**Comment by Vishnu3012** [comment]
I have tried both the ways.

First way: Updating Application Properties
I have updated below details

driver.name=iExplorerDriver
webdriver.ie.driver=C:\\temp\\IEDriverServer.exe
iExplorer.capabilities.ignoreProtectedModeSettings=true

This wasnt launching the IE browser.

Next , tried updating the listener file in beforeInitialize(Capabilities)
![image](https://user-images.githubusercontent.com/29592596/27514162-d9ac149c-599f-11e7-91ed-b3b5f99f06c2.png)

This is launching multiple browsers but not launching any scripts, 
What is missing here?

**Comment by cjayswal** [comment]
you need to set `webdriver.ie.driver` as system property or set
``` properties
system.webdriver.ie.driver=C:\temp\IEDriverServer.exe
```

**Comment by Vishnu3012** [comment]
This is not working yet.

I have gone through the https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration
for IE Config details ( I am using IE11) , understand that below settings should be true for the IE to work as expected. Can someone confirm?

For 64-bit Windows installations, the key is HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. Please note that the FEATURE_BFCACHE subkey may or may not be present, and should be created if it is not present. Important: Inside this key, create a DWORD value named iexplore.exe with the value of 0.

Right now, due to IT org restrictions this is not possible, I am following up though. Any other alternative please.

**Comment by cjayswal** [comment]
closing as it is specific to your environment.
