### ISSUE TITLE
QAF BDD editor Eclipse plugin manual install

### ISSUE THREAD

**Issue by brianhclark** [qmetry/qaf#121]
We are trying to implement QAF in an org where access to the Eclipse Marketplace is restricted, is there any availability of a manual installation file for the QAF bdd editor plugin for Eclipse?

**Comment by cjayswal** [comment]
You can try by using [update site](https://qmetry.github.io/qaf/editor/bdd/eclipse/). Location of  a site for QAF Editors is https://qmetry.github.io/qaf/editor/bdd/eclipse/.

**Comment by brianhclark** [comment]
Unfortunately, Eclipse update is completely disabled. Is there any option for manual install?

**Comment by infoneershalin** [comment]
download following directory and provide this to eclipse as local repository

[plugin](https://github.com/qmetry/qaf/tree/gh-pages/editor/bdd/eclipse)

You can either checkout the repo and get it or download zip of gh-pages branch.

**Comment by cjayswal** [comment]
Closing inactive issue. If required further help post into [users group](https://groups.google.com/forum/#!forum/qaf-users).

**Comment by RAKESH-coder-tech** [comment]
For latest eclipse this zip is not working, getting error like cannot complete the installation
