### ISSUE TITLE
Hard coded JQuery CDN location

### ISSUE THREAD

**Issue by jmresler** [qmetry/qaf#123]
I noted in the file JavaScriptHelper.java that the method getJQueryInjectSnippet has a hard coded CDN url. This will fail if the CDN cannot be reached. As it stands, the exception that would be thrown would not indicate the real cause of the problem. I suggest adding a doc comment that indicates either a direct connection or a proxy setting is needed in order for the JQuery JS to be retrieved.

**Comment by cjayswal** [comment]
@jmresler, thanks for your input. Hope commit cc7005c takes care of your input. Please let us know if you have different thought.
