### ISSUE TITLE
Unable to pass dynamic value to locators using pageProps when the locator values are written using OR operator

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#125]
Below is the locator used in .loc file
selstore.btn.storeselectwithstoreid = {\"locator\":\"xpath=//*[@id='selectCategoryStore_%s'] | //*[@id='%s']/button\",\"desc\":\"ButtonView for Select button with respect to Store id\"}

Corresponding QAFWebElement:
	public QAFWebElement getSelstoreBtnStoreselectwithstoreid(String storeId){
		String loc = String.format(pageProps.getString("selstore.btn.storeselectwithstoreid"), storeId);
		return new QAFExtendedWebElement(loc);
	}

Due to this test case fails, since it has taken this as valid Element.
When single xpath is written for the locator, it has identified the element and it has passed.

**Comment by cjayswal** [comment]
will you provide more details of failure? for example, exception, expected behavior vs actual.
From above information it looks like you need to fix your code as below:
``` java
 String loc = String.format(pageProps.getString("selstore.btn.storeselectwithstoreid"), storeId, storeId);
```

**Comment by Priya335021** [comment]
Thank you for the correct code. It is working fine now. Able to pass dynamic value to locators.
