### ISSUE TITLE
Unable to set Capabilities for IE browser

### ISSUE THREAD

**Issue by Ramesh882** [qmetry/qaf#127]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.Using application properties we have given 
    2. driver.name=iExplorerDriver
    3. iExplorer.capabilities.ignoreProtectedModeSettings=true

### Expected behavior
It should launch IE browser

### Actual behavior
Getting the error as below:
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for iexplorer: java.lang.NoSuchMethodException: org.openqa.selenium.ie.InternetExplorerDriver

### Is the issue reproductible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Will you please provide qaf and selenium version you are using.

**Comment by Ramesh882** [comment]
Hi,

We are using selenium version:2.53.1
qaf version:2.1.11

Regards,
Ramesh.

**Comment by Ramesh882** [comment]
Hi Chirag,
I have stucked with this and it is a showstopper for us.Kindly help to provide the solution as soon as possible.
Regards,
Ramesh.

**Comment by cjayswal** [comment]
One of the observation is, ignoreProtectedModeSettings value is boolean, which will be passed as string when you use <driver>.capability.<capabilityName>. In such case you should use driver.additional.capabilities. Refer [setting driver capabilities](https://qmetry.github.io/qaf/latest/setting_driver_capabilities.html)
It may be the case of compatibility of driver, ie server with IE version. You should check with latest ie server and driver version.

**Comment by cjayswal** [comment]
Closing as no user response . Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
