### ISSUE TITLE
Are Cucumber @Before and @After hooks supported with Gherkin Scenarios?

### ISSUE THREAD

**Issue by brianhclark** [qmetry/qaf#128]
### QAF Version
>qaf-2.1.11

### Steps To Reproduce
    1.Add @Before annotation for stepDef method desired to run before scenario and import the cucumber.api.java.Before library
    2.Execute the feature file via testNG or Maven using GherkinScenarioFactory
    3.

### Expected behavior
The Cucumber before hook is executed prior to the scenario

### Actual behavior
Receive "java.lang.String; cannot be cast to java.lang.String" error from JavaStep.setMetaData(). I think this is due to cucumber.api.java.Before class returning either null or a String[] for any tagging attributed added after the annotation rather than a string as the QAFTestStep annotations do.

### Is the issue reproductible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

**Comment by cjayswal** [comment]
QAF is using TestNG runner not cucumber runner. So cucumber hooks are not supported. You can use TestNG Listeners instead. If You are migrating your existing cucumber tests Refer [documentation](https://qmetry.github.io/qaf/latest/gherkin_client.html#how-to-use-it). It looks there are people who successfully migrated form cucumber to QAF [according to this post](https://stackoverflow.com/questions/39899242/is-it-possible-to-migrate-from-cucumber-jvm-to-qaf)

**Comment by cjayswal** [comment]
Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
