### ISSUE TITLE
Ability to teardown driver by name 

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf#131]
https://github.com/qmetry/qaf/blob/3cf1ad13c594eb6dd8f753056fb7bfca5c9bd281/src/com/qmetry/qaf/automation/core/QAFTestBase.java#L171
It is useful to have functionality to teardown driver by name for use cases with more than one driver.
- Teardown driver by name
- Set driver name blank if it is current driver
- need to return  which driver will be used when driver name is blank and getBrowser() called

**Comment by kulin24** [comment]
This commit has broken the driver teardown when we are using multiple devices in a single scenario.
https://github.com/Project-Quantum/Quantum/issues/49

The driver teardown was working fine in the 2.1.12 version. It is failing as the following line of code is returning null:
if(getBaseUrl().equalsIgnoreCase(driverName)){

On analyzing this issue I found that the BaseURL and the other two parameters in stb are set to Null when we use setDriver(String driverName) method to switch drivers.

This is causing the NullPointer on driver quitting.

**Comment by kulin24** [comment]
Thanks for adding this fix immediately.
Is there any tentative date when the next release will be released?
