### ISSUE TITLE
Is there any property for driver/command session timeout?

### ISSUE THREAD

**Issue by genesisthomas** [qmetry/qaf#132]
### Steps To Reproduce
    We are getting Access denied issue during runtime. This is a random issue which is only appearing within a proxy environment. We are requesting to know if we can somehow increase the driver/command duration to see if this issue can be resolved.

application.properties:
driver.init.retry.timeout=60
selenium.wait.timeout=30000 

PROXY:
Had set up all http & https proxy host, port, user and password

### Expected behavior
1. No Access denied issue
2. Command duration timeout to be increased

### Actual behavior
11:48:48 <TITLE>Access Denied</TITLE>
11:48:48 </HEAD>
11:48:48 <BODY>
11:48:48 <FONT face="Helvetica">
11:48:48 <big><strong></strong></big><BR>
11:48:48 </FONT>
11:48:48 <blockquote>
11:48:48 <TABLE border=0 cellPadding=1 width="80%">
11:48:48 <TR><TD>
11:48:48 <FONT face="Helvetica">
11:48:48 <big>Access Denied (authentication_failed)</big>
11:48:48 <BR>
11:48:48 <BR>
11:48:48 </FONT>
11:48:48 </TD></TR>
11:48:48 <TR><TD>
11:48:48 <FONT face="Helvetica">
11:48:48 Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
11:48:48 </FONT>
11:48:48 </TD></TR>
11:48:48 <TR><TD>
11:48:48 <FONT face="Helvetica">
11:48:48 This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
11:48:48 </FONT>
11:48:48 </TD></TR>
11:48:48 <TR><TD>
11:48:48 <FONT face="Helvetica" SIZE=2>
11:48:48 <BR>
11:48:48 For assistance, contact helpdesk.
11:48:48 </FONT>
11:48:48 </TD></TR>
11:48:48 </TABLE>
11:48:48 <FONT face="Helvetica" SIZE=2>
11:48:48 <p>Client URL : tcp://****.perfectomobile.com:443/</p>
11:48:48 <p>Client IP Address : **********</p>
11:48:48 <p>Client Username : </p>
11:48:48 <p>Date & Time : [21/Aug/2017:11:48:38 +0800]</p>
11:48:48 <p>Reference Device : ********</p>
11:48:48 </blockquote>
11:48:48 </FONT>
11:48:48 </BODY></HTML>
11:48:48 Command duration or timeout: 14 milliseconds

### Is the issue reproductible on runner?
Issue happens while executing from eclipse, maven/ Jenkins

### Test case sample
> NA, random issue

**Comment by cjayswal** [comment]
The issue looks like wrong credentials/url used. Will you please post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or perfecto support group?
