### ISSUE TITLE
QAF to support output of cucumber.json file for Quantum

### ISSUE THREAD

**Issue by PhilippSchwarzePM** [qmetry/qaf#133]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1. Write any test using Gherkin in feature file 
    2. Run it

### Expected behavior
cucumber.json should be created in test-result folder.
The customer wants to use this to directly import results into Jira.
Find attached an expected cucumber.json example.

### Actual behavior
Instead, QAF specific json files are output.
Similar in content, but not accepted by Jira as they deviate from standard cucumber.json file syntax.

### Is the issue reproductible on runner?

- [x] QAS
- [x] Maven
- [ ] Gradle
- [] Ant
- [x ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
https://github.com/Project-Quantum/Quantum-Starter-Kit
Run any test using feature file- only qaf specific output json files are created.

Attached:
expected file- cucumber.json and ResultsToUpload.json
actual file generated by QAF- WeeklyMarkets.json
video showing how customer attempts to import results json into Jira

[cucumber.json.txt](https://github.com/qmetry/qaf/files/1248073/cucumber.json.txt)
[WeeklyMarkets.json.txt](https://github.com/qmetry/qaf/files/1248077/WeeklyMarkets.json.txt)
[ResultstoUpload.json.txt](https://github.com/qmetry/qaf/files/1248078/ResultstoUpload.json.txt)
[Json report upload into JIRA.arf.zip](https://github.com/qmetry/qaf/files/1248079/Json.report.upload.into.JIRA.arf.zip)

**Comment by cjayswal** [comment]
qaf doesn't use cucumber or cucumber runner so it is not generating cucumber report. You will get testng xml report in addition to qaf json report which is supported by different tools.  If you want cucumber report you need to run with cucumber runner or generate using testng report listener.
