### ISSUE TITLE
Data not fetching from Scenario Outline Example to Data Table in a step

### ISSUE THREAD

**Issue by sugatmankar** [qmetry/qaf#134]
### Test case sample

```
@SugatsDataTable
Scenario Outline:
  Given I test data table
    | a           | b     | c     |
    | <abc>-<qwe> | <xyz> | <pqr> |
  Examples:
    | abc | xyz | pqr | qwe   |
    | 12  | 14  | 15  | sugat |
```

Gherkin works with above format

```
@Given("^I test data table$")
public void iTestDataTable(DataTable dataTable){

List<DataTableRow> dataTableRows = dataTable.getGherkinRows();
List<String> headerList = dataTableRows.get(0).getCells();
ArrayList<HashMap<String, String>> dataList = new ArrayList<HashMap<String, String>>();
for (int i = 1; i < dataTableRows.size(); i++) {
    HashMap<String, String> dataMap = new HashMap<>();
    List<String> colList = dataTableRows.get(i).getCells();
    int colIndex = 0;
    for (String cellVal : colList) {
        dataMap.put(headerList.get(colIndex), cellVal.trim());
        colIndex++;
    }
    dataList.add(dataMap);
}

    for(HashMap<String,String> m : dataList){
        for(Map.Entry<String,String> entry : m.entrySet()){
            System.out.println(entry.getKey()+"*****"+entry.getValue());
        }
    }
}
```

Output: 
```
a*****12-sugat
b*****14
c*****15
```

but QMetry fails 

```
@QAFTestStep(description = "I test data table{0}")
public void iTestDataTableQmetry(Map<Object,Object> data) {
    for (Map.Entry<Object, Object> entry : data.entrySet()) {
        System.out.println(entry.getKey().toString()+"*************"+ entry.getValue().toString());
    }
}
```

Output :
```
a*************<abc>-<qwe>
b*************<xyz>
c*************<pqr>

```

**Comment by cjayswal** [comment]
will you try using ${param}?

**Comment by sugatmankar** [comment]
Thanks @cjayswal  it works 👍

**Comment by nikhilagrawal82** [comment]
@cjayswal @sugatmankar I am also using DataTable and exactly same scenario but getting below error:

**Error**
/**
* Auto-generated code snippet by QMetry Automation Framework.
*/
@QAFTestStep(description="I enter username{0}")
public void iEnterUsername(Object[] objArray0){
	//TODO: remove NotYetImplementedException and call test steps
	throw new NotYetImplementedException();
}

**Although step is implemented but still it is giving error.**

**test.feature**
 @GoogleLogin
    Scenario Outline:User Successfully Login to Application
      Given Test Admin on application login page
      When I enter username
        |username|<uname>|
      And I enter password as "Test123"
      Then Login should Pass
      Examples:
        | uname |
        |112233|

**stepdef.java**
 @QAFTestStep(description="I enter username")
    @When("^I enter username$")
    public void iEnterUsername(DataTable dataTable) throws Throwable{
        System.out.println("Test");
    }
