### ISSUE TITLE
teardown browser after each scenario run finish and create new for new scenario

### ISSUE THREAD

**Issue by sugatmankar** [qmetry/qaf#135]
### QAF Version 2.1.11
```

@feature1
Feature: two scenarios
@SugatsDataTable

Scenario Outline:
  Given I am on first scenario


Scenario Outline:
  Given I am on second scenario

```

I want to teardown browser after each scenario run finish and create new for new scenario.

I refereed issue https://github.com/qmetry/qaf/issues/114 ,
`
selenium.singletone=method
`
this property doesn't work , getting execption 

```
org.openqa.selenium.remote.SessionNotFoundException:
Session ID is null. Using WebDriver after calling quit()?
```

Any idea how to configure setting for QMetry ?

**Comment by cjayswal** [comment]
will you please try with 2.1.12?

**Comment by sugatmankar** [comment]
Hi @cjayswal ,

I tried with both version 2.1.11 and 2.1.12 both tear down the driver but once first scenario finish and tear down success , new instance of driver starts successfully but when it come to find element/s it throws

`[WebDriverCommandLogger] - command: findElements[ param-1: {value=//*[@id='abcd')], using=xpath}] Result: Session ID is null. Using WebDriver after calling quit()?`

I have web elements as Page Object pattern.
```
@FindBy(locator="xpath=pah of elements")
QAFWebElement element;
```

**Comment by sugatmankar** [comment]
My bad...teardown works for both versions, PageObject class must be extended by QAFWebComponent class otherwise above comments exception will get throw.

**Comment by cjayswal** [comment]
Thanks for update. FYI [to create page class](https://qmetry.github.io/qaf/latest/creatingtestpages.html) there there is `WebDriverBaseTestPage`. You also can use different [page design concepts](https://qmetry.github.io/qaf/latest/page_design_concepts.html). Purpose of component to have custom element like grid, calendar, item section etc. 

I would encourage to start utilizing [Users-group](https://groups.google.com/forum/#!forum/qaf-users) to get help and help other users. In this way we can keep git issues clean and for bugs, new features.

**Comment by Karthick1126** [comment]
HI @sugatmankar... I am facing the same problem while launch the browser for second scensrio...could you help

**Comment by Dakshesh123** [comment]
I am facing issue like session of is null. 
Browser is launched successfully for second scenario but not able to find elements.
Getting error like: Session ID is null, Using Webdriver after calling quite()??
