### ISSUE TITLE
How to read and get the data for sub child nodes of nodes under data element in XML files which is used for data driven testing

### ISSUE THREAD

**Issue by kalyani09** [qmetry/qaf#136]
### QAF Version 2.1.11
> Note: only the latest version is supported

### Steps To Reproduce
    1. create an test.xml file with <root>
                                                      <test>
                                                              <data>
                                                                            <a>a</a>
                                                                            <b>b</b>
                                                                            <c name="1">
                                                                               <y name="yyyy"/>
                                                                                <y name="dddd"/>
                                                                             </c>
                                                                              <c name="2">
                                                                                   <y name="zzzz"/>
                                                                                   <y name="eeee"/>
                                                               </data>
                                                    </test>
                                            </root>

    2. use this xml for data driven testing using @QAFDataProvider(name="test.data") 
    3. create a property variable for this in application.properties file as test.test.datafile=/test.xml
4.run the test case

### Expected behavior
able to get the data

### Actual behavior
getDataSetAsMap is throwing exception as array index out of bounds 

### Is the issue reproductible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
@QAFDataProvider(key="test.data")
@test
public void testMethod(Map<String, String> data)
{
//Here i need to know the count of how many nodes with <c> tag
List<c> listC= new ArrayList<>();
for(for int i=0; i<c.size(); i++)
{
listC.add("data.get("c"), data.get("y"));
}
runMethod(data.get("a"),data.get("b"),listC)
}

**Comment by cjayswal** [comment]
will you please ask questions in [user group](https://groups.google.com/forum/#!forum/qaf-users)?

**Comment by cjayswal** [comment]
Closing inactive issue. If required further help post into [users group](https://groups.google.com/forum/#!forum/qaf-users).
