### ISSUE TITLE
Unable to create driver instance. Please help

### ISSUE THREAD

**Issue by MrudulaTCS** [qmetry/qaf#141]
Hi,

Getting the below error:
Unable to create driver instance in 2nd attempt with retry timeout of 500 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'HYDTC221015783', ip: '172.31.34.126', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_40'
Driver info: driver.version: QAFExtendedWebDriver
Even after including below statements in the application.properties file, am still facing the same issue.
Could you please specify what exactly needs to be in the given in the host and port values.
system.http.proxyHost=<host>
system.http.proxyPort=<port>

**Comment by cjayswal** [comment]
will you please post this in [user group](https://groups.google.com/forum/#!forum/qaf-users)?

**Comment by cjayswal** [comment]
Closing inactive issue. If required further help post into [users group](https://groups.google.com/forum/#!forum/qaf-users).
