### ISSUE TITLE
Setting TestNG timeOut in Testng xml or method level open two instance of browser

### ISSUE THREAD

**Issue by rjnwl** [qmetry/qaf#142]
### QAF Version
2.1.10

### Steps To Reproduce
    1. set timeout in testng xml file or method 
    2. extends test class with WebDriverBaseTestPage<WebDriverTestPage>
    3.run any test method 

### Expected behavior
only single instance should be open

### Actual behavior
 opening two browsers and test method execute on second instance

### Is the issue reproductible on runner?

- [x] QAS
- [x] Maven
- [x] Eclipse

### Test case sample
//Executed on chrome and IE browsers
//Below using timeout at method level. and same behavior  with testng xml as well as listener method.setTimeout(4000)

     public class SampleTest extends WebDriverBaseTestPage<WebDriverTestPage> {
        @Test(timeOut=4000)
	public void test1() throws InterruptedException {
	getTestBase().getDriver().navigate().to("https://www.google.com/");

      }
    }

without extending WebDriverBaseTestPage<WebDriverTestPage>, its work fine -

    @Test(timeOut=4000)
	public void test1() throws InterruptedException {
	System.setProperty("webdriver.chrome.driver", "D:\\\\JavaJar\\\\chromedriver_win32\\\\chromedriver.exe");
	WebDriver driver=new ChromeDriver();
         driver.navigate().to("https://www.google.com/");
}

Thanks!

**Comment by rjnwl** [comment]
In the mean time you look into the issue, can you suggest me how I can set method timeout?

**Comment by cjayswal** [comment]
it should work, will you please check with latest version of QAF?

**Comment by cjayswal** [comment]
You have imported wrong class. Below code works fine for me:
```
public class SampleTest  extends WebDriverTestCase {
     @Test(timeOut=4000)
     public void test1() throws InterruptedException {
           getTestBase().getDriver().navigate().to("https://www.google.com/");
     }
}
```

Refer [Creating test cases](https://qmetry.github.io/qaf/latest/Creating_test_cases.html).
