### ISSUE TITLE
When the object is not identified it is closing the browser.How to prevent this kind of scenario

### ISSUE THREAD

**Issue by Ramesh882** [qmetry/qaf#143]
### QAF Version
> Note: only the latest version is supported
2.1.11
### Steps To Reproduce
    1.Update incorrect object path in the script
    2.
    3.

### Actual behavior
If  the driver did not identifies the specified object it getting closed.

### Is the issue reproductible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by Ramesh882** [comment]
Kindly help to provide the solution

**Comment by cjayswal** [comment]
Will you please post this in [user group](https://groups.google.com/forum/#!forum/qaf-users)?

**Comment by cjayswal** [comment]
Closing inactive issue. If required further help post into [users group](https://groups.google.com/forum/#!forum/qaf-users).
