### ISSUE TITLE
In QAF we have any option to get the html reports after executing the test cases, Like if object is present it will pass that step and if any object fails it should fail

### ISSUE THREAD

**Issue by Ramesh882** [qmetry/qaf#144]
### QAF Version
> Note: only the latest version is supported
2.1.11
### Steps To Reproduce
    1.Execute one end to end flow and see for the results
    2.
    3.

### Expected behavior
1.It should display the detailed report like the passed and failed

### Is the issue reproductible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by Ramesh882** [comment]
Kindly help to update on this issue

**Comment by cjayswal** [comment]
will you please post this in [user group](https://groups.google.com/forum/#!forum/qaf-users)?

**Comment by cjayswal** [comment]
Closing inactive issue. If required further help post into [users group](https://groups.google.com/forum/#!forum/qaf-users).
