### ISSUE TITLE
unable to update to latest version of Selenium when running firefox

### ISSUE THREAD

**Issue by Manolo2014** [qmetry/qaf#145]
### QAF Version
> Note: only the latest version is supported
I have tried 2.1.11, 2.1.12, 2.1.12-RC2 and 2.1.12-RC3
I was running successfully with version 3.0.0 but when trying to update to resolve an issue with firefox webdriver, I ran into this problem with QAF. I have looked at several closed issues in this repo.. #118 , #60 , #88 but was unable to find resolution.

### Steps To Reproduce
    1. update to latest version of selenium 3.5.3

POM included below:
<dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.qmetry</groupId>
            <artifactId>qaf</artifactId>
            
            <version>2.1.12-RC3</version>
        </dependency>
        <dependency>
            <groupId>com.qmetry</groupId>
            <artifactId>qaf-support</artifactId>
            <version>${qaf.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.jersey.contribs</groupId>
            <artifactId>jersey-multipart</artifactId>
            <version>1.19.4</version>
        </dependency>
        <dependency>
            <groupId>com.qmetry</groupId>
            <artifactId>qaf-qtm4j-updator</artifactId>
            <version>2.1.13-RC1</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.2.0</version>
        </dependency>

    </dependencies>

### Expected behavior
Tests run in firefox as they did with previous versions of Selenium

### Actual behavior
Running TestSuite
log4j:WARN No such property [follow] in org.apache.log4j.FileAppender.
[ConfigurationManager] - ISFW build info: {qaf-Type=core, qaf-Revision=12-RC3, qaf-Version=2.1, qaf-Build-Time=06-Aug-2017 11:49:43}
[ConfigurationManager] - Resource dir: /Users/swinters/IdeaProjects/AutomationTesting/resources. Found property files to load: 14
[ConfigurationManager] - Resource dir: /Users/swinters/IdeaProjects/AutomationTesting/resources. Found property files to load: 0
[QAFTestBase] - Initializing Driver...browser_str:remotefirefoxDriver,base_url:http://test.gcihub.com,sel_server:10.171.3.184,port:4444
[UiDriverFactory] - Driver: remotefirefoxDriver
[QAFTestBase] - Initializing Driver...browser_str:remotefirefoxDriver,base_url:http://test.gcihub.com,sel_server:10.171.3.184,port:4444
[QAFTestBase] - Initializing Driver...browser_str:remotefirefoxDriver,base_url:http://test.gcihub.com,sel_server:10.171.3.184,port:4444
[UiDriverFactory] - Driver: remotefirefoxDriver
[UiDriverFactory] - Driver: remotefirefoxDriver
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Error forwarding the new session webdriver new session JSON response body did not contain a session ID
Command duration or timeout: 3.93 seconds
[QAFTestBase] - Initializing Driver...browser_str:remotefirefoxDriver,base_url:http://test.gcihub.com,sel_server:10.171.3.184,port:4444
[UiDriverFactory] - Driver: remotefirefoxDriver
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Error forwarding the new session webdriver new session JSON response body did not contain a session ID
Command duration or timeout: 4.07 seconds
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Error forwarding the new session webdriver new session JSON response body did not contain a session ID
Command duration or timeout: 4.25 seconds
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Error forwarding the new session webdriver new session JSON response body did not contain a session ID
Command duration or timeout: 3.92 seconds
[QTM4JResultUploader] - QTM4J Integration is not enabled. To enable it set integration.param.qtm4j.enabled=true
Tests run: 4, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 8.889 sec
Preparing For Shut Down...
Preparing For Shut Down...
Preparing For Shut Down...

### Is the issue reproductible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by Manolo2014** [comment]
I am seeing the following error when I use selenium-java v 3.53.3 and selenium-support v 3.53.3

org.openqa.selenium.support.ui.FluentWait.withMessage(Lcom/google/common/base/Supplier;)Lorg/openqa/selenium/support/ui/FluentWait;

**Comment by cjayswal** [comment]
You need to use selenium-support v 3.0.0
It looks like you are using grid to run your test. If so did you provided webdriver.gecko.driver while starting up grid? You can test in your local environment by using `driver.name=firefoxDriver` and setting system property `system.webdriver.gecko.driver=<geckodriverpath>`

 This issue doesn't seems QAF compatibility webdriver issue.

**Comment by Manolo2014** [comment]
yes, I have set the system property for webdriver.gecko.driver on all of my grid nodes. this was working with version 3.0.0 of Selenium, but when I switch to version 3.53.3 it stops working.

**Comment by cjayswal** [comment]
Try without grid (as well as different driver) to find where the exact problem. This doesn't looks like QAF issue. Will you please post it in [qaf user group](https://groups.google.com/forum/#!forum/qaf-users)?

May be you can refer any of the following and other issues with same error:
* [7421 - Firefox WebDriver init problem - Error forwarding new session JSON response body did not contain a session ID](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7421)
* [4185 - Error forwarding the new session...](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4185)
* [WebDriver grid configuration throws error](https://stackoverflow.com/questions/24011694/webdriver-grid-configuration-throws-error)

**Comment by Manolo2014** [comment]
This issue can be closed. You are correct, it was not a QAF issue. my version of the Selenium Grid Hub was incorrect. I am using Docker and it was an old image.
