### ISSUE TITLE
QAF throws error while trying to connect to CrossBrowserTesting "Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure."

### ISSUE THREAD

**Issue by martinlienhard-minted** [qmetry/qaf#146]
### QAF Version
name="qaf" rev="latest.integration"

### Steps To Reproduce
This same issue occurs using both firefoxRemoteDriver and chromeRemoteDriver on CrossBrowserTesting with Selenium 3.5.3.

Followed the QAF documentation for Sauce Labs and modified for CrossBrowserTesting:
https://qmetry.github.io/qaf/latest/how_to_run_test_on_suace_lab.html
https://qmetry.github.io/qaf/latest/sauce_on_demand_integration.html

ivy.xml file snippet:

	dependencies
		dependency org="com.qmetry" name="qaf" rev="latest.integration" 
		dependency org="com.qmetry" name="qaf-support" rev="latest.integration" 
		dependency org="ant-contrib" name="ant-contrib" rev="1.0b3"
		dependency org="com.googlecode.jcsv" name="jcsv" rev="1.4.0" 
		dependency org="net.sourceforge.htmlunit" name="htmlunit" rev="2.24"
		dependency org="joda-time" name="joda-time" rev="2.9.7" 
		dependency org="mysql" name="mysql-connector-java" rev="5.1.40"
		dependency org="org.jasypt" name="jasypt" rev="1.9.2"
		dependency org="com.jcraft" name="jsch" rev="0.1.54"
		dependency org="javax.mail" name="javax.mail-api" rev="1.5.6"
		dependency org="com.saucelabs" name="saucerest" rev="1.0.32"
		dependency org="com.saucelabs" name="sauce_java_common" rev="2.1.21"
		dependency org="net.jsourcerer.webdriver" name="JSErrorCollector" rev="0.6-atlassian-3"
		dependency org="org.seleniumhq.selenium" name="selenium-remote-driver" rev="3.5.3" 
		dependency org="org.seleniumhq.selenium" name="selenium-java" rev="3.5.3" 
		dependency org="org.seleniumhq.selenium" name="selenium-support" rev="3.0.1" force="true" 
	dependencies

application.properties file snippet:

channel=desktop_web
env.baseurl=https://qa.minted.com/
env.resources=resources/extension;resources/images;resources/JsonData;resources/PropData;resources/XMLData;resources/assertMessages.properties;resources/${channel}
resources.load.subdirs=1
step.provider.pkg=com.minted.common;com.minted.${channel}
selenium.server=http://<username>:<access-key>@hub.crossbrowsertesting.com:80/wd/hub
scenario.file.loc=scenarios/${channel}
selenium.defaultBrowser=firefoxRemoteDriver
driver.name = ${selenium.defaultBrowser}
remote.server = ${selenium.server}
firefox.additional.capabilities={"platform":"Windows 10","browserName":"Firefox","version":"54"}
driver.init.retry.timeout=10
retry.count=0
report.log.skip.success=1
selenium.explicit.wait.timeout=60000
selenium.success.screenshots=0
check.broken.images=0
wd.command.listeners=com.minted.common.listeners.WDListener;
we.command.listeners=com.minted.common.listeners.SendKeysListener

### Expected behavior
Invokes a new RemoteWebDriver instance running in CrossBrowserTesting

### Actual behavior
TestNG console output:

log4j:WARN No appenders could be found for logger (com.qmetry.qaf.automation.testng.pro.QAFAnnotationTransformer2).
log4j:WARN Please initialize the log4j system properly.
...
... TestNG 6.10 by Cédric Beust (cedric@beust.com)
...

include groups []
 exclude groups: [] Scanarios location: scenarios/desktop_web/test/MartinTest.bdd 
[TestNG] Running:
  /Users/martin/Documents/github/minted-test-cases/src/SeleniumMinted/QAS/MintedAutomation/config/MartinTest.xml

[ThreadUtil] Starting executor timeOut:2147483647ms workers:1 threadPoolSize:6
[TestRunner] Starting executor for test Martin Tests with time out:2147483647 milliseconds.
#####::::BEFORE firefoxRemoteDriver
adding profile.........Firefox
#####:::: firefoxRemoteDriver
Unable to create driver instance in 1st attempt with retry timeout of 10 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'Martin-Lienhard-Mac.local', ip: 'fe80:0:0:0:8fa:a5e7:3348:6d3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: driver.version: QAFExtendedWebDriver
#####::::BEFORE firefoxRemoteDriver
adding profile.........Firefox
#####:::: firefoxRemoteDriver
Unable to create driver instance in 2nd attempt with retry timeout of 10 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'Martin-Lienhard-Mac.local', ip: 'fe80:0:0:0:8fa:a5e7:3348:6d3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: driver.version: QAFExtendedWebDriver
#####::::BEFORE firefoxRemoteDriver
adding profile.........Firefox
#####:::: firefoxRemoteDriver
Unable to create driver instance in 1st attempt with retry timeout of 10 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'Martin-Lienhard-Mac.local', ip: 'fe80:0:0:0:8fa:a5e7:3348:6d3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: driver.version: QAFExtendedWebDriver
#####::::BEFORE firefoxRemoteDriver
adding profile.........Firefox
#####:::: firefoxRemoteDriver
Unable to create driver instance in 2nd attempt with retry timeout of 10 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'Martin-Lienhard-Mac.local', ip: 'fe80:0:0:0:8fa:a5e7:3348:6d3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: driver.version: QAFExtendedWebDriver
#####::::BEFORE firefoxRemoteDriver
adding profile.........Firefox
#####:::: firefoxRemoteDriver
Unable to create driver instance in 1st attempt with retry timeout of 10 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'Martin-Lienhard-Mac.local', ip: 'fe80:0:0:0:8fa:a5e7:3348:6d3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: driver.version: QAFExtendedWebDriver
#####::::BEFORE firefoxRemoteDriver
adding profile.........Firefox
#####:::: firefoxRemoteDriver
Unable to create driver instance in 2nd attempt with retry timeout of 10 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'Martin-Lienhard-Mac.local', ip: 'fe80:0:0:0:8fa:a5e7:3348:6d3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: driver.version: QAFExtendedWebDriver
SKIPPED: EC-1823
         No Tier_paper_kind_id for RSVP Sample
com.qmetry.qaf.automation.core.AutomationError: Expected condition failed: Unable to create driver instance in 2nd attempt with retry timeout of 10 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure. (tried for 10 second(s) with 10 SECONDS interval)
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'Martin-Lienhard-Mac.local', ip: 'fe80:0:0:0:8fa:a5e7:3348:6d3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
Driver info: driver.version: QAFExtendedWebDriver
	at .When opens registration page(scenarios/desktop_web/test/MartinTest.bdd:20)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:667)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.execute(QAFExtendedWebDriver.java:234)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:175)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.<init>(QAFExtendedWebDriver.java:93)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.getDriver(UiDriverFactory.java:459)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.access$5(UiDriverFactory.java:438)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriver(UiDriverFactory.java:227)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.get(UiDriverFactory.java:94)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:511)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:410)
	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:198)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:47)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:1)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:86)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:93)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:62)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:58)
	at com.minted.desktop_web.pages.RegistrationPage.<init>(RegistrationPage.java:15)
	at java.lang.Class.newInstance(Class.java:442)
	at com.qmetry.qaf.automation.step.JavaStep.getClassInstance(JavaStep.java:311)
	at com.qmetry.qaf.automation.step.JavaStep.getStepProvider(JavaStep.java:190)
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:153)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:134)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:167)
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

===============================================
    Martin Tests
    Tests run: 1, Failures: 0, Skips: 1
===============================================

===============================================
Martin Automation Suite
Total tests run: 1, Failures: 0, Skips: 1
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@66d18979: 16 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@3c3d9b6b: 5 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@65d09a04: 3 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@707194ba: 7 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@45b4c3a9: 5006 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 4 ms

### Is the issue reproductible on runner?

- [ ] QAS
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
SCENARIO: EC-1823
META-DATA: {"description":"No Tier_paper_kind_id for RSVP Sample","groups":["Regression","IS","Transaction","NOTONPROD"],"author"="QA"}
	Given user opens minted website
	When opens registration page

**Comment by cjayswal** [comment]
Will you please make sure ` selenium.server=http://:@hub.crossbrowsertesting.com:80/wd/hub` that server url is correct? Did you provided credentials for hub if required?

**Comment by martinlienhard-minted** [comment]
Read this online documentation:
https://help.crossbrowsertesting.com/selenium-testing/getting-started/java/
Note the code:

URI uri = new URI(“http://“ + username + “:” + authkey +
“@hub.crossbrowsertesting.com:80/wd/hub”)
RemoteWebDriver driver = new RemoteWebDriver(uri.toURL(),
caps);System.out.println(driver.getSessionId());

Yes, I supplied my username and authkey, but I'm not going to publicly post
it online, so I removed it before posting the issue. I would recommend you
start a free trial and confirm that Cross Browser Testing works with QAF.


Regards,
Martin

**Comment by martinlienhard-minted** [comment]
Have you been able to get QAF working with CrossBrowserTesting?

**Comment by martinlienhard-minted** [comment]
This was a bug with CrossBrowserTesting and not QAF. They were not expecting the correct string format back from the Capabilities get platform name.

**Comment by cjayswal** [comment]
@martinlienhard-minted thanks for update.
