### ISSUE TITLE
Unable to launch Internet Explorer using QMetry

### ISSUE THREAD

**Issue by sunnysabhanam** [qmetry/qaf#148]
2.1.11 QAF Version

while using QMetry Framework for internet Explorer i am unable to launch Internet Explorer

driver.name=iExplorerDriver
iExplorer.capabilities.ignoreProtectedModeSettings=true

i tried with IE 9/10/11, 

### Expected behavior
Internet Explorer should be launched

### Actual behavior
throwing below error
Unable to create driver instance in 10th attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for iexplorer: java.lang.NoSuchMethodException: org.openqa.selenium.ie.InternetExplorerDriver.<init>(java.net.URL, org.openqa.selenium.Capabilities)
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'HIS-PCS-2995691', ip: '10.9.43.177', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: unknown

### Test case sample
    public class GoogleTestPage extends WebDriverBaseTestPage<WebDriverTestPage>{
	
	
    @FindBy(locator="Amazon.Tester.Enter")
    private QAFExtendedWebElement enterData;
	
	
	@Test
	public void testingGoogle() throws InterruptedException {
		driver.get("https:\\www.amazon.in");
		enterData.sendKeys("hello");
		Thread.sleep(5000);
	}

	@Override
	protected void openPage(PageLocator locator, Object... args) {
		
	}
    }

**Comment by cjayswal** [comment]
For none string value of capabilities you should use `<driverName>.capabilities.<capabilityName>`. for example:
```
iExplorer.additional.capabilities={'ignoreProtectedModeSettings':true}
```
Refer [Setting driver capabilities](https://qmetry.github.io/qaf/latest/setting_driver_capabilities.html)

**Comment by sunnysabhanam** [comment]
Hi cjayswal, I had made the necessary changes in application.properties file.

driver.name = iExplorerdriver
system.webdriver.ie.driver=D:\\Selenium\\IEDriverServer.exe **my64-bit IEDriver Location**
iExplorer.additional.capabilities={'ignoreProtectedModeSettings':true}

my system is 64-bit Windows. I had Enabled Protected Mode for all Zones.
and enabled "Enable Enhanced Protected Mode*" under Security Heading in Adavnced Tab in Internet Options.

Internet Explorer is starting now, but it is not getting navigated to any page. 
Error is displayed as SessionNotFoundException.

**Comment by cjayswal** [comment]
You also should try adding `ignoreZoomSetting` capability. For Example:
```
iExplorer.additional.capabilities={'ignoreProtectedModeSettings':true, 'ignoreZoomSetting':true}
```
You should refer [IE-Driver wiki page](https://github.com/seleniumQuery/seleniumQuery/wiki/seleniumQuery-and-IE-Driver) and questions like
[Getting `SessionNotFoundException` while launching IE from WebDriver](https://stackoverflow.com/questions/14936916/getting-sessionnotfoundexception-while-launching-ie-from-webdriver)
[Not able to launch IE browser ](https://stackoverflow.com/questions/14952348/not-able-to-launch-ie-browser-using-selenium2-webdriver-with-java)

Please post/discuss in [users group](https://groups.google.com/forum/#!forum/qaf-users) instead of git issue. Even if you get it resolve please post with the solution for benefit of other users.

**Comment by cjayswal** [comment]
Closing inactive issue. If required further help post into [users group](https://groups.google.com/forum/#!forum/qaf-users).

**Comment by nakulkhargonkar** [comment]
Below setting worked for me
iexplorer.additional.capabilities={'ignoreProtectedModeSettings':true,'nativeEvents':false,'unexpectedAlertBehaviour':accept,'enablePersistentHover':true,'ignoreZoomSetting':true,'requireWindowFocus':true}

IE v 11.1087
Selenium v 3.141.59
QAF v 2.1.14
Win 10 64bit
