### ISSUE TITLE
qaf-2.1.7b.jar & qaf-support-2.1.7b.jar doesn't include qmetry package 

### ISSUE THREAD

**Issue by Nandesh7** [qmetry/qaf#149]
### QAF Version : 2.1.7b

I am referring to a sample test case posted on https://qmetry.github.io/qaf/latest/Creating_test_cases.html. It says, to create test class & extend to WebDriverTestCase. I am able to extend WebDriverTestCase but it doesn't come from com.qmetry.qaf.automation.ui.WebDriverTestCase rather it comes from com.infostretch.automation.ui.WebDriverTestCase. Later, I found that qaf-2.1.7b.jar & qaf-support-2.1.7b.jar both jar's doesn't include a package com.qmetry. Request to make the appropriate jars available

### Expected behavior
A jar with com.qmetry be made available to execute sample project 

### Is the issue reproductible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by amitbhoraniya** [comment]
If QAF version >= 2.1.8, then its  com.qmetry.qaf package.
For QAF version < 2.1.8 then it was com.infostretch.automation.

**Comment by infoneershalin** [comment]
@Nandesh7 If you are planning to use QAF, please use latest version to get all new features' and more support

**Comment by mishalhshah** [comment]
Hi Nandesh,

Please use QAF version 2.1.8 or above to support ‘com.qmetry.qaf’ package.

Thanks,
Mishal Shah

**Comment by Nandesh7** [comment]
Could you please help me with a link to download QAF  2.1.8 version? I am unable to locate on Qmetry site. Thanks

**Comment by mishalhshah** [comment]
https://github.com/qmetry/qaf

https://qmetry.github.io/qaf/latest/download.html

Thanks,
Mishal Shah

**Comment by Nandesh7** [comment]
I downloaded & added a QAF jar 2.18 & 2.1.9 respectively & still can't see the expected method showing up "getDriver().get();"from com.qmetry.qaf.automation.ui.WebDriverTestBase. It would be helpful if any one can refer to detailed documentation on how to set up & test a sample test case. Thanks in advance.

**Comment by cjayswal** [comment]
I would recommend walk through [qaf-step-by-step-tutorial](https://github.com/qmetry/qaf-step-by-step-tutorial/wiki). For any new automation use latest version of QAF.

**Comment by cjayswal** [comment]
Closing inactive issue. If required further help post into [users group](https://groups.google.com/forum/#!forum/qaf-users).
