### ISSUE TITLE
How is AbstractTestCase linked to UiTestBase<D> in QAF 2.18 version?

### ISSUE THREAD

**Issue by Nandesh7** [qmetry/qaf#151]
### QAF Version
2.18

I am new to QAF 2.18 & trying to understand how an AbstractTestCase is able to accept a type parameter using Generic's in below case.

public abstract class AbstractTestCase<D, B extends UiTestBase<D>>
The WebDriverTestCase extends AbstractTestCase<D, B extends UiTestBase<D>> that said, the AbstractTestCase must and should make a use of Interface UiTestBase or the classes that have the implementation of the interface UiTestBase<D>. I tried to drill down more & couldn't find that QAFExtendedWebDriver and WebDriverTestBase classes don't implement UiTestBase in any way. 

public class WebDriverTestCase extends AbstractTestCase<QAFExtendedWebDriver, WebDriverTestBase>

Could anyone help me understand how is this working? Thanks in advance.

**Comment by cjayswal** [comment]
Will you please post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) and close here?

**Comment by Nandesh7** [comment]
I've added the post to Google groups, could you please clarify now

**Comment by cjayswal** [comment]
Closing as a issue  type of help/question and moved to user group.
