### ISSUE TITLE
result file generation for scenario name with some special characters is not working

### ISSUE THREAD

**Issue by infoneershalin** [qmetry/qaf#153]
### QAF Version
2.1.12

### Steps To Reproduce
    

1. Create a scenario with name containing any of `\/:*?"<>|`
2. Execute the scenario
3. Open dashboard.htm and try to view the results, it will not work as json files for storing results are not created on windows machine.This is due to file name limitation from Windows OS.

### Expected behavior
QAF should not execute such scenarios/Provide warnings during execution.

### Actual behavior
QAF executes scenarios but viewing results is difficult.Also parsing the result file for QTM4J integration is not feasible

### Is the issue reproducible on runner?

- [x] QAS
- [x] Maven
- [x] Gradle
- [x] Ant
- [x] Eclipse

### Test case sample

```

SCENARIO: Verify Homepage > Login Section Verification
META-DATA: {"description":"Verify Login section is available on HomePage","groups":["SMOKE"]}
	COMMENT: 'scenario with special character'	
END
```

**Comment by cjayswal** [comment]
@infoneershalin Did you added any test case for this?
