### ISSUE TITLE
Unable to integrate headless browser in QAF(Qmetry Automation Framework) given by recording Plugin.

### ISSUE THREAD

**Issue by dcjefferies** [qmetry/qaf#157]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
1. Recorded two-three pages by Recording plugin.
    
2 .Make following changes to application.properties
        driver.name=otherDriver
        other.additional.capabilities=
         {'driverClass':'org.openqa.selenium.phantomjs.PhantomJSDriver'}
       system.phantomjs.binary.path=<PHANTOMJS_BINARY_PATH>

3   Add below dependencies in pom if project type is maven
<dependency>
<groupId>com.codeborne</groupId>
<artifactId>phantomjsdriver</artifactId>
<version>1.4.3</version>
</dependency>
<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-remote-driver</artifactId>
<version>3.4.0</version>
</dependency>

This is all required to use phantomJS which supports headless automation with WebDriver protocol support.
   
4 Run the pom.xml by Maven

### Expected behavior
 Code should run in the Headless mode.

### Actual behavior
Headless mode is not running.

### Is the issue reproducible on runner?

- [x] QAS---------Yes
- [ ] Maven-------Yes
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Are you getting any exception? if so please provide that details. When using selenium 3+ make sure you have added selenium-support version 3.0.0
```xml
<!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-support -->
<dependency org="org.seleniumhq.selenium" name="selenium-support" rev="3.0.0"/>
```

**Comment by raviguptasmarsh** [comment]
@dcjefferies Did you find a solution for this ?

**Comment by cjayswal** [comment]
Closing as not bug or feature request and inactive since more than a year.

**Comment by cjayswal** [comment]
If you want to set capability programmatically, you can use [driver listener](https://qmetry.github.io/qaf/latest/qaf_listeners.html#webdriver-listener).  Refer [answer](https://stackoverflow.com/a/45341056/861594) of similar question for another way to set capability through code using [driver listener](https://qmetry.github.io/qaf/latest/qaf_listeners.html).

**Comment by LazioKarisma** [comment]
oke, thanks @cjayswal .
I can use headless browser by adding chrome option code in application.properties:

`chrome.additional.capabilities={"goog:chromeOptions":{"args":["--allow-outdated-plugins","--always-authorize-plugins","--headless --disable-gpu","-disable-extensions"],"prefs":{"profile.default_content_settings.popups":0,"download.default_directory":"C:/AutoScript/id_crm_quantum/src/main/resources/driver","credentials_enable_service":false,"profile.password_manager_enabled":false}}}`
