### ISSUE TITLE
appiumDriver: -Unable to create driver instance in 1st attempt 

### ISSUE THREAD

**Issue by nitinbehrani** [qmetry/qaf#161]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.appium.additional.capabilities= {'app':'/qaf-example-project/src/ApiDemos-debug.apk','deviceName':'5554:Nexus_5_API__23_x86','platformName':'Android','automationName':'Appium','driver.class':'io.appium.java_client.android.AndroidDriver'}

    2.driver.name=appiumDriver
    3.remote.server=127.0.0.1
    4.remote.port=4723
5. selenium.wait.timeout=30000

### Expected behavior
The ApiDemos-debug.apk should open successfully on the Android device 

### Actual behavior

[testng] [UiDriverFactory] - Driver: appiumDriver
   [testng] Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for appium: java.lang.reflect.InvocationTargetException
   [testng] Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
### Is the issue reproducible on runner?

- [x] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
did you seen appium server logs? if it complains file not found then you need to correct app path. With QAF-2.1.12 `project.path` property available to get project absolute path. So you can provide capability value as like `'app':'${project.path}/src/ApiDemos-debug.apk'`

**Comment by nitinbehrani** [comment]
Thanks for the help i was able to resolve the problem by updating
'app':'${project.path}/src/ApiDemos-debug.apk'
remote.server=localhost

**Comment by nitinbehrani** [comment]
Thanks for the help i was able to resolve the problem by updating
'app':'${project.path}/src/ApiDemos-debug.apk'
remote.server=localhost

**Comment by cjayswal** [comment]
Glad to hear.
Please post problems, questions etc in [users-group](https://groups.google.com/forum/#!forum/qaf-users) and help github issues to manage for bug and features requests.
