### ISSUE TITLE
Using report tool from Jenkins

### ISSUE THREAD

**Issue by hadasshani** [qmetry/qaf#166]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1. 
### Expected behavior

 How can I view tests results in Jenkins using the dashboard tool? 

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Please refer [user-group post](https://groups.google.com/d/msg/qaf-users/LrhxWAnr1Ts/g-wG8rhOAAAJ).
