### ISSUE TITLE
How to instantiate ios driver to use its methods in Qmetry framework

### ISSUE THREAD

**Issue by myProwess** [qmetry/qaf#167]
Hi folks,

I am currently using the command `**QAFExtendedWebdriver mydriver = getQAFDriver();**`
It will stores current driver in "mydriver" object so i can call its available methods.

Now i need to create a new driver object in the same current session itself to access IOSDriver specific methods.
`IOSDriver<WebElement> driver= new IOSDriver<WebElement> (url, capabilities);`

How to get current session **url,** **capabilities** to pass as parameters... 

I googled a lot. But its not working out for me. Any inputs will help me a lot

**Comment by cjayswal** [comment]
Please refer community answer: [how-to-instantiate-iosdriver-to-access-its-methods-in-the-current-session](https://stackoverflow.com/questions/48342030/how-to-instantiate-iosdriver-to-access-its-methods-in-the-current-session/48432012#48432012) 

Make sure you have provided driverClass [capability](https://qmetry.github.io/qaf/latest/setting_driver_capabilities.html) having value fully qualified name of driver class. For example

**properties**:
```properties
driver.name=appiumDriver
appium.driverClass=io.appium.java_client.ios.IOSDriver
```

You can get driver class object anytime  by casting underlying driver. For example
Code:
```java
IOSDriver<WebElement> iosdriver = (IOSDriver<WebElement>)getDriver().getUnderLayingDriver();
```
**NOTE**: `driverClass` capability will not applicable with remote driver, so if you provide driver name `appiumRemoteDriver` driver class will not be considered and you will get class cast exception in above statement.
