### ISSUE TITLE
With long bdd scenario name, not able to open captured images on windows

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf#169]
### QAF Version
Any

If the scenario have long scenario name, the captured screenshot file name is also too long created from scenario name. Such file's are not get opened in windows system.

### Steps To Reproduce
    1. create bdd scenario with long scenario name
    2. add check point
    3. set success screenshot true to ensure screenshot will captured for checkpoint

### Expected behavior
should be able to open screen shot

### Actual behavior
not able to open screenshot in windows system even if it is there.

**Comment by nagaraj2709** [comment]
Adding example of Scenario name with lengthier description containing some special characters too.

**Scenario:** 3-Scenario Name with Long Description. Missing Verification message "Filing Date" and should reflect invoice date as "11/11/2014". Order amount should be equivalent to order received and should not exceed credit note, make sure that bill report includes client name and same should reflect in PDF report. Cross verify that balance is reflected in balance sheet in consolidated way
