### ISSUE TITLE
Parallel Execution Setup - IE, Chrome, Mozilla Firefox

### ISSUE THREAD

**Issue by obula** [qmetry/qaf#170]
Hi Team,

Can any one provide parallel execution setup - Step By Step with QAF frame work ? or any referral documentation ?

Thanks,

Regards,
Obula Reddy.

**Comment by cjayswal** [comment]
Refer [creating configuration file](https://qmetry.github.io/qaf/latest/creating_configuration_file.html). Please post your questions in [users group](https://groups.google.com/forum/#!forum/qaf-users) for help.
