### ISSUE TITLE
Support to have encripted password

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf#171]
Few of the following classes uses plain password from properties file:
DatabaseUtils
Web service clients with authentication (basic, NTLM, oAuth ... )

Required a way to support encrypted password instead of plain text.

**Comment by infoneershalin** [comment]
Hi @cjayswal ,
This issue happens when Appium has been installed using Node.
It detects Node installation and starts Appium server if it is not running.

**Comment by cjayswal** [comment]
@infoneershalin, It looks your comment is for different issue #158.
