### ISSUE TITLE
How to parameterise Scenario name?

### ISSUE THREAD

**Issue by genesisthomas** [qmetry/qaf#179]
### Steps To Reproduce
    1. I tried to parameterise my scenario name like below: 
   @WebDDxls
  Scenario Outline: Search Keyword xls Data  "\<searchKey>"
    Given I am on Google Search Page
    When I search for "\<searchKey>"
    Then it should have "\<searchResult>" in search results

    #for csv, txt, xls files specify datafile location
    Examples: {'datafile' : 'src/main/resources/data/testData.xls'}
   
### Expected behavior
searchKey value should be displayed in the Scenario name along with Search Keyword xls Data.
E.g.: Search Keyword xls Data Quantum

### Actual behavior
Scenario name is displayed as: Search Keyword xls Data "\<searchKey>"

### Is the issue reproducible on runner?
Yes
- [x] QAS
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> You can use the below Scenario example in https://github.com/Project-Quantum/Quantum-Starter-Kit/blob/master/src/main/resources/scenarios/webSearch.feature to reproduce the issue 

@WebDDxls
  Scenario Outline: Search Keyword xls Data "\<searchKey>"
    Given I am on Google Search Page
    When I search for "\<searchKey>"
    Then it should have "\<searchResult>" in search results

    #for csv, txt, xls files specify datafile location
    Examples: {'datafile' : 'src/main/resources/data/testData.xls'}

**Comment by cjayswal** [comment]
Parameter in scenario name is not supported by design and also doesn't make sense. You will be able to see data used in report. You can customize report to display name differently as per your need.

**Comment by genesisthomas** [comment]
Okay, I'm closing this issue. I tweaked the report instead.

**Comment by AnbarasuMurugesan** [comment]
Hi THomas/Jayaswal,

    I am using data provider .csv in my feature file. Report shows unique scenario name for all use cases. How to customize report to show based on each entries from csv file? I am new to QAF framework, please help me to crack this.

**Comment by amitbhoraniya** [comment]
Provide `recId` column in your csv file. Refer example csv file from [Documentation](https://qmetry.github.io/qaf/latest/maketest_data_driven.html)

**Comment by AnbarasuMurugesan** [comment]
Hi Amit,

     My concern is about the dashboard report showing the test case name as
scenario name. I want to parameterise scenario names. For example

Scenario: Testing DB "${recId}"
Given login DB with "${username}" "${password}"

testdata.csv
recId,username, password
1,xyx,zyx
2,xxy,zzy

dashboard.html in collapse All
Testing DB 1
Testing DB 2

Is this possible?

Thanks,
Anbarasu M

**Comment by amitbhoraniya** [comment]
Purpose of `recId` column is that only. It displays at scenario level in QAF dashboard.
