### ISSUE TITLE
Question: How do i pass proxy information to Webdrivertestbase inturn to be used in extendedwebelement

### ISSUE THREAD

**Issue by HiroMT** [qmetry/qaf#183]
Hi, This is more of a question than an issue. How do i set proxy information for a remotewebdriver call made? If i need to use WebDriverTestBase how to pass proxy details?

PS. I see an issue which is resolved within 2.1.14-RC1 related to setting proxy.

**Comment by cjayswal** [comment]
Will you please post questions in users group?

**Comment by HiroMT** [comment]
Will do. Closing this issue
