### ISSUE TITLE
Need to have support of file path using datafile for xml dataprovider like csv or json.

### ISSUE THREAD

**Issue by Theneskumar** [qmetry/qaf#185]
Need to have similar feature like json data provider xml also enhance with file path  to be input.

Currenly QAF supports to specify xml test data using `key` parameter in `@QAFDataProvider` annotation but not supporting to specify file using `datafile`.  Need to have feature to load the file specified in `datafile` for XML data in `@QAFdataprovider`.

**Comment by cjayswal** [comment]
XML data driven test is supported through key. As result you need not to specify xml file using datafile. But you need to make sure that xml file is under configured resources using `env.resources`. With this feature we will allow user to specify xml file as well. The disadvantage of this approach is, it will not take advantage of resource configuration.

**Comment by kishanbhoraniya** [comment]
@BChitrakannan, you can use custom data provider and can implement your logic. [Example](https://github.com/qmetry/qaf/issues/82)

**Comment by BChitrakannan** [comment]
@kishanbhoraniya  Thank you it worked :) 

Also, Can you please tell me how I can write the scenario as an Excel file? As of now we are using text.bdd. I would like to write the feature in a excel file. Could you please help?

Thanks in advance! 

Kindest Regards,
Chitrakannan

**Comment by amitbhoraniya** [comment]
@BChitrakannan Can you start a different thread for ExcelTestFactory?
