### ISSUE TITLE
Unable to run suite with chromedriver in ubuntu 

### ISSUE THREAD

**Issue by mkpati** [qmetry/qaf#186]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
using following configurations
    1. ChromeDriver 2.36.540471
    2. qaf 2.1.13 
    3. java 1.8

### Expected behavior
I am able to run UI test suites in mac , however not able to run on ubuntu/debian linux systems.

### Actual behavior
Getting the following exception after running mvn test

[UiDriverFactory] - Driver: chromeDriver
Starting ChromeDriver 2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752) on port 12609
Only local connections are allowed.
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for chrome: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-1052-aws x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 96 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'

### Is the issue reproducible on runner?

- [x ] QAS
- [x ] Maven
- [  ] Gradle
- [  ] Ant
- [  ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

[UiDriverFactory] - Driver: chromeDriver
Starting ChromeDriver 2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752) on port 12609
Only local connections are allowed.
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for chrome: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-1052-aws x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 96 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'

**Comment by cjayswal** [comment]
Issue is more related to driver configuration.
As exception reads `Unable to Create Driver Instance for chrome: unknown error: cannot find Chrome binary`, which is from chrome driver! May be it's not finding the chrome binary and you can try by providing chrome binary location using capability as per closed chrome driver [issue #950](https://github.com/angular/protractor/issues/950#issuecomment-55569620).
```
chrome.additional.capabilities={"chromeOptions": {"binary": "D:/Program Files/Chrome/chrome.exe"}}
```
Make sure you have correct value for `webdriver.chrome.driver` and the chromedriver is compatible with the version of chrome.

[qaf users](https://groups.google.com/forum/#!forum/qaf-users) group is right place to post such issues.

**Comment by mkpati** [comment]
Thanks cjayswal, Binary issue has been resolved, however i am getting different issue and posting in [qaf users](https://groups.google.com/forum/#!forum/qaf-users) group. Many thanks , Really appreciate your help here.

**Comment by cjayswal** [comment]
Will you please share resolution and close the issue?

**Comment by mkpati** [comment]
following setting helped me to resolve binary issue:

chrome.additional.capabilities={"chromeOptions":{"binary": "/home/ubuntu/software/chromedriver"}}
