### ISSUE TITLE
dependsOnGroups for BDD and Gherkin need alwaysRun=false

### ISSUE THREAD

**Issue by kulin24** [qmetry/qaf#187]
### QAF Version - 2.1.13
> Note: only the latest version is supported

### Steps To Reproduce
    1. Create two BDD or Gherkin scenarios where the second scenario depends on the first one:

SCENARIO: Second
META-DATA: {"dependsOnGroups":["test1"],"groups":["test2","SMOKE"]}
	Given second scenario step

END

SCENARIO: First
META-DATA: {"groups":["test1","SMOKE"]}
	Given first scenario step

END

    2. Create a testANG configuration file with following configurations:
`<test name="Web Debug Test" enabled="true">
		<groups>
			<run>
				<include name="SMOKE" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
	</test>`
    3. Implement the two steps for the given scenarios with the following step definitions:
````
@QAFTestStep(description="first scenario step")
	public void first_scenario_step() {
		System.out.println("FIrst scenario step");
		Assert.assertFalse(true);
	}
````

```
@QAFTestStep(description="second scenario step")
	public void second_scenario_step() {
		System.out.println("Second scenario step");
		
	}

```

	

### Expected behavior
The second scenario should not be executed when the dependent scenario fails.

### Actual behavior
Both scenarios are executed

### Is the issue reproducible on runner? 

- [x] QAS
- [x] Maven
- [ ] Gradle
- [x] Ant 
- [x] Eclipse

### Test case sample - 
> Code to reproduce shared.

### Description - 
We need the default behavior of testNG to be replicated in BDD and Gherkin scenarios so if any of the dependent scenarios fail, then the subsequent scenarios are not executed. If we can have the provision to provide the 'alwaysRun':false in the Meta-data then that would be great.

**Comment by benzionyunger** [comment]
Can you also provide clear working examples how to implement this in Gherkin in the qmetry documentation. Thanks.

**Comment by kulin24** [comment]
Thanks for helping us with this issue.

I am sorry but, I am afraid that now it will always not run the dependent scenarios in case of failure. I believe what we were looking for a solution that would give us an option as a configuration to change the true or false based on the user needs.

Is that possible to achieve?

**Comment by ksitwala-perfecto** [comment]
The changes made to fix this issue has not fixed the issue. We can still observe that the second scenario is still executed if the first one fails. The dependsOn functionality is working as expected but the execution of the dependent scenarios should not happen if the initial one fails. Ideally, the end user should have the capability to configure alwaysRun as true or false for each scenario based on the need.

**Comment by WendyZ123** [comment]
I faced similar issue as the second scenario is still executed if the first one fails. 
Is there any suggestion for it?
