### ISSUE TITLE
Junit test fails when Integrating qaf

### ISSUE THREAD

**Issue by KamalMoorthy** [qmetry/qaf#188]
### QAF Version 
2.1.13

### Steps To Reproduce
    1.  Integrate qaf with Junit tests and run the sample maven project(weather)
    2. "WeatherFormatterTest.java" class fails when run from command line
    3. When running from IDE all the test are passed. but when running from command line one test fails.

### Expected behavior
All junit test should be passed 

### Actual behavior
**Test fails with below error:
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.208 sec <<< FAILURE! - in TestSuite
testFormat on testFormat(com.bns.ciad.bootcamp.weather.WeatherFormatterTest)(com.bns.ciad.bootcamp.weather.WeatherFormatterTest)  Time elapsed: 0.281 sec  <<< FAILURE!
java.lang.NullPointerException: null
        at org.apache.velocity.runtime.RuntimeInstance.parse(RuntimeInstance.java:735)
        at org.apache.velocity.runtime.RuntimeInstance.parse(RuntimeInstance.java:720)
        at org.apache.velocity.runtime.RuntimeSingleton.parse(RuntimeSingleton.java:251)
        at org.apache.velocity.app.Velocity.evaluate(Velocity.java:282)
        at com.bns.ciad.bootcamp.weather.WeatherFormatter.format(WeatherFormatter.java:21)
        at com.bns.ciad.bootcamp.weather.WeatherFormatterTest.testFormat(WeatherFormatterTest.java:23)**

### Is the issue reproducible on runner? 

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**package com.bns.ciad.bootcamp.weather;
import java.io.InputStream;
import org.apache.commons.io.IOUtils;
import com.bns.ciad.bootcamp.weather.Weather;
import com.bns.ciad.bootcamp.weather.WeatherFormatter;
import com.bns.ciad.bootcamp.weather.YahooParser;
import junit.framework.TestCase;

public class WeatherFormatterTest extends TestCase {

	public WeatherFormatterTest(String name) {
		super(name);
	}
	
	public void testFormat() throws Exception {
		InputStream nyData = 
			getClass().getClassLoader().getResourceAsStream("ny-weather.xml");
		Weather weather = new YahooParser().parse( nyData );
		String formattedResult = new WeatherFormatter().format( weather );
		InputStream expected = 
			getClass().getClassLoader().getResourceAsStream("format-expected.dat");
		assertEquals( IOUtils.toString( expected ), formattedResult );
	}
}**

Thanks,
Kamal

**Comment by cjayswal** [comment]
This looks more specific to project issue. I can see.

```
com.bns.ciad.bootcamp.weather.WeatherFormatter.format(WeatherFormatter.java:21)
```

As you are able to run through IDE, it may have junit dependency related issue.

**Comment by cjayswal** [comment]
You should be able to override dependecy through your project pom. Provide dependency in pom with required version and try.

**Comment by cjayswal** [comment]
For further queries or question post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
