### ISSUE TITLE
Passing cucumber tags in test runner class returning features as null instead of filtered tests based on tags

### ISSUE THREAD

**Issue by nikhilagrawal82** [qmetry/qaf#190]
### QAF Version
2.1.13
> Note: only the latest version is supported

### Steps To Reproduce
    1. I have a TestNG runner class which is having features, glue, tags and plugin key-value pairs under cucumber options 
    2. I have testng.xml file wherein I have mentioned this TestNG runner class and executed it
    3. During execution I observed that features are showing as null i.e. when you pass tag names in TestNg runner class, features shows as null. 
    4. Now I commented the tag names in TestNg runner class and again executed my testng.xml file. This time it executed everything and could see the features showing as scenario names. 

### Expected behavior
 When we pass tag names in TestNG runner class, it should execute only those features having that tag name i.e. features should not be null 

### Actual behavior
Features are showing as null when you pass tag names in TestNG runner class.

### Is the issue reproducible on runner? 
Yes

- [ ] QAS
- [x] **Maven**
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

**P.S.** I tried to execute the TestNG runner class without passing tags which executes all the features i.e. passing tags in TestNG Runner class not working correctly.

**Comment by cjayswal** [comment]
If my understanding is correct, you are using cucumber runner. In that case it is out of scope for qaf as nothing related to qaf. I would suggest to use qaf ghekin factory instead.

**Comment by nikhilagrawal82** [comment]
Hi, 
**My requirement is mentioned as below:**

I want to generate JSON output of the test report which would be imported into test management tool in JIRA (test Management integration).
How can I achieve this using Gherkinfactory?

So, I have created the runner class.
**Here is my code snippet.**

Code Snippet from TestNG.XML file:

**<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Web Demo Suite" verbose="0" thread-count="100">
        <test name="BDD Test" enabled="true">
               <classes>
                      <class name="com.quantum.steps.runTest" />
                     <class name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
        </classes>
    </test>
</suite>**

Code Snippet from runner class (runTest.java): 

**package com.quantum.steps;

import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions( 
                  features = {"src/main/resources/scenarios"},
                  glue = {"com.quantum.steps"},
                  tags = {"@mastercard"},
                  plugin = {"json:target/cucumber.json"}
)

public class runTest extends AbstractTestNGCucumberTests {
}**

I am calling the runner class in testng.xml file addition to Gherkinfactory because of which it ignores the feature and tags that are passed. If I don’t use Gherkinfactory how can I generate the json output that is generated via plugin in cucumberoptions?

Thanks.

Regards,
Nikhil Agrawal

**Comment by cjayswal** [comment]
you should use either qaf gherkin factory or cucumber runner. when you will use cucumber runner as it is not of qaf we can't fix issues with it. On other hand when you are using gherkin factory it will generate qaf json and testNG xml report but not cucumber report. 

In that case you can use qaf gherkin and
1. Check with test management tool support team, if they have support for TestNG xml or qaf json report. For example QTM4J is similar test management tool that supports TestNG, QAF, Junit, Cucumber and other report formats. OR
2. Alternately you can ask them to provide a TestNG report listener to generate report int the format that Test Management tool expect or you can write one own your own.

Keep in mind that what you are using is not TestNG report listener. The reporting listener should work only with TestNG (or qaf) without any of the cucumber dependencies.

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
