### ISSUE TITLE
Help  Needed | Existing Results are getting appended with the new run

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#192]
### QAF Version - 2.1.10
> Note: only the latest version is supported

I have a suite of 10 test cases. When I run for the first time, I am seeing results for 10 test cases. Next, I am trying to run a single test case but all the previous results are getting appended to the new result. So in the dashboard, I am seeing 11 test results.

I cleared the Test Result folder and cleared Meta json file as well. But it is happening again. I didn't make any change in the dashboard.htm file.

Can you please help?

Thanks much in advance.

Update:

When I checked, I am able to see that only one test result is generated for all the runs. I executed the cases 4 times but only one folder is generated with the same time stamp. Is that the issue? :)

I believe the issue is here. 
<test.results.dir>test-results</test.results.dir>
		<run.time>${maven.build.timestamp}</run.time>
		<maven.build.timestamp.format>yyyyMMdd-HHmmss</maven.build.timestamp.format> //I edited the time format. I added it here.		
		<lib.dir>${project.basedir}/lib</lib.dir>
		<resource.dir>${project.basedir}/resources</resource.dir>
		<output.dir>${test.results.dir}/${run.time}</output.dir>
 		<maven.build.timestamp.format>yyyyMMdd-HHmmss</maven.build.timestamp.format> //I edited the time format.

Regards,
CK

**Comment by amitbhoraniya** [comment]
Post your questions in [users group](https://groups.google.com/forum/#!forum/qaf-users).

**Comment by cjayswal** [comment]
Closing with reference of [post in user groups](https://groups.google.com/forum/#!topic/qaf-users/Qdm1suV96Kk).
