### ISSUE TITLE
Not able to run @Test(i.e TestNG method) when QAF is present 

### ISSUE THREAD

**Issue by SwapnilMore123** [qmetry/qaf#193]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by amitbhoraniya** [comment]
Can you provide more details and update issue again? What error are you getting?

**Comment by cjayswal** [comment]
Closing this as it is duplicate with [stackoverflow question](https://stackoverflow.com/questions/50603716/qmetry-com-qmetry-qaf-automation-step-client-scenariofactory-gettestsfromfile). Provide details with your question in stackoverflow for anybody to reproduce and/or help.
