### ISSUE TITLE
Threading issue in initialising the driver

### ISSUE THREAD

**Issue by kulin24** [qmetry/qaf#200]
### QAF Version - 
Latest version

### Steps To Reproduce
I have attached the code of the starter kit project where this issue is reproduced in testng_appium.xml file.
    1. Configure the cloud credentials in application.properties file.
    2. Run the testng_appium.xml file to execute the scenario which recreates this problem.
    3. Check the results for three parallel drivers (two android and one ios)
    **Description:**
We have a simple scenario where we are trying to check the class of the underlying driver. The testNG config file contains two Android and one IOS test configurations.

   **Problem:**
Either all the three drivers are initialized with AndroidDriver constructor or all of them are initialized with IOSDriver constructor. Therefore, resulting in ClassCastException in our execution.

 **Observation:**
This issue is easily reproduced when we are using deviceName or udid as the main device selection capability. Moreover, the driver capabilities after initializing the driver show that the driverClass capability is correct for all three drivers.
On further debugging within QAF, I found that the issue is with this variable in UIDriverFactory.java - `private Class<? extends WebDriver> driverCls = null;`
After I kept some console output statements, I can see that this variable is not behaving in thread-safe manner and it is getting overridden by different driver threads. 

This results in incorrect Driver constructor being used at the time of initialization of the driver. 

**Solution tried:**
By making the main driver creation method in UIDriverFactory synchronized, I was able to remove this issue and the drivers are getting created properly. 
This will cause some delay in driver creation for parallel execution but it ensures that the drivers are getting created properly.

### Expected behavior
The individual drivers for IOS and Android platforms should be IOSDriver or AndroidDriver class.

### Actual behavior
All the drivers are having the same driver class when they are getting initialized.

### Is the issue reproducible on runner?
We are able to reproduce this issue and we also were able to debug this issue and found the root cause. Attached the code to reproduce this issue.

If we make the below method synchronized then it is solving this issue. We are fine with any solution that you see fit here to resolve this issue.

I was able to debug it in this method by adding some console statements:

```
private QAFExtendedWebDriver getDriver(WebDriverCommandLogger reporter, String urlstr) {
			System.out.println("Driver creation method 1 ");
			DesiredCapabilities desiredCapabilities = getDesiredCapabilities();

			Collection<QAFWebDriverCommandListener> listners = getDriverListeners();
			beforeInitialize(desiredCapabilities, listners);
			try {
				if (this.name().equalsIgnoreCase("chrome")) {
					return new QAFExtendedWebDriver(ChromeDriverHelper.getService().getUrl(), desiredCapabilities,
							reporter);
				}
				System.out.println("Driver CLS before initializing driver - " + String.valueOf(driverCls));
				WebDriver driver = getDriverObj(driverCls, desiredCapabilities, urlstr);// driverCls.newInstance();
				return new QAFExtendedWebDriver(driver, reporter);
			} catch (Throwable e) {
				onInitializationFailure(desiredCapabilities, e, listners);

				throw new AutomationError("Unable to Create Driver Instance for " + browserName + ": " + e.getMessage(),
						e);
			}
		}
```

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
[quantum-starter.zip](https://github.com/qmetry/qaf/files/2143891/quantum-starter.zip)

**Comment by amitbhoraniya** [comment]
Can you please update
```
resources.load.subdirs=0
```
And let me know are you still facing same error ?

**Comment by kulin24** [comment]
Thanks for your reply.

I tried with this update but I am still facing the same error.

**Comment by kulin24** [comment]
I am closing this issue as creating the driver in synchronized manner is resolving the issue for me.
