### ISSUE TITLE
Need to pass json object from xls or kwd file as input to QAFTestStep

### ISSUE THREAD

**Issue by SwapnilMore123** [qmetry/qaf#202]
### QAF Version
Need to know whether we can pass json object in following way i.e without curly braces at start.
> Note: only the latest version is supported
"name": [
{
"first": "sample",
"last": 356,
"startDate": "1530211075000",
"endDate": "1530383875000",
"phoneNumber": "1263899027"
}
]
}

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Will you please post in [users group](https://groups.google.com/forum/#!forum/qaf-users) with details what exactly you are trying to do? While posing in users group provide as much as possible details including what you have tried and where you are facing issue.

**Comment by cjayswal** [comment]
For further queries or question post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
