### ISSUE TITLE
sendkeys command uses encrypted password instead of decrypted version

### ISSUE THREAD

**Issue by dsiino** [qmetry/qaf#203]
### QAF Version
2.1.13

### Steps To Reproduce
    1. Configure a field with type:password metadata
    2. Encrypt password in Base64 and store in property file
    3. Write a test to do a login

### Expected behavior
    1.The password is decrypted before the sendkeys command gets executed.
    2.Execution logs show encrypted password.

### Actual behavior
Execution log shows encrypted password but sendkeys also sent encrypted password instead of decrypted version.

### Is the issue reproducible on runner?

- [ ] QAS
- [x ] Maven
- [ ] Gradle
- [x] Ant
- [x ] Eclipse

### Test case sample
// In property file : app.properties
input.login.user.name={"locator":"xpath=//input[@id='inputUserName']","desc":"Name Input field"'}
input.login.user.pwd={"locator":"xpath=//input[@id='inputUserPassword']","desc":"Password Input field", "type":'password'}
encrypted.user.pwd=&lt;encrypted val>

	// In Java step definition : 
	@QAFTestStep(description = "login with valid credentials")
	public void login()  {
		String userName= getBundle().getString("user.name");
		CommonStep.sendKeys(userName,"input.login.user.name");
		
		String encryptedPwd = getBundle().getString("encrypted.user.pwd");
		CommonStep.sendKeys(encryptedPwd,"input.login.user.pwd");  // *** this sends encrypted pwd
       } 

### Note : 
While debugging, we can see that the **ElementMetaDataListener** correctly calls executeWithoutLog(element, commandTracker) with the decrypted value.  However, **executeWithoutLog** does *nothing* since the commandTracker response is null. 

	if (null != commandTracker.getResponce())  {
		commandTracker.setResponce(element.execute(commandTracker.getCommand(), commandTracker.getParameters()));
	}

How can the commandTracker  have a response since it has not yet executed???

Thanks

Daniel

**Comment by cjayswal** [comment]
I am also able to reproduce. It looks something broken!... or i am doing something wrong.

While it get resolved (found what's wrong), you can use decrypted value key in code. With each encrypted value there will be decrypted value available in the code. For example for prorperty `encrypted.user.pwd` property with decrypted value `user.pwd` will be available that you should use in code. In your case you can use as below.
``` properties
 encrypted.user.pwd=Q2hpcmFnMTIzIw==
```
```java
String encryptedPwd = getBundle().getString("user.pwd"); //this is corresponding decrypted value
CommonStep.sendKeys(encryptedPwd,"input.login.user.pwd"); 
```
