### ISSUE TITLE
Need to reopen this issue as multi device scripts tear down is broken in 2.1.13

### ISSUE THREAD

**Issue by kulin24** [qmetry/qaf#204]
https://github.com/qmetry/qaf/issues/131

This commit has broken the driver teardown when we are using multiple devices in a single scenario.
Project-Quantum/Quantum#49

The driver teardown was working fine in the 2.1.12 version. It is failing as the following line of code is returning null:
if(getBaseUrl().equalsIgnoreCase(driverName)){

On analyzing this issue I found that the BaseURL and the other two parameters in stb are set to Null when we use setDriver(String driverName) method to switch drivers.

This is causing the NullPointer on driver quitting.

**Comment by cjayswal** [comment]
Thanks, Reopened #131. Please utilize [users group](https://groups.google.com/forum/#!forum/qaf-users).
