### ISSUE TITLE
Help Needed: Passing Json node as input in the Excel

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#206]
Hi Amit,

I have this scenario. I need to pass JSONArray or JsonObject as an input. I am using ExcelTestFactory.

Below is my sample input:

["nodename",["a","b","c"]]

I want the whole word to be read. QAF is not able to read everything as a whole as I have comma in it.

Can you please tell me how I can address this :)

Thanks much in advance for the help.

Also, I cannot store these values in an external file as the input is coming from external team.

Kindest Regards,
CK

**Comment by cjayswal** [comment]
For further queries or question post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
