### ISSUE TITLE
How to consolidate step definitions by capturing optional groups

### ISSUE THREAD

**Issue by dsiino** [qmetry/qaf#207]
### QAF Version
2.1.14-RC1

### Steps To Reproduce
    1. Write a step that includes optional text
        1a. For example : And a valid account is not present
    2. Write a step definition that include a regex for the optional text
        2a. For example :@QAFTestStep(description = "a valid account is( not)? present")
            public void accountPresent(String... negate) { doStuff(); }
    3. Run test

### Expected behavior
Step is called. When the word "not" is present the parameter negate is an array with one String.
When the word "not" is not included in step, the parameter negate is an empty array []
This way, there is no need to implement 2 steps definition.

### Actual behavior
java.lang.RuntimeException: 
Wrong number of parameters, Expected 1 parameters but Actual is 0

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ x] Eclipse

This is supported by Cucumber-Ruby : 
*  _Then /^I should( not)? see the following columns: "([^"]*)"$/ do |negate, columns|_
*  See http://coryschires.com/ten-tips-for-writing-better-cucumber-steps/

Is this supported by QAF? 
If so, what is the correct way to write the step definition?  (combination of parenthesis vs. curly braces???)

**Comment by cjayswal** [comment]
Unlike cucumber, qaf is not using regular expression for argument place holder. So from your step description `a valid account is( not)? present`, **`( not)?`** will not be considered as argument. Regardless of supported or not certainly the approach is not preferable, because it will required unnecessary condition (if else) in step implementation. Below is the example how should the such step look like:

```java
@QAFTestStep(description = "{expValidAccouts} valid account( is|s are) present")
public void accountPresent(int expValidAccouts) {
	int actualValidAccounts = getValidAccounts().size();
	Validator.verifyThat(actualValidAccounts, Matchers.equalTo(expValidAccouts));
}

```
Step call will be:

```
0 valid account is present
1 valid account is present
2 valid accounts are present
```
To make it more readable your description can be
```java
@QAFTestStep(description = "should have {expValidAccouts} valid account(s)?")
```
In this case step call will be:
```
should have 0 valid account
should have 1 valid account
should have 2 valid accounts
```

**Comment by dsiino** [comment]
Once again, thanks for the quick response.
Your suggestion makes sense and is well aligned with the Cucumber approach.  
However, in some situation, I might want to validate the presence of items in a list without knowing the exact number. That is why I was thinking of a step with empty/not empty in mind.

Regards,

Daniel
