### ISSUE TITLE
Help Needed | Accessing BeforeSuiteMethod from QAF

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#210]
I need to connect to the database to populate the data before I start my execution. So I would like to add these steps in the beforeSuite method.

Could you please tell me how to do that?

Thanks much in advance.! 

Regards,
Chitrakannan

**Comment by cjayswal** [comment]
For further queries or question post in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf)
