### ISSUE TITLE
get  NotYetImplementedException() when I use meta-data label

### ISSUE THREAD

**Issue by MoonLikeSinging** [qmetry/qaf#214]
### QAF Version: 2.1.13
> Note: only the latest version is supported

### Steps To Reproduce
 @TestForTest
SCENARIO: Custom Data provider Example
Given I am on fruits and colors activity
When i select 'fruit'
Then the color should be 'color'

###This scenario above is correct.
###Then I use scenario below, get the NotYetImplementedException().

@TestForTest
SCENARIO: Custom Data provider Example
META-DATA: {"dataProvider":"my-custom-dp", "dataProviderClass":"com.qmetry.qaf.example.CustomDataProvider","description":"Data driven test that uses custom data provider"}
Given I am on fruits and colors activity
When i select '${fruit}'
Then the color should be '${color}'

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

@QAFTestStepProvider
public class TestDataProdivider {
    @QAFTestStep(description = "I am on fruits and colors activity")
    public void test()
    {
        System.out.println("I am on fruits and colors activity");
    }

    @QAFTestStep(description = "i select {fruit}")
    public void testfruit(String fruit)
    {
        System.out.println(fruit);
    }

    @QAFTestStep(description = "the color should be {color}")
    public void testcolor(String color)
    {
        System.out.println(color);
    }
}

###DataProdiverClass:
public class CustomDataProdvider {

    @DataProvider(name="my-custom-dp")
    public static Object[][] dataProviderForBDD(){

        Map<Object, Object> rec1 = Maps.newHashMap();
        rec1.put("fruit", "grapes");
        rec1.put("color", "green");

        Map<Object, Object> rec2 = Maps.newHashMap();
        rec2.put("fruit", "banana");
        rec2.put("color", "yellow");

        return new Object[][]{ {rec1},{rec2}};
    }
}

**Comment by MoonLikeSinging** [comment]
![configxml](https://user-images.githubusercontent.com/28696706/45074894-c444af80-b117-11e8-9c5f-f4f025bb19f7.PNG)

**Comment by cjayswal** [comment]
Please refer [stack-overflow post](https://stackoverflow.com/questions/52177179/meta-data-label-in-feature-file-cant-be-resolve-in-qaf-2-1-13/52192990#52192990)
