### ISSUE TITLE
Help Needed | Need to use multiple dataProviders

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#216]
Hi Team,

In my project i have to use two data providers. 

I want to achieve the below execution flow:

1. Test1
2. Test 2

 (or)

In a same test, i want to call these 2 methods which consume different data providers.

Please find my code below. 

@QAFDataProvider(dataFile = "resources/data/TestData.xls", sheetName="Req", key="data")
	@Test(description = "Trasanction Test")
	public void makePackReq(Map <String, String> data)
{

//I need to call makePackReq() from this method with different data but that is also using a dataprovider.
}

@QAFDataProvider(dataFile = "resources/data/TestData.xls", sheetName="Res", key="data")
	@Test(description = "Trasanction Test")
	public void makePackRes(Map <String, String> data)
{
//logic
}

Is there any way I can use 2 data providers to the first method?

**Comment by BChitrakannan** [comment]
Also, if there is any way to get the dataProvider function inside the method, that will be great.

Thanks much in advance

**Comment by amitbhoraniya** [comment]
@BChitrakannan,

Simply it can be done by creating one method, call the same method in both the testcase.

```java

public void makePackTest(Map <String, String> data){
   // your logic
}

@QAFDataProvider(dataFile = "resources/data/TestData.xls", sheetName="Req", key="data")
@test(description = "Trasanction Test")
public void makePackReq(Map <String, String> data)
{
    makePackTest(data);
}

@QAFDataProvider(dataFile = "resources/data/TestData.xls", sheetName="Res", key="data")
@test(description = "Trasanction Test")
public void makePackRes(Map <String, String> data)
{
    makePackTest(data);
}
```

**Comment by cjayswal** [comment]
For further queries or question post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
