### ISSUE TITLE
Using dynamic Test name

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#218]
In my suite, I have used QAFDataProviders. 

The same test case is being executed with 100s of data. But in the report, just the same method name is generated.

Do we have any option to change the test case name which is displayed in the report?

Note: I am not using BDD. I am using @Test. 

Any help will be appreciated. Thanks much! 

![capture](https://user-images.githubusercontent.com/37250404/45949216-ce701480-c018-11e8-875d-caf0cd0c7a97.PNG)

PLease find the screenshot of the current report. 

Kindest Regards,
Chitrakannan

**Comment by BChitrakannan** [comment]
Thank you very much Amit :)

**Comment by ramadossgit** [comment]
Did you get the recId in each test cases header in report?
