### ISSUE TITLE
Is there any way to get only selected rows from data provider excel to BDD

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#221]
### QAF Version
2.1.13

### Steps To Reproduce
    1. In BDD meta data, define the "dataFile" and "sheetName" and get the data in steps as '${dataName}'
    2. In Excel sheet, I have data for many test cases like for 1st test case 2 rows (needs to be executed 2 times), and for 2nd test case 3 rows

### Expected behavior
Single excel sheet to be used for running multiple scenarios at multiple times

### Actual behavior
All the rows are taken for all test cases.

### Is the issue reproducible on runner? Yes

- [x] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample

Scenario:
SCENARIO: Create Notification in FSE Portal
META-DATA: {"description":"Create Notification in FSE Portal","Groups":["Z3_Notification"], "TestCaseId":"TC_001", "dataFile":"${TestDataFile}", "sheetName":"${TestDataSheet}"}

Excel Sheet

TestCaseId | Test Case Name | UserName | Password | Description
-- | -- | -- | -- | --
TC_001 | Create Z3   Notification in FSE Portal |   |   | Z3 Notification - 1
TC_001 | Create Z3   Notification in FSE Portal |   |   | Z3 Notification - 2
TC_002 | Create Z4   Notification in FSE Portal |   |   | Z3 Notification - 2
TC_002 | Create Z4   Notification in FSE Portal |   |   | Z3 Notification - 2
TC_002 | Create Z4   Notification in FSE Portal |   |   | Z3 Notification - 2

**Comment by cjayswal** [comment]
Refer [excel-data-provider](https://qmetry.github.io/qaf/latest/maketest_data_driven.html#excel-data-provider).

**Comment by Priya335021** [comment]
Thanks @cjayswal . 

Referred the documentation and added another meta-data "key":"TC_001" to my BDD. But I am getting below error. Can you please help me to resolve this.

Lable TC_001 for ending data range not found in sheet Sheet1

Excel:

TC_001 | Test Case Name | UserName | encrypted.Password | Description | Priority | Field_Resposible | Equipment
-- | -- | -- | -- | -- | -- | -- | --
  | Create Z3   Notification in FSE Portal | XXXXXX | XXXXX | XXXXXXX | X | XXXXX | XXXX

**Comment by Priya335021** [comment]
Thanks much @amitbhoraniya . It is working !!

**Comment by Priya335021** [comment]
Closing the issue since it is working fine.
