### ISSUE TITLE
Help Needed : How to parameterize the file name in QAFTestDataProvider

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#222]
Hi Team,

I have a requirement to parameterize the csv file name in the QAFTestDataProvider. But it needs to be a constant. I tried using a String variable. But i was not able to do that.

@QAFDataProvider(dataFile = {File will be selected during run time})

Could you please let me know if there is any way to do this?

Best Regards,
CK

**Comment by cjayswal** [comment]
Please refer [documentation](https://qmetry.github.io/qaf/latest/maketest_data_driven.html#configureoverride-dataprovider), you can find information on how to override data provider.

**Comment by BChitrakannan** [comment]
Hi @cjayswal ,

Thank you very much :) That was my bad. I should have checked the documentation :) 

Appreciate you taking your time to answer :)

Kindest regards,
CK
