### ISSUE TITLE
Not able to launch IE and FF with QMetry Framework using Selenium Grid

### ISSUE THREAD

**Issue by ashs1432** [qmetry/qaf#223]
Hi Team ,

I would request to help me with Grid implementation for IE and FF using Qmetry frame work. The same for Chrome is successfully implemented and working as expected.

QAF Version - 2.1.13
Selenium Version - 2.53.0

For IE , below the properties set in env.properties file
remote.server="IP "
remote.port=5555
driver.name=iExplorerRemoteDriver
iExplorer.additional.capabilities={"ignoreProtectedModeSettings":true, "ignoreZoomSetting":true}

Error -

Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)

12:02:15.072 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
Started InternetExplorerDriver server (64-bit)
2.53.0.0
Listening on port 19712
Only local connections are allowed
12:02:25.715 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "internet explorer",
  "cssSelectorsEnabled": true,
  "ensureCleanSession": true,
  "javascriptEnabled": true,
  "platform": "WINDOWS",
  "takesScreenshot": true,
  "version": ""
}

For FF , below the properties set in env.properties file
remote.server="IP "
remote.port=5555
driver.name=firefoxRemoteDriver

[UiDriverFactory] - Driver: firefoxRemoteDriver
Unable to create driver instance in 12th attempt with retry timeout of 180 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

12:06:13.059 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1539153373121   geckodriver     INFO    geckodriver 0.20.1 (685f18325cea0a282c736e65972f95aa6db7ca48 2018-04-03)
1539153373121   geckodriver     INFO    Listening on 127.0.0.1:40468
12:06:23.715 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "cssSelectorsEnabled": true,
  "javascriptEnabled": true,
  "takesScreenshot": true,
  "version": ""
}

Appreciate if some one can help me in identifying and fixing these issues.

Thanks,
Asish B

**Comment by cjayswal** [comment]
Which version of grid you are using? You should check grid log to get idea what's going wrong. It looks grid is not able to create driver session. There are many reasons of that. One of the possibles reason is older version of grid or driver executable.  

- Try using latest version of grid. 
- Make sure you have provided driver executable path through system property while starting grid. 
- Make sure that driver executable version are compatible with browser version.

Below are list of properties to used to set different driver executable:  

```
webdriver.chrome.driver=<chrome-driver-executable-path>
webdriver.gecko.driver=<gecko-driver-executable-path>
webdriver.ie.driver=<ie-driver-executable-path>
webdriver.edge.driver=<edge-driver-executable-path>
```
Above properties are expected to set as system property so either you can set environment variable  or pass as system property while starting grid. Here is example how you can set system property when starting grid

```
java -Dwebdriver.ie.driver=c:/downloads/iedriverserver.exe -Dwebdriver.gecko.driver=c:/downloads/geckodriver.exe -jar selenium-server-standalone-3.14.0.jar -role hub
```

**Comment by ashs1432** [comment]
Hi Chirag ,

By upgrading to Selenium 3.5.3 and updating the gecko driver , I can able to launch firefox as well and execute . But I still facing the issue with IE with the same above mentioned error.

Can you please let me know is there any way to over come that issue or I can any extra parameters to ignore protected settings?

Note - I can able to successfully launch IE driver in my own machine and same is not happening when I am trying to launch in different machine using grid.

Thanks,
Asish B

**Comment by cjayswal** [comment]
Make sure that you have followed [required-configuration](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration) in the system where grid is running.

To set capabilities refer post in [users group](https://groups.google.com/d/msg/qaf-users/itoSC8hMWWA/3x-MzQlDAQAJ). You can have capabilities something like below:
```
driver.name=iexplorerRemoteDriver
iexplorer.additional.capabilities={'ignoreProtectedModeSettings':true,'ignoreZoomSetting':true}

```

**Comment by cjayswal** [comment]
For further queries or question post in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf)

**Comment by nakulkhargonkar** [comment]
Below setting worked for me
iexplorer.additional.capabilities={'ignoreProtectedModeSettings':true,'nativeEvents':false,'unexpectedAlertBehaviour':accept,'enablePersistentHover':true,'ignoreZoomSetting':true,'requireWindowFocus':true}

IE v 11.1087
Selenium v 3.141.59
QAF v 2.1.14
Win 10 64bit
