### ISSUE TITLE
Rest Client Factory creates request logger with hard-coded System.out printstream

### ISSUE THREAD

**Issue by dsiino** [qmetry/qaf#226]
### QAF Version
2.1.14-RC1

### Steps To Reproduce
    1. Create bdd scenario 
    2. Run test
    3. View logs

### Expected behavior
Logs can be turned off so they don't show request and response traffic. Response can be quite large... 

### Actual behavior
Logs always show request and response (in/bound data exchange)

### Is the issue reproducible on runner?

- [x] Maven
- [x] Eclipse
- [x] TestNG

### Test case sample
In file test.bdd : 
SCENARIO: scenario name
META-DATA: {"description":"description"}

   When user requests '${get.sample.call}'

### Description

I could not find a way to quiet the logger as it it always outputting client request/response.
Adding _log4j.logger.com.qmetry.qaf.automation.ws.rest.RequestLogger=ERROR_ in log4j.properties doesn't help since the logger is hard-coded with a System.out printstream ( RestClientFactory line 60).
`requestLogger = new RequestLogger(System.out);`

I've create a custom RestClient that extends DefaultRestClient but could not override the `getClient()` method as it is declared **final**. 

I don't understand the code in `getClient()` :  it adds a ConnectionListenerFilter with a RequestListener and also adds the same instance of the RequestLogger as a second filter (redundant???).

RestClientFactory lines 48-49 : 
```java
client.addFilter(new ConnectionListenerFilter(getRequestListener()));
// Next line will add the same instance of the RequestLogger still pointing to System.out
client.addFilter(getRequestListener()); 
```

Any suggestion on how to turn off the verbose logging?

Thanks

Daniel

**Comment by cjayswal** [comment]
You can disable that by registering void out stream through before method invocation listener.
For example:
`getTestBase().getContext().setProperty(REST_REQ_LOGGER_KEY, ByteStreams.nullOutputStream())`

**Comment by cjayswal** [comment]
You are right, refer updated example.
