### ISSUE TITLE
DataProvider | Considering the empty cell as non empty

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#228]
Hi Team,

I am using QAFTestDataProvider. It reads the value from xls. 

In the Excel sheet, I have added a dropdown(Multi-select) in the 13th column. I have only one test case where i have selected the options in the 13th column. In the remaining rows, I have neither added any test data nor selected any value in the 13th column. But QAF considers this as non-empty and running the test cases with Null value. 

Is this an issue?

Thanks,
Chitrakannan

**Comment by cjayswal** [comment]
That is expected.

**Comment by cjayswal** [comment]
For further queries or question post in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf)
