### ISSUE TITLE
Database data provider not working if query contains "="

### ISSUE THREAD

**Issue by Rajdi** [qmetry/qaf#229]
![image](https://user-images.githubusercontent.com/11414599/47816027-520fd600-dd28-11e8-8192-0b828baa2d08.png)
Actual sql was SELECT * FROM some_table_name WHERE column_name ='xyz'
Observation : The method getDataFromDB is ignoring the query after '=' equal to relational operator. And it fails to execute the SQL.

_Originally posted by @Rajdi in https://github.com/qmetry/qaf/issues/225#issuecomment-434837427_

**Comment by Rajdi** [comment]
Thank you for Chirag, for creating a new ticket . Since, it was labelled as a bug, I was wondering and wanted to check how long would it take to address or provide a fix for this issue. I don't mean to rush, but wanted to check if there is any workaround until the fix. Thanks much and I appreciate your help.

**Comment by cjayswal** [comment]
@Rajdi, Is it blocker for your project? If so i can provide deploy snapshot. Otherwise it will be available with next release or release candidate.

**Comment by cjayswal** [comment]
You can try with [SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/qmetry/qaf/2.1.14-SNAPSHOT/).

**Comment by Rajdi** [comment]
Sorry, The snapshot did not work . when I added this dependency, it was showing import errors all over in project on all @test annotations and other areas , I even tried to add TestNG library to the build path, it did not work. Please let me know , if  you need me to try something else. Thank you!

**Comment by cjayswal** [comment]
Maybe you haven't added snapshot as dependency.

**Comment by Rajdi** [comment]
Here are few details, I still couldn't get that working.

**Comment by cjayswal** [comment]
You may refer [to setup snapshot version from maven snapshot repository](https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository). Or alternately in addition to jar you need to copy pom as well.

**Comment by Rajdi** [comment]
Its working. Thank you very much!

**Comment by cjayswal** [comment]
Thanks for confirmation. Release candidate 2.1.14-RC2 is now available on maven central.
