### ISSUE TITLE
Is it possible to run only selected test cases using Excel Data Provider?

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#232]
Hi Team, 

I am using QAFDataProvider to read the inputs from an Excel sheet. The data provider works fine when I have no data validation in the excel sheet. But when I have a Data validation (I have drop down in 3 columns which is applicable to all the rows), it ignores the key("data" to mark the end of the test case as mentioned  [here.](https://qmetry.github.io/qaf/latest/maketest_data_driven.html#excel-data-provider)  

It considers all the rows as test even though i have selected value in only one row. Is there any other way to run only selected test cases? 

This will help me a lot. Thanks much in advance. 

This is how i am calling my DataProvider:

@QAFDataProvider(dataFile="transaction.testdata.datafile", key="data")
@Test(description = "TestName")
public void test(Map <String, String> data) throws IOException
{
}

Application.properties
test.transaction.datafile =./resources/data/test.xls;

Excel sheet:
[test.xlsx](https://github.com/qmetry/qaf/files/2638858/test.xlsx)

Best,
CK

**Comment by BChitrakannan** [comment]
Hi Team,

Can you please help me with this?

Best,
CK

**Comment by cjayswal** [comment]
Excel data provider excepts .xls file. Try with .xls file instead of xlsx.

**Comment by cjayswal** [comment]
For further queries or question post in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf)
