### ISSUE TITLE
Run single test with mutilple examples tags using TestNG XML file 

### ISSUE THREAD

**Issue by KonaMohan** [qmetry/qaf#239]
Hi Team,

I just want to know if there’s a way to run a scenario with different Example sections in the Quantum framework. I created the following example scenario to demonstrate. Is there a way only using the @Canada tag to trigger the Canada site using **TestNG XML file**. It is working fine using a JUnit runner file.

**@Outline**
**Scenario Outline:**  Demo Test
    **Given** That the test name is demo test
    **Given** I navigate to `site`
    **And** If a cookie is present I accept
    **Then** I check complete window `tag`

    @Canada
    Examples:   
   |site                             |tag      |
   |http://www.demo.ca/ | home |
   
   @US
   Examples:
   |site                                |tag      |
   |http://www.demo.com/ | home |

Thanks,
Mohan Kona.

**Comment by cjayswal** [comment]
@KonaMohan BDDTestFactory2 will support multiple examples with groups(tags). It is coming soon, Refer [unit tests](https://github.com/qmetry/qaf/blob/86ff342569718405ce181778f26155ecf9614a49/test/resources/scenarios2/scenario_examples_withtag.feature)

Still external test data recommended over Examples with or without groups.

**Comment by KonaMohan** [comment]
@cjayswal  Thankyou so much for this info. Please do update me when BDDTestFactory2 comes.:)

**Comment by cjayswal** [comment]
@KonaMohan, QAF-2.1.14 released. You can refer [bdd-syntax](https://qmetry.github.io/qaf/latest/bdd-syntax.html) and [release notes](https://qmetry.github.io/qaf/latest/release_notes.html#ver-2114-release-notes).

**Comment by cjayswal** [comment]
Closing issue as per comments above.
