### ISSUE TITLE
appiumDriver - Unable to create driver instance in real device

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#240]
### QAF Version: 2.1.13
> Note: only the latest version is supported

### Steps To Reproduce
    1. After setting up the all desired capabilities, while running the testNG xml file, it is showing below issue. There are no other stack trace available in console too.
    
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for appium: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'indch221652', ip: '10.81.250.63', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown

### Expected behavior
Driver should intialize

### Actual behavior
Driver intialization failure

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
Appium capabilities were set like below.

remote.server=127.0.0.1
remote.port=4723
driver.name=appiumDriver
appium.additional.capabilities= {'app':'path/xxx.apk','deviceName':'xxxxxxxxxxx','platformName':'Android','platformVersion':'8.1.0','automationName':'Appium','driverClass':'io.appium.java_client.android.AndroidDriver','appPackage':'appPackage','appActivity':'appActivity','newCommandTimeout':'8000','driver.class':'io.appium.java_client.android.AndroidDriver'}
selenium.singletone=methods

It opens the application and but the test case is skipped with error "Unable to create driver instance in 1st attempt"

Getting below error in appium server
"UiAutomator exited unexpectedly with code 4294967183, signal null"

**Comment by cjayswal** [comment]
It looks issue with appium. Make sure you are able to inspect elements in Appium Desktop.

**Comment by Priya335021** [comment]
Yes, able to inspect elements in Appium desktop. But unable to execute with appiumDriver. Please provide some suggestions to resolve the issue.

**Comment by cjayswal** [comment]
@Priya335021 will you please try with qaf latest (2.1.14) version and latest appium client version?

**Comment by cjayswal** [comment]
closing as inactive.
