### ISSUE TITLE
Issue with Time Duration at Test Level

### ISSUE THREAD

**Issue by amitbhoraniya** [qmetry/qaf#243]
Currently in QAF Report, Test Overview is showing a wrong time duration. It is not considering a time of first testcase.

![test_overview](https://user-images.githubusercontent.com/4617600/51015353-e2249400-1591-11e9-941f-51465c112adb.png)
![screen shot 2019-01-11 at 11 06 48 am](https://user-images.githubusercontent.com/4617600/51015356-e3ee5780-1591-11e9-860e-672f8ae33e09.png)

Here actual testcase took 11s time, but at test overview it is showing only 1s.

**Comment by cjayswal** [comment]
Will you please share report json files? Also check with latest reporting by updating dashbord.htm dashbord from [qaf-report](https://github.com/qmetry/qaf-report)?
