### ISSUE TITLE
Argument to isShown must be of type Element when  calling waitForNotPresent()

### ISSUE THREAD

**Issue by israelsotos** [qmetry/qaf#245]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
   We have the next code
@QAFTestStep(description = "select {alldata-app} service")
	public void selectApp(String app) {

		CommonStep.waitForNotPresent("page.loader.loc");
		QAFTestBase.pause(3000);
		CommonUtils.waitForAjaxToComplete(3000);
		CommonUtils.waitForLoaderToDismiss();
		LoginStepsWebImple loginSteps = new LoginStepsWebImple();
		loginSteps.closeWalkManPopUp();

		AllDataApp.valueOf(app).getElement().waitForPresent();

		CommonUtils.waitForAjaxToComplete(3000);
		CommonUtils.waitForLoaderToDismiss();

		if (AllDataApp.valueOf(app).getElement().isPresent()
				&& AllDataApp.valueOf(app).getElement().isDisplayed()) {
			AllDataApp.valueOf(app).getElement().click();
			Reporter.log("Clicked on :" + app);
		}
	}

### Expected behavior
It should click on the desired element and open it.

### Actual behavior
It displays the next error and then crashes:
[error.txt](https://github.com/qmetry/qaf/files/2838889/error.txt)

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
@QAFTestStep(description = "select {alldata-app} service")
	public void selectApp(String app) {

		CommonStep.waitForNotPresent("page.loader.loc");
		QAFTestBase.pause(3000);
		CommonUtils.waitForAjaxToComplete(3000);
		CommonUtils.waitForLoaderToDismiss();
		LoginStepsWebImple loginSteps = new LoginStepsWebImple();
		loginSteps.closeWalkManPopUp();

		AllDataApp.valueOf(app).getElement().waitForPresent();

		CommonUtils.waitForAjaxToComplete(3000);
		CommonUtils.waitForLoaderToDismiss();

		if (AllDataApp.valueOf(app).getElement().isPresent()
				&& AllDataApp.valueOf(app).getElement().isDisplayed()) {
			AllDataApp.valueOf(app).getElement().click();
			Reporter.log("Clicked on :" + app);
		}
	}

**Comment by cjayswal** [comment]
Looks like related to https://github.com/appium/appium/issues/11510

**Comment by amitbhoraniya** [comment]
Hi @israelsotos,

Can you please check `driver.name` property.

For appium version 1.9.0+ you might face this issue with `appiumRemoteDriver`. Can you try with `driver.name=appiumDriver` and provide `driverClass` capability.

**Comment by israelsotos** [comment]
We added the driver.name property and  modified the Ivy dependencies as follows:

```
	<dependency org="com.qmetry" name="qaf" rev="2.1.14" force="true"/>
	<dependency org="com.qmetry" name="qaf-support" rev="2.1.14" />
	<dependency org="org.seleniumhq.selenium" name="selenium-java" rev="3.141.59"/>	
	<dependency org="org.seleniumhq.selenium" name="selenium-remote-driver" rev="3.141.59"/>
		
	<!--<dependency org="io.appium" name="java-client" rev="4.0.0"/>-->
	<dependency org="io.appium" name="java-client" rev="6.1.0"/>
	
	<dependency org="org.aspectj" name="aspectjtools" rev="1.9.1" />
	<dependency org="org.aspectj" name="aspectjweaver" rev="1.9.1" />
	<!--
	<dependency org="org.aspectj" name="aspectjtools" rev="1.8.5">
		<artifact name="aspectjtools" type="jar"></artifact>
	</dependency>
	-->
	<dependency org="ant-contrib" name="ant-contrib" rev="1.0b3"/>
	<dependency org="com.paulhammant" name="ngwebdriver" rev="1.1.4" >
	<exclude org="org.testng" />
	</dependency>
	
</dependencies>
```
This fixed the problem
