### ISSUE TITLE
Autocompletion doesn't work in feature files for gherkin

### ISSUE THREAD

**Issue by davidreedme** [qmetry/qaf#246]
I don't see a project for the Eclipse QAF Editors plugins. If there's a better place to drop an issue, please point me at it.

### QAF Version
2.1.4

### QAF Editors Plugin Version
1.0.0.4--cKe8k67E7AUAEEEAI7Y

### Eclipse version
Eclipse Java EE IDE for Web Developers.
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200

### Steps To Reproduce
    1. Clone a new project
    2. Add a feature file
    3. Add a scenario and given
    4. Then... no suggestions of built-in or custom steps

### Expected behavior
    * Syntax completion for built-in or custom steps

### Actual behavior
    * No syntax completion at all. Syntax highlighting/coloration works.

### Is the issue reproducible on runner?
n/a

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
@@Account_Services_Example @#11111 @769900 @meandyou
Scenario: Ensure the functionality of the account services widget
	Given I have a widget and I signed into my account
	Then

**Comment by cjayswal** [comment]
Are you using Ctrl+space to get content assist?

**Comment by davidreedme** [comment]
I verified that ^SPACE (CTRL+SPACE) is bound to content assist in Eclipse, but that combo does nothing inside a feature file when pressed. Neither does CTRL+SHIFT+SPACE for context info.

I don't see a preference for anything QAF to turn it on or off. Removing the plugins, restarting Eclipse, and reinstalling has no effect.

I've been on a Mac full-time for the past year, so I haven't tried this on other platforms recently. I have verified that it's not working for other folks on Mac as well.

**Comment by cjayswal** [comment]
I tried with Eclipse Oxygen.3a Release (4.7.3a) on Mac and it worked for me.
<img width="473" alt="screen shot 2019-02-12 at 10 57 45 am" src="https://user-images.githubusercontent.com/110619/52660845-6d58b880-2eb5-11e9-8adf-c6c5b5f19456.png">

I observed that if i remove feature line it's showing error feature is missing at line 1 and not showing content assist. Make sure editor is not showing any error.

**Comment by davidreedme** [comment]
Alright, very good, Chirag. That seems to be what the problem was. There are some steps further down that were in error. Commenting those out got me working.

There are some of the built-in templates that come out unrecognizable for whatever reason, but I can work with this.

Thank you.
