### ISSUE TITLE
deviceName capability is persistent and not cleared in new test

### ISSUE THREAD

**Issue by rajeshmahalingaswamy** [qmetry/qaf#248]
### QAF Version
> > Note: only the latest version is supported

Verified on 2.1.13 and 2.1.14. Issue is reproducible.

### Steps To Reproduce
1. Set the TestNG suite with parallel=”none” and enable two tests i.e., 1 test with capabilities of Mobile device and 1 test with capabilities of Desktop device

### Expected behavior
In 2nd test, Desktop device to be launched.

### Actual behavior
In the 2nd test, Mobile device is launched instead.

### Is the issue reproducible on runner? Yes

- [] QAS
- [x] Maven
- [] Gradle
- [] Ant
- [x] Eclipse

### Test case sample

> > Please, share the test case (as small as possible) which shows the issue

When we have mobile & desktop tests in a TestNG file running in sequential order from two different <test> tags. Attached a TestNG file with the set-up for reproducing the error. If in first test, a mobile device is launched using ‘deviceName’ capability and the second test which executes sequentially (in different <test> tag) is of Desktop device. Instead of launching desktop browser of selected capability in second test, the previously selected mobile device is re-launched.
[sampleTestNG.txt](https://github.com/qmetry/qaf/files/2937051/sampleTestNG.txt)

**Comment by cjayswal** [comment]
Try using different driver name, for example:
```xml
<test name="Web Scenarios Test" enabled="true"
		thread-count="10">
		<parameter name="driver.name" value="perfectoRemoteDriver" />
		<parameter name="perfecto.capabilities.deviceName" value="DEVICE_ID"/>
		<!-- <parameter name="perfecto.capabilities.platformName" value="iOS"/>
		<parameter name="perfecto.capabilities.model" value="iPhone.*"/>
		<parameter name="perfecto.capabilities.browserName" value="MobileOS"/> -->
		<groups>
			<run>
				<include name="@WebSearch" />
			</run>
		</groups>
		<classes>
			<class
				name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>
	
	<test name="Web Scenarios Chrome Test1" enabled="true">
		<parameter name="driver.name" value="chromeRemoteDriver" />
		<!-- below capabilities for driver you can move into properties as well-->
		<parameter name="chrome.capabilities.platformName" value="Windows" />
		<parameter name="chrome.capabilities.platformVersion"	value="10"/>
		<parameter name="chrome.capabilities.browserName" value="Chrome"/>
		<parameter name="chrome.capabilities.browserVersion" value="70"/>
		<parameter name="chrome.capabilities.resolution" value="1280x1024"/>
		<parameter name="chrome.capabilities.location" value="US East"/>
		<parameter name="chrome.capabilities.deviceType" value="Web"/>
		<parameter name="env.resources" value="src/main/resources/common" />
		<groups>
			<run>
				<include name="@WebSearch" />
			</run>
		</groups>
		<classes>
			<class
				name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>
```
Make sure you are setting credentials for all drivers, for example
```
driver.capabilities.user=<username>
```

**Comment by rajeshmahalingaswamy** [comment]
Thank you, Chirag.

I was able to launch the specific device type as required, with using different driver name as you mentioned above.
