### ISSUE TITLE
Qmetry QAF tests execution order issue

### ISSUE THREAD

**Issue by nakulkhargonkar** [qmetry/qaf#251]
### QAF Version
qaf-2.1.14
selenium 3.141.59

### Expected behavior
Oder of execution of Test Cases should run in lexicographical order.

### Actual behavior
Running in reverse order.
In the code given below  Test named MDM_4 is running first whle MDM_1 should run first.

### Is the issue reproducible on runner?
- [x] Ivy
- [x] Ant
- [x] Eclipse

### Test case sample
```

package com.tibco.automation.mdm.tests.test;

import org.apache.velocity.test.BaseTestCase;
import org.testng.annotations.Test;
import com.qmetry.qaf.automation.ui.WebDriverBaseTestPage;
import com.qmetry.qaf.automation.ui.WebDriverTestBase;
import com.qmetry.qaf.automation.ui.api.PageLocator;
import com.qmetry.qaf.automation.ui.api.WebDriverTestPage;
import com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver;
import com.tibco.automation.mdm.common.Roles;
import com.tibco.automation.mdm.tests.common.UtilityFunctions;

public class test extends WebDriverBaseTestPage<WebDriverTestPage> {
	public QAFExtendedWebDriver driver;
	public test(String name) {
		super();
		driver = new WebDriverTestBase().getDriver();
		// TODO Auto-generated constructor stub
	}
	@Test
	public void MDM_1() throws InterruptedException{
		System.out.println("in test 123");
		driver.get("http://10.97.108.121:9080/eml/Login");
		Thread.sleep(3000);
		UtilityFunctions.creatNewCompanyWithUser(UtilityFunctions.createArray(Roles.Administrator,
				Roles.RepositoryEditor));
	}
	@Test
	public void MDM_2() throws InterruptedException{
		UtilityFunctions.creatNewCompanyWithUser(UtilityFunctions.createArray(Roles.Administrator,
				Roles.RepositoryEditor));
	}
	
	@Test
	public void MDM_3() throws InterruptedException{
		UtilityFunctions.creatNewCompanyWithUser(UtilityFunctions.createArray(Roles.Administrator,
				Roles.RepositoryEditor));
	}
	
	@Test
	public void MDM_4() throws InterruptedException{
		UtilityFunctions.creatNewCompanyWithUser(UtilityFunctions.createArray(Roles.Administrator,
				Roles.RepositoryEditor));
	}
}


```
**Config file**
```
<suite name="QAF Example" verbose="0" preserve-order="true" >
	<test name="JAVA Test" preserve-order="true">
		<classes>
			<class name="com.tibco.automation.mdm.tests.test.test">				
			</class>
		</classes>
	</test>
</suite>

```

**Comment by cjayswal** [comment]
TestNg doesn't ensured order of the methods. It will run your tests in the order they are found in the XML file when specified `preserve-order="true"`.  For example:
```xml
<suite name="QAF Demo" verbose="0">
	<test name="java Test" enabled="true" preserve-order="true">
		<classes>
			<class name="com.tibco.automation.mdm.tests.test.test">
			<methods>
			<include name="MDM_1" />
			<include name="MDM_2" />
			<include name="MDM_3" />
			<include name="MDM_4" />			
			</methods>
			</class>
		</classes>
	</test>
</suite>
```
Furthermore above code needs to be updated by extending `WebDriverTestCase` instead of `WebDriverBaseTestPage`. It should look like below:
```java
public class Suite1 extends WebDriverTestCase {
	//avoid class variables in test class, try to  make  test independent of each other 
        //public QAFExtendedWebDriver driver; 
       //for driver, you can access using getDriver()
	public Suite1() {
		
	}
	@Test
	public void MDM_1() throws InterruptedException{
		System.out.println("in test 1");
		getDriver().get("http://10.97.108.121:9080/eml/Login");
	}
	@Test
	public void MDM_2() throws InterruptedException{
		System.out.println("in test 2");
	}
	
	@Test
	public void MDM_3() throws InterruptedException{
		System.out.println("in test 3");
	}
	
	@Test
	public void MDM_4() throws InterruptedException{
		System.out.println("in test 4");
	}
```

**Comment by nakulkhargonkar** [comment]
i might be wrong but, from my understanding we can run all the Test cases under a class by providing its name in xml file.

for eg.
```
<suite name="QAF Demo" verbose="0">
	<test name="java Test" enabled="true" preserve-order="true">
		<classes>
			<class name="com.tibco.automation.mdm.tests.test.test">
			</class>
		</classes>
	</test>
</suite>

```
in above xml file we are providing just a class name. TestNG will take care(run) of all the methods that are @test. We use this approcah since we have 20-30 test cases in a single class. So instead of writing names its convenient to write class name only.
Hence in that case order of execution is creating issue.

Could you please look into this once.

**Comment by cjayswal** [comment]
It smells wrong test design, you should consult to your automation lead/architect. 

However, You can add priority to test to get executed in specific order. To set priority either you can use `@Priority` annotation or add `priority` in `@Test`.

I would **not recommend**  to have implementation with such restriction where 20-30 test needs to get executed in order, because you are indirectly making them dependent and restrict them for being candidate for parallel execution. Also consider the case when you just want to run 1 or 2 test from them and assuming something from other test cases.  

For help, also refer existing discussion or  create new in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stack-overflow](http://stackoverflow.com/questions/tagged/qaf)

**Comment by cjayswal** [comment]
For further queries or question post in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf)
