### ISSUE TITLE
Help Needed | How can I access the test case name and Scenario name in the step definition

### ISSUE THREAD

**Issue by BChitrakannan** [qmetry/qaf#252]
Hi Team,

I need a help. 

`SCENARIO: First Test Case
META-DATA: {"description":"Some Test","groups":["SMOKE","Regression"], "author":"PK"}

 	Given Running the test
END`

I want to access the test case name (First Test Case) and Test Step Name (Running the test) in my step definition. can you please advise how I can achieve it ? I am using QAF.

Thanks in advance,
Best,
Chitrakannan

**Comment by cjayswal** [comment]
What you are trying to achieve? Will you please provide details about purpose?

**Comment by BChitrakannan** [comment]
Hi Chirag,

Thanks for the swift response.

The reason why I need this is, I need to write the report in Excel file. The excel file should have the TestName and Scenario name with Pass/Fail Status. 

I will try the one which you suggested. 

Thanks again.

Best,
CK

**Comment by cjayswal** [comment]
For further queries or question post in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf)
