### ISSUE TITLE
How to initialize  WaitService object outside Test. (Help wanted)

### ISSUE THREAD

**Issue by nakulkhargonkar** [qmetry/qaf#253]
In framework code you have explicitly mentioned that.
	/**
	 * **be careful while from initializing out side test**
	 */
	public WaitService() {
		this(new SeleniumTestBase().getDriver());
	}

The **pages** that were created for our tests have WaitService initialization n number of times. 
If we initialize it outside tests an exception is thrown and tests fails.
Please let us know how to initialize outside test.

Thanks,
Nakul

**Comment by cjayswal** [comment]
Are you using selenium 1 api or selenium2 (webdriver) api? If you are not clear about selenium 1 or 2 api you can share the code of test case and related page(s). 

You can post your question in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stack-overflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by nakulkhargonkar** [comment]
We were using selenium 1 and now converting it to selenium webdriver. 
We are clear with both APIs. Could you please tell how we can call WaitService outside test.

**Comment by cjayswal** [comment]
WaitService class you are referring, is used with selenium 1 api. With selenium 2 api refer documentation for [wait service](https://qmetry.github.io/qaf/latest/wait_service.html), [assertion and verification](https://qmetry.github.io/qaf/latest/assertion_verification.html)

**Comment by cjayswal** [comment]
For further queries or question post in [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf)
