### ISSUE TITLE
[Help needed] How to make BDD selective execution based on Gherkin tags?

### ISSUE THREAD

**Issue by atos-jl** [qmetry/qaf#254]
### QAF Version
Latest
> Note: only the latest version is supported

### Steps To Reproduce
    1. I have a Qmetry project with BDD feature files written in Gherkin and GherkinScenarioFactory working
    2. I have some of the BDD scenarios annotated with Gherkin tags
    3. How do I execute selective scenarios based on annotated tags?

### Expected behavior
Other Gherkin running engines like Cucumber allow to make selective execution of scenarios based on an expression passed as a parameter for including/excluding tags (e.g. in Cucumber using parameter: --tags "@tag1 and @tag2").

So, a similar feature is expected to have Qmetry as should support entire Gherkin specification with GherkinScenarioFactory running engine. How can this be achieved?

No reference for this have been found in online documentation yet .

### Actual behavior
As we have a Maven based project, when executed *mvn test* all feature files configured in TestNG XML file are executed. It seems there are no way to control wich tags include/exclude when launching execution.

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Not applicable.

**Comment by cjayswal** [comment]
Refer [running-tests-with-specific-groups](https://qmetry.github.io/qaf/latest/bdd-configuration.html#running-tests-with-specific-groups).

With QAF 2.1.14 `BDDTestFactory2` is recommended. It supports [BDD2 syntax](https://qmetry.github.io/qaf/latest/bdd-syntax.html) which is advance and superset of gherkin syntax.

If you are using `GherkinScenarioFactory` you need to provide tag with `@` sign when specifying groups (which is scenario tags) in configuration file. For example:
```
   <groups>
      <run>
        <include name="@smoke" />
      </run>
   </groups>
```

**Comment by atos-jl** [comment]
Thanks for your reply.

So in any case, used `BDDTestFactory2` or `GherkinScenarioFactory`, all the configuration must be done in XML and fixed when project build. There is no option to select which test group run when lauching application, isn't it?

It is a interesting and powerful feature that I suggest to be included in future versions.

**Comment by cjayswal** [comment]
Definitely you can do, the key point here is, you can use scenario tags as group. Refer TestNG documentation how to run specific groups  through command line. For example:
```
mvn test -Dgroups=group1,group2
```
Again it's depends what build tool (ant/maven/gradle) you are using and how you wrote build script. The bottom line is it will work how TestNG work and TestNG and so QAF, support running specific groups through command line.

Furthermore, with QAF, You can use [meta-data filter](https://qmetry.github.io/qaf/latest/scenario_metadatata_filter_include_exclude_prop.html) as well where you can [use properties](https://qmetry.github.io/qaf/latest/different_ways_of_providing_prop.html) `include` and `exclude` to filter test cases using meta-data. When you are using gherkin, only groups is supported in meta-data filter as gherkin doesn't have provision for custom meta-data. 

Knowingly or unknowingly you  opted very powerful framework which is way ahead in the industry.

Happy Learning...

**Comment by atos-jl** [comment]
Thansk for your support, that is the feature we were looking for.  

Definitely TestNG knowing functionality & documentation is key when using QAF.
