### ISSUE TITLE
Unable to trigger non http url with get command

### ISSUE THREAD

**Issue by deepakhadiya** [qmetry/qaf#255]
### QAF Version
> 2.1.14

### Steps To Reproduce
    1. Launch the html local file using get command in chrome browser
    

Observation:
Frame work is implicitly registering [WebDriverCommandLogger.java](https://github.com/qmetry/qaf/blob/master/src/com/qmetry/qaf/automation/ui/WebDriverCommandLogger.java), where "get" commands behavious is changes as per url triggered , line 96. 

Is there any way to ignore this implementation? or can we add a property flag to handle this. 

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
>  @driver.get("file://");

**Comment by amitbhoraniya** [comment]
Hi @deepakhadiya,

It is not a preferred way to open local file using selenium, cause this may create issue while executing testcases on selenium grid or remote machine. To read file or handle local files, you can directly use File Utility classes, you don't even require selenium to do that. 

Can you please provide us specific usecase that you want to archive through this?

Mean while below code snippet will work for you.
```java
Map<String, String> parameters = new HashMap<String, String>();
parameters.put("url", "file://your_file");
Command command = new Command(getDriver().getSessionId(), DriverCommand.GET, parameters);
getDriver().getCommandExecutor().execute(command);
```

**Comment by deepakhadiya** [comment]
Thanks Amit,
This solution works for me.
