### ISSUE TITLE
GherkinScenarioFactory ignores a Gherkin file when it has Feature description

### ISSUE THREAD

**Issue by atos-jl** [qmetry/qaf#257]
### QAF Version
> Note: only the latest version is supported

Latest  2.1.14

### Steps To Reproduce
    1. Have a QAF project configured with GherkinScenarioFactory runner configured
    2. Have one Gherkin file with a Feature with description, for example:
```
Feature: Multiple site support
  Only blog owners can post to a blog, except administrators,
  who can post to all blogs.

  Scenario: Dr. Bill posts to his own blog
    Given I am logged in as Dr. Bill
    When I try to post to "Expensive Therapy"
    Then I should see "Your article was published."
```

    3. Launch tests

### Expected behavior

QAF should execute Gherkin file as expected regardless it has description or not

### Actual behavior

QAF ignores that Feature and does not execute it. If description is removed QAF executes the Feature normally.

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

The issue is easily reproducible but test case sample could be provided if requested.

**Comment by cjayswal** [comment]
Do you mean that it not executing and ignores scenario(s) in the feature file?

**Comment by atos-jl** [comment]
Hi, yes I mean QAF ignores scenarios and not execute it. At least ignoring the first scenario as was tested with a Gherkin file with just one scenario, but likely it is ignoring whole Feature file.
