### ISSUE TITLE
Create a screenshot folder for each scenario with the scenario name and include all the screen shots in the corresponding folder..Finally Zip and upload to JIRA after Each Scenario 

### ISSUE THREAD

**Issue by araveeti** [qmetry/qaf#258]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
Team,
I would like to create a Folder and add all the screenshots corresponding to the scenario with time stamp and After each method,have to Zip the same folder and attach to the JIRA Test cases.Can some one please assist me if we have this functionality with QAF?

**Comment by cjayswal** [comment]
This looks custom need. Please post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by araveeti** [comment]
Thanks much Chirag Jayswal.....

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
