### ISSUE TITLE
How can I pass a Hashmap to a Scenario.....can some please assist

### ISSUE THREAD

**Issue by araveeti** [qmetry/qaf#259]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
I need to pass a Hashmap Object to a Scenario and from there  I need to read the Appropriate Test Data across all the steps in the Scenario.Can some one please let me know is there is a way to achieve?

**Comment by araveeti** [comment]
It will be really helpful....

**Comment by cjayswal** [comment]
It looks that you are trying to make your Scenario data-driven. Refer documentation for [data-driven tests](https://qmetry.github.io/qaf/latest/maketest_data_driven.html). 

This is not right place for questions or discussion. Please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by araveeti** [comment]
Thanks much Chirag Jayswal

Sure!

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
