### ISSUE TITLE
Running Same Scenario for Multiple Test Data

### ISSUE THREAD

**Issue by araveeti** [qmetry/qaf#260]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1. Scenario Driven with Multiple Hashmaps

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
Hi Assume the below Scenario

  Scenario Outline: Data Driven Examples
    Given load Test Data for "<TESTCASE_ID>"
    Given User is on Home Page
    When user completes Transation
    Then verify Transaction
    Examples:
      | TestCaseID |
      | TCID_02 |

Lets assume if the TCID_02 is repeated twice in external data files (rows),then I need to execute the same Scenario two times....
can I Achieve this?

**Comment by araveeti** [comment]
Hi..Can some one assist here please?

**Comment by cjayswal** [comment]
Refer documentation for [make test data driven](https://qmetry.github.io/qaf/latest/maketest_data_driven.html#bdd).

This is not right place for questions or discussion. Please help us to manage issues (bug and feature requests) by posting your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
