### ISSUE TITLE
Same local browser session for sequential tests in TestNG suite file

### ISSUE THREAD

**Issue by ShankarChoudhury** [qmetry/qaf#261]
### QAF Version
> Note: only the latest version is supported
2.1.12
### Steps To Reproduce
    1.Create two tests in TestNG suite xml file,configured to run concurrently
    2.Execute your suite file on a local chrome or firefox or IE browser
    3.The driver session(browser) closes after 1st test execution.A new driver session or a browser is created to run second test.

### Expected behavior
We want to check if its possible to continue with the first browser to run our second test instead of opening a new browser session.

### Actual behavior
Browser is closed once the first test is completed.A new browser is launched to run the second sequential test.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
Yes
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
It looks that you have `selenium.singletone` [property](https://qmetry.github.io/qaf/latest/properties_list.html) value set to `methods` change value to `tests` (which means test node in xml config file) or `false`. 

Please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by ShankarChoudhury** [comment]
Thanks for replying.Tried with 
 selenium.singletone=tests as well as 
selenium.singletone=false
Still i see a new browser when my second test is triggered.

**Comment by cjayswal** [comment]
It means from listener or configuration method either `selenium.singletone` property configured or `tearDown` called. In big enterprises, this behavior forced organization level as their standard practice. If that is the case you can consult to respective team member. 
In case the behavior is set through property, you have still chance to override by setting system property. For example: `system.selenium.singletone`. But if tearDown method called through listener or configuration method only thing you can do is not use that listener or base calss (which is not preferred if your organization force it). In other case remove  listener that does `tearDown`, for example,
If you have added perfecto's quantum dependency, it calls `tearDown` after [each test case](https://github.com/Project-Quantum/Quantum/blob/dafcb7730f3a71cdb53e047d4950ba5d4ede5044/src/main/java/com/quantum/listeners/QuantumReportiumListener.java#L194). You can debug and find out from where `tearDown` method is called. 

Please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by cjayswal** [comment]
Closing issue, refer [post in users group](https://groups.google.com/forum/#!topic/qaf-users/esn-fNVHcOY)
