### ISSUE TITLE
Reading from json in Cucumber scenario outline

### ISSUE THREAD

**Issue by Rupak-66** [qmetry/qaf#262]
### QAF Version
> Note: 2.1.14

 I have started exploring Qaf bdd framework lately and found it amazing. I got one issue when using Cucumber Scenario outline with QAF, I have given path to external json file as test data. But while executing @QAFTestStepProvider not able to read integer from json. It reading string just fine. Please help me here. Is it a bug or there is a way around for this

This is my json test data

[
    { "searchKey" : "Rupak", "searchResult":"Testng", "number": 96 },
    { "searchKey" : "Admin", "searchResult":"Yuont", "number": 78 },
    { "searchKey" : "Qa", "searchResult":"Umbrella", "number": 121 }
]

**Comment by cjayswal** [comment]
Can you share your scenario and step implementation as well?

This is not right place for questions or discussion. Please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
