### ISSUE TITLE
Unable to run the second scenario in QMetry

### ISSUE THREAD

**Issue by Karthick1126** [qmetry/qaf#264]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.getDriver().get("URL");...followed by some validations for MAKER
    2.getDriver().quit....... To quit the browser 
    3.getDriver().get("URL");...to Authorise the Maker validation

### Expected behavior
The Browser should launch again

### Actual behavior
 no such window: target window already closed

### Is the issue reproducible on runner?
- [ ] Maven
Yes

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
[WebDriverCommandLogger] - Executing quit parameters: {}
[WebDriverCommandLogger] - command: quit[ param-1: {}] Result: null
[UiDriverFactory] - UI-driver tear down complete...
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 25.431 sec <<< FAILURE!
Preparing For Shut Down...
Preparing For Shut Down...
[ChromeDriverHelper] - Stopping chrome driver service.

Results :

Failed tests:   XYZ
transfer(com.qmetry.qaf.automation.step.client.DataDrivenScenario): no such window: target window already closed
  Login to Back office IPSH Application and Authorize Transaction(com.qmetry.qaf.automation.step.client.DataDrivenScenario): no such window: target window already closed

**Comment by amitbhoraniya** [comment]
QAF itself manages the driver instance. So its not a best practice to manage the driver instance inside testcase. Instead of that use `selenium.singletone` property.

To create a driver instance for each testcase, use below property.
```
selenium.singletone=Methods
```

Still, if you want to manage driver by yourself, below code will work for you. But this is not recommended way and may impact on other things as well.
```
getDriver().get("https://www.google.com");
new WebDriverTestBase().tearDown();
getDriver().get("https://www.yahoo.com");
```

**Comment by Karthick1126** [comment]
Its working for me now... thank you so much

**Comment by cjayswal** [comment]
Please post your further questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
