### ISSUE TITLE
How to implement before & after methods for Feature & Scenario in QAF - gherkin?

### ISSUE THREAD

**Issue by Rupak-66** [qmetry/qaf#267]
### QAF Version
> Latest

Please help me to implement before & after for feature as well as scenario in QAF - gherkin.

**Comment by cjayswal** [comment]
This is not right place for questions or discussion. Please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by anxx15** [comment]
I have implemented this and can help you. See you at  [stackoverflow](https://stackoverflow.com/questions/tagged/qaf
)

**Comment by cjayswal** [comment]
closing inactive issue.
