### ISSUE TITLE
Execution context is not kept within Gherkin scenario

### ISSUE THREAD

**Issue by atos-jl** [qmetry/qaf#268]
### QAF Version
> Note: only the latest version is supported

Latest 2.1.14

### Steps To Reproduce
    1. Have a QAF project configured with GherkinScenarioFactory, one Gherkin file with one scenario
    2. In first Gherkin scenario step assign value to any variable of the class that implements the step
    3. In second Gherkin scenario step read value of that variable, it is null

### Expected behavior
The execution context is kept within scenario execution. Same behaviour than other Gherkin engines like Cucumber.

### Actual behavior
The execution context is not kept. Apparently a new instance of step implementation class is created for each step execution. The same instance of that class should be used for a whole scenario.

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

The issue is easily reproducible but test case sample could be provided if requested.

**Comment by cjayswal** [comment]
Did tried with `step.provider.sharedinstance=true`? Will you please share test case which reproduce the issue?

**Comment by atos-jl** [comment]
Thansk, didn't know about that property, with that it works as expected. In my opinion this should be default behaviour and optionally configure the opposite if needed.
Issue can be closed.

**Comment by cjayswal** [comment]
@atos-jl initially, when this feature provided, default behavior was set to assume shared instance, which resulted issues with existing tests where users not want to share instance.
