### ISSUE TITLE
Gherkin support for test case authoring

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf#28]
QAF supports cucumber as underlying framework for Gherkin but not all the features as QAF-BDD available because of  some limitation of cucumber. If QAF supports for Gherkin it will be more useful for those who want to opt Gherkin instead of QAF-bdd for testcase authoring.

**Comment by cjayswal** [comment]
- User should be able to opt either to provide step using QAFStepProvider of annotation from cucumber
- It should work with cucumber editor provided user has step implementation using cucumber annotation. 
- Scenario should be executed and  execution configuration should be same as QAF-BDD implementation

**Comment by cjayswal** [comment]
Factory class to configure in xml: `com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory`

You can have step implementation with cucumber `Given`, `When`, `Then`, `And`, `But` annotations or `QAFTestStepAnnotation`

- Even if you have cumber step implementation you can use those in gherkin implementation or in QAF bdd implementation
- Even if you have cumber step implementation with gherkin you can run as QAF step client (All features like run configuration, reporting parallel execution, step listener ) using GherkinScenarioFactory
- It will support test data outside feature file (all QAF data provider support) use QAF data-provider meta-data with Examples to have data from **text, csv, xml, excel or json file or DB** 
- Gherkin with cucumber step annotations in java should work with any cucumber editor.

**supported gherkin syntax:**

- Global tags at feature level
- Background
- Scenario tags
- Scenario
- Scenario outline
- Examples

Refer [feature files](https://github.com/qmetry/qaf/tree/master/test/resources/features) for [CucumberStepImpl.java](https://github.com/qmetry/qaf/blob/master/test/src/com/qmetry/qaf/automation/impl/step/cucumber/CucumberStepImpl.java) example of cucumber step implementation and [QAFTestStepImpl.java](https://github.com/qmetry/qaf/blob/master/test/src/com/qmetry/qaf/automation/impl/step/qaf/QAFTestStepImpl.java) for QAF step implementation example for the feature files. You need to provide either one of the implementation (you can have mixed implementation as well)

**Comment by patelakhil** [comment]
Awesome! Thanks!
