### ISSUE TITLE
How do you ensure QAF is thread safe when running Parallel execution?i meant the Data Retrieved from Excel,driver etc...

### ISSUE THREAD

**Issue by araveeti** [qmetry/qaf#280]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Are you facing any issue while running in parallel? If so please provide details and steps to reproduce. 

This is not right place for questions or discussion. Please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
