### ISSUE TITLE
dependsOnMethods not working for BDD

### ISSUE THREAD

**Issue by infoneershalin** [qmetry/qaf#281]
### QAF Version
> 2.1.14, 2.1.15-beta-1, 2.1.15-beta-2

### Steps To Reproduce
    1. Create BDD with dependentScenarios and make one scenario(on which other scenario is dependent) fail/skip.

### Expected behavior
Dependent scenario should not be executed.

### Actual behavior
Dependent scenario gets executed.

### Is the issue reproducible on runner?

- [x] QAS
- [x] Maven
- [x] Gradle
- [x] Ant
- [x] Eclipse

### Test case sample
> 

    SCENARIO: SignUp
    META-DATA: {"description":"Sample Test Scenario","groups":["SMOKE"]}

        Given this should fail or skip
        
    END

    SCENARIO: Login
    META-DATA: {"description":"Sample Test Scenario","groups":["SMOKE"],"dependsOnMethods":["SignUp"]}

        Given COMMENT: "This should not run"
        
    END

**Comment by cjayswal** [comment]
With qaf 3.0.0 we may not support test dependency with BDD or Feature file.  If one want to take benefit of test dependency and still want to implement BDD new feature of `RuntimeScenario` can be useful, where scenario is create during execution in Java code just like reading from BDD or Feature file. It will look like:

```java
 import static com.qmetry.qaf.automation.step.client.RuntimeScenarioFactory.scenario;
 
@Test(description="a sample scenario" ...)
 public void testWithGivenWhenThen() {

 	scenario().
	given("a precondition",()->{
 		//write appropriate code...
 	}).
 	when("some action performed",()->{
 		//write appropriate code...
 	}).
 	then("it should have expected outcome",()->{
 		//write appropriate code...
 	}).
 	execute();
 }
```
This will have all feature of BDD, like dry-run, reporting of each step including not-run steps, step listeners...
