### ISSUE TITLE
Unable to view QAF dashboard.htm in latest Firefox version 68.0.1

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#282]
### QAF Version
> Note: only the latest version is supported
2.1.13
### Steps To Reproduce
    1. Open the dashboard.htm in latest firefox version
    2.
    3.

### Expected behavior
User should able to view the report

### Actual behavior
Blank page is displayed

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Refer discussion in [users-group](https://groups.google.com/d/msg/qaf-users/CYz7JAhaccw/7bLEMCL4DwAJ) and detailed [answer](https://www.google.com/url?q=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F57049482%2Freport-is-not-displaying-in-dashboard-html-page-for-qmetry%2F57050031%2357050031&sa=D&sntz=1&usg=AFQjCNFC1TTmiIsgOEXiXEQ5YAnOH4PBzQ) to question on stackoverflow. 
Please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by Priya335021** [comment]
Thanks @cjayswal. I changed the firefox settings as suggested. It solved the issue. 

### Firefox Settings:
> If you observed it's not working after firefox update with latest firefox follow below steps:

go to about:config
set security.fileuri.strict_origin_policy:false. 

>

**Comment by yashvinaik146** [comment]
I tried above steps and it is not working
