### ISSUE TITLE
Getting error "qaf is not in Maven project registry." when "testrun_config.xml" run as TestNGSuite 

### ISSUE THREAD

**Issue by nilesh-bhamare** [qmetry/qaf#283]
### QAF Version
> Note: only the latest version is supported
2.1.14

### Steps To Reproduce
    1. Imported qaf project in Eclipse
    2. Build successful
    3. Run "testrun_config.xml" as TestNGSuite

### Expected behavior
It should execute project as TestNG

### Actual behavior
Getting error -  "qaf is not in Maven project registry."

### Is the issue reproducible on runner?

- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Refer [group discussion](https://groups.google.com/d/msg/qaf-users/fTvzUyziJWU/gkEFOICfEAAJ). Try updating pom as below:

```
        <dependency>
            <groupId>com.qmetry</groupId>
            <artifactId>qaf-support</artifactId>
            <version>${qaf.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.qmetry</groupId>
                    <artifactId>qaf</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
If still facing issue then it looks issue in your local environment. 

Please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
