### ISSUE TITLE
Feature/test is not getting executed by running build.xml as ANT

### ISSUE THREAD

**Issue by nilesh-bhamare** [qmetry/qaf#284]
### QAF Version
2.1.14

### Steps To Reproduce
1. Imported qaf project in Eclipse
2. Build successful
3. Run "build.xml" as ANT

### Expected behavior
Selected test/feature should be executed

### Actual behavior
Console is showing Test Run: 0

### Is the issue reproducible on runner?
- [X ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**“testrun_config.xml” file with below code:**

<test name="QAF-BDD2-tagged-example">
              
              <parameter name="step.provider.pkg" value="com.qmetry.qaf.automation.impl.step" />
              <parameter name="scenario.file.loc" value="resources/features" />
              <groups>
                     <run>
                           <include name="@Web"/>
                     </run>
              </groups>
              <classes>
                     <class
                           name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory2" />
              </classes>
       </test>

**Console Output:**

test:
   [testng] log4j:WARN No such property [follow] in org.apache.log4j.FileAppender.
   [testng] ...
   [testng] ... TestNG 6.10 by C�dric Beust (cedric@beust.com)
   [testng] ...
   [testng] [ConfigurationManager] - ISFW build info: {qaf-Type=core, qaf-Revision=15-beta-2, qaf-Version=2.1, qaf-Build-Time=24-Jul-2019 15:37:12}
   [testng] [ConfigurationManager] - Resource dir: C:\Eclipse\qaf-master\qaf-master\test\resources. Found property files to load: 1
   [testng] [ConfigurationManager] - Resource dir: C:\Eclipse\qaf-master\qaf-master\test\resources. Found property files to load: 2
   [testng] include groups [@Web]
   [testng]  exclude groups: [] Scanarios location: resources/features 
   [testng] [TestNG] Running:
   [testng]   C:\Eclipse\qaf-master\qaf-master\test\config\testrun_config.xml
   [testng] ===============================================
   [testng]     QAF-BDD2-tagged-example
   [testng]     Tests run: 0, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] ===============================================
   [testng] QAF Tests
   [testng] Total tests run: 0, Failures: 0, Skips: 0
   [testng] ===============================================
   [testng] [TestNG] Time taken by org.testng.reporters.jq.Main@a434c8: 119 ms
   [testng] [TestNG] Time taken by org.testng.reporters.EmailableReporter2@1f45fa1: 7 ms
   [testng] [TestNG] Time taken by org.testng.reporters.JUnitReportReporter@6e276e: 0 ms
   [testng] [TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 1 ms
   [testng] [TestNG] Time taken by org.testng.reporters.XMLReporter@145433b: 12 ms
   [testng] [TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@1083826: 159 ms
BUILD SUCCESSFUL
Total time: 1 minute 7 seconds

**Comment by cjayswal** [comment]
Refer [documentation](https://qmetry.github.io/qaf/latest/bdd-configuration.html#running-tests-with-specific-groups), you don't need to add @ when using bdd2. For example,
```
 <include name="Web"/>
```

For further queries please post your questions and/or discussions in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).

**Comment by cjayswal** [comment]
If still not working with above solution, Post your questions to [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf).
