### ISSUE TITLE
Gson interprets integers as floats for DATASET_TYPE = new TypeToken<List<Map<String, Object>>>()

### ISSUE THREAD

**Issue by TomasBahnik** [qmetry/qaf#285]
### QAF Version
2.1.14

### Steps To Reproduce
Json data from dataFile of the form 
```
    "body": {
      "startIndex": 0,
      "length": 10
    }
```
are mapped by 
`mapData = gson.fromJson(jsonStr, DATASET_TYPE);` in 

`com.qmetry.qaf.automation.util.JSONUtil#getJsonArrayOfMaps`
as 
```
    "body": {
      "startIndex": 0.0,
      "length": 10.0
    }
```

See https://stackoverflow.com/questions/15507997/how-to-prevent-gson-from-expressing-integers-as-floats

This is an issue when the values are sent to backend and validated as integers.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
@TomasBahnik will you please provide test case to reproduce the behavior?

**Comment by cjayswal** [comment]
@TomasBahnik i assume that you are considering the case of data driven test with json data file. Please let us know if it is something else.

**Comment by cjayswal** [comment]
Fixed in https://github.com/qmetry/qaf/commit/68c810ae118bb3deeb859b6bad752b966941e34c

**Comment by TomasBahnik** [comment]
> @TomasBahnik i assume that you are considering the case of data driven test with json data file. Please let us know if it is something else.

@cjayswal Sorry for delay. Exactly. When I specify JSON data (for data driven test) as
```

**Comment by cjayswal** [comment]
@TomasBahnik, If my understanding is correct, you are referring in report. Can you try 3.0.0-beta-1? It has updated `com.qmetry.qaf.automation.util.JSONUtil#getJsonArrayOfMaps`.
