### ISSUE TITLE
QAF script execution through command line not working

### ISSUE THREAD

**Issue by abhishekDautomator** [qmetry/qaf#288]
### QAF Version
2.1.10

### Steps To Reproduce
    1. Calling testrun_config.xml file using java providing following set of command in the CMD :
       
set projectLocation=C:\Users\abhishek.narayan\git\com.rxcorp.project.automation

cd %projectLocation%

set classpath=%projectLocation%\Project_Automation\src\test\java\iqvia\platform\stepdef\suite\*;%projectLocation%\Project_Automation\scenarios\*;%projectLocation%\.idea\libraries\*;

java org.testng.TestNG %projectLocation%\config\testrun_config.xml
   

### Expected behavior
Execution should start

### Actual behavior
Could not find or load main class org.testng.TestNG
Caused by: java.lang.ClassNotFoundException: org.testng.TestNG

Not able to run the testrun_config.xml. Please provide the correct process of running through command line.

**Comment by cjayswal** [comment]
Refer similar [question](https://stackoverflow.com/questions/11896791/how-to-run-testng-from-command-line). It is preferred to use build tool like ant or maven. You can find sample template for [ANT+IVY](https://github.com/qmetry/qaf-blank-project), [Maven](https://github.com/qmetry/qaf-blank-project-maven) and [Gradle](https://github.com/qmetry/qaf-blank-project-gradle).

**Comment by abhishekDautomator** [comment]
Hi cjayswal, as my project is using maven build so i tried executing my test using mvn test and it worked for me after successfully resolving some issues using mvn install under my project path. Thanks for the assistance.
