### ISSUE TITLE
StepNotFoundException is thrown even when step is implemented

### ISSUE THREAD

**Issue by raviguptasmarsh** [qmetry/qaf#291]
### QAF Version: 2.1.14
> Note: only the latest version is supported

### Steps To Reproduce
  This is an intermittent issue and there seems to be no pattern.

### Expected behavior
The step should execute.

### Actual behavior
StepNotFoundException is thrown

### Is the issue reproducible on runner?

- [ ] QAS
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

**Comment by mishalhshah** [comment]
can you provide more information ?
Still based on the exception there are 2 possibilities:
1)  It seems duplicate method names in java and having different BDD description. Make sure method names are different in java.
2) Java method not exist/created which is being called from BDD.

**Comment by amitbhoraniya** [comment]
Hi Ravi, 

First check with `step.provider.pkg` property, make sure it points to correct package.

If that is correct then try with providing unique `stepName` to your step implementation.

```java
@QAFTestStep(description="user logins with {username} and {password}",stepName="user login with username and password")
public void login(String username,String password){
}
```

**Comment by raviguptasmarsh** [comment]
> 
> 
> can you provide more information ?
> Still based on the exception there are 2 possibilities:
> 
>     1. It seems duplicate method names in java and having different BDD description. Make sure method names are different in java.
> 
>     2. Java method not exist/created which is being called from BDD.

@mishalhshah Yes, as per you pointed out. I was using different step descriptions for 2 overloaded methods. Thanks for informing about this limitation in QAF.

**Comment by raviguptasmarsh** [comment]
> 
> 
> Hi Ravi,
> 
> First check with `step.provider.pkg` property, make sure it points to correct package.
> 
> If that is correct then try with providing unique `stepName` to your step implementation.
> 
> ```java
> @QAFTestStep(description="user logins with {username} and {password}",stepName="user login with username and password")
> public void login(String username,String password){
> }
> ```

What is the difference between "description" and "stepName" ? In our current projects, we use "description" and it works fine.

**Comment by raviguptasmarsh** [comment]
@mishalhshah Same methods names in different classes can also create issue ?

**Comment by raviguptasmarsh** [comment]
Thanks for the quick reply @mishalhshah @amitbhoraniya and @naeem-github

**Comment by mishalhshah** [comment]
> 
> 
> @mishalhshah Same methods names in different classes can also create issue ?

@raviguptasmarsh  yes same java method names without unique "StepName" in QAFTestStep will create issue.
So as suggested by @amitbhoraniya , add the unique stepName in QAFTestStep annotation or give the different java method names. let me know after applying any of the above solution works for you or not.

**Comment by amitbhoraniya** [comment]
`stepName` is a unique identifier for QAFTestStep. If `stepName` is not provided then QAF considers method name as a `stepName`. 
`description` is used to call teststep from bdd file.
