### ISSUE TITLE
Handling multipart data 

### ISSUE THREAD

**Issue by raviguptasmarsh** [qmetry/qaf#292]
How to handle the post/put operation a multipart file using QMetry ? In our current framework, we use xml files to handle the JSON creation for request body which looks something like:

`<publickey>
	<withClientId>
		<put>
			<headers>${keymanagement.header}</headers>
			<endPoint>${keymgmnt.keypair.endpoint}</endPoint>
			<baseUrl>${keymanagementapi.baseurl}</baseUrl>
			<method>PUT</method>
			<query-parameters>{"masterKeySource":"${masterKeySource}","alias":"${key.alias}"
			</query-parameters>
			<body>{"publicKey": "${publicKey}"}
			</body>
		</put>
	</withClientId>
</publickey>
`

Or should we use Curl commands instead of using QMetry based solution for this.

**Comment by amitbhoraniya** [comment]
Multipart data can be passed using `form-parameters` key.
Below is an working example to upload file using multipart formdata.
```xml
<fileupload>
	<post>
		<baseUrl>http://httpbin.org</baseUrl>
		<endPoint>/post</endPoint>
		<method>POST</method>
		<headers>{"Accept":"application/json"}</headers>
		<query-parameters>{"search":"test"}</query-parameters>
		<form-parameters>{"key1":"value1","key2":"value2","filekey":"file:resources/test.xml"}
		</form-parameters>
	</post>
</fileupload>
```

**Comment by raviguptasmarsh** [comment]
@amitbhoraniya Thanks for the help. It worked fine.
