### ISSUE TITLE
Information needed : How can we implement WebDriverManager in QAF project

### ISSUE THREAD

**Issue by abhishekDautomator** [qmetry/qaf#293]
### QAF Version
2.1.10

Information needed : How can we implement **WebDriverManager** in QAF project so that we don't need to provide driver for the browser and the latest version would be automatically downloaded.

**Comment by amitbhoraniya** [comment]
Here I have implemented WebDriverManager in QAF. You can refer this example.
https://github.com/amitbhoraniya/Databean-Component-Example

**Comment by abhishekDautomator** [comment]
@amitbhoraniya Hi, why we have to provide browser driver in application.properties file like you did in your project 
webdriver.chrome.driver =/Users/amit.bhoraniya/Documents/drivers/chromedriver,
 if we are using webdrivermanager and it automatically downloads the driver.

**Comment by amitbhoraniya** [comment]
You don't need to provide that.

**Comment by abhishekDautomator** [comment]
@amitbhoraniya But it's throwing error if I am not providing that property.

**Comment by cjayswal** [comment]
That example uses [driver listener](https://github.com/amitbhoraniya/Databean-Component-Example/blob/master/src/test/java/com/qmetry/qaf/example/listeners/WDListener.java) did you created and registered listener?

**Comment by abhishekDautomator** [comment]
@cjayswal @amitbhoraniya thanks for the suggestions. After adding WDListener class, i am able to run my script without the need of providing the browser driver.
