### ISSUE TITLE
Suggestion required: How to convert QAF refort into simple HTML report

### ISSUE THREAD

**Issue by abhishekDautomator** [qmetry/qaf#294]
Suggestion required: How to convert QAF report into simple HTML report that can be send over the email, detailing high level details with Check points validation logs. Please help as we don't have a server and port to host the report there which can be viewed by entire team seating across the globe.

**Comment by cjayswal** [comment]
are you looking for emailable report? If so you can register [EmailableReporter](https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/reporters/EmailableReporter.html) or  [EmailableReporter2](https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/reporters/EmailableReporter2.html) listener. You also can have default html reports generated by TestNG including emailable by setting `useDefaultListeners` to `true` in ant or maven.

**Comment by abhishekDautomator** [comment]
I have used IReporter listener class to create a customized report for this. It's working good and I am able to get the required details of each test steps and test points too.
