### ISSUE TITLE
Failed rerun test cases are showing as skipped in results

### ISSUE THREAD

**Issue by is-shobhankarmakar** [qmetry/qaf#295]
### QAF Version
> Note: only the latest version is supported
I am using qaf bdd framework in eclipse. i am having a scenario file having 1 scenario which will fail and i have kept retry.count=1 in application.properties file.
### Steps To Reproduce
    1.Run the scenario file using maven  which should contain a scenario which will fail which should not fail due to some exception.
    2.It ran for 1st time and it failed and since we kept retry.count=1 , it again ran for the second time.
    3.Getting Tests run: 2, Failures: 1, Skips: 1

### Expected behavior
Getting Tests run: 2, Failures: 2, Skips: 0 

### Actual behavior
Tests run: 2, Failures: 1, Skips: 1 . 

### Is the issue reproducible on runner?

- [ ] QAS
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ .] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
This is expected behavior to skip result where test rerun happened.

**Comment by amitbhoraniya** [comment]
This is expected behavior. Reference: https://github.com/cbeust/testng/issues/1715

**Comment by cjayswal** [comment]
Closing as it is expected behavior.
