### ISSUE TITLE
Not able to work with Appium studio with the QAF Framework. 

### ISSUE THREAD

**Issue by Khyathikonala** [qmetry/qaf#297]
Hello QAF Team, 
We setup Appium Desktop in our mechine and using hte same QAF Framework it was working fine. 
After that we setup appium studio and we want to use the same QAF  Framework with Appium Studio too. But it is throwing the following error. 

[RemoteTestNG] detected TestNG version 6.10.0
main: ISFW build info: {qaf-Type=core, qaf-Revision=13, qaf-Version=2.1, qaf-Build-Time=20-Feb-2018 00:19:29} 
 
include groups [@ContractAdminRefines]
 exclude groups: [] Scanarios location: src/main/resources/scenarios 
TestNG: Adding resources from: src/main/resources/android 
TestNG: â–ˆ TEST STARTED: Contract_Admin_Refines [{passcode=Welcome1, url=https://vf4-cust225.dev.sapbydesign.com, username=administration01, password=Welcome1, customer_account_id=MC6127, product_id=MCF-0001, serial_id=SER_, contracts_new_name=Cont_, service_level=MCSL-0005, create_so_type=Service Contract, create_new_contracts_notes_customer_information=New Notes For Customer Information}]
TestNG: â–„ â–„ â–„ BEGIN STEP: Given I launch application in appium â–„ â–„ â–„
TestNG: Initializing Driver...browser_str:appiumDriver,base_url:,sel_server:http://127.0.0.1:4723/wd/hub,port:4723 
TestNG: Driver: appiumDriver 
Unable to create driver instance in 1st attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for appium: java.lang.reflect.InvocationTargetException
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'INLN50942421A', ip: '192.168.246.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
TestNG: Driver: appiumDriver 
Unable to create driver instance in 2nd attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for appium: java.lang.reflect.InvocationTargetException
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'INLN50942421A', ip: '192.168.246.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
TestNG: Driver: appiumDriver 
Unable to create driver instance in 3rd attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for appium: java.lang.reflect.InvocationTargetException
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'INLN50942421A', ip: '192.168.246.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
TestNG: Driver: appiumDriver 
Unable to create driver instance in 4th attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance for appium: java.lang.reflect.InvocationTargetException
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'INLN50942421A', ip: '192.168.246.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
TestNG: â–€ â–€ â–€ END STEP: Given I launch application in appium â–€ â–€ â–€
Preparing For Shut Down...
Preparing For Shut Down...
application pro file.
remote.server=http://127.0.0.1:4723/wd/hub
remote.port=4723
driver.name=appiumDriver
#TODO
appName=Cloud4CustEx
driver.additional.capabilities={'platformName': 'Android','platformVersion':'7.0','driverClass':'io.appium.java_client.android.AndroidDriver','deviceName': '040ffea0047b6829','app': 'C:/Users/c5257429/Downloads/Cloud4CustEx-1911.1.1-SNAPSHOT.apk',  'newCommandTimeout': '120',  'udid': '040ffea0047b6829',  'autoWebview': false,  'appActivity': 'Aurora',  'appPackage': 'com.sap.cloud4custex',  'recreateChromeDriverSessions': false,'noReset':true,'acceptSslCerts':true}

**Comment by cjayswal** [comment]
Make sure you have appium server running on 127.0.0.1 on port 4723.

**Comment by Khyathikonala** [comment]
Thanks You, i seen log and we find that issue. Now its working fine.
