### ISSUE TITLE
Factory Tests throwing exception in latest version (2.1.15) of QAF

### ISSUE THREAD

**Issue by wildcat111** [qmetry/qaf#311]
### QAF Version - 2.1.15
> Note: only the latest version is supported

### Steps To Reproduce
    1. Run the attached file DeviceFactory Test suite using the latest QAF Maven project. 
     - The attached code doesn't require QAF and if you remove the QAF Dependency it works as expected.

 Note: The tests in the attached file work just fine with QAF 2.1.13, it is failing in 2.1.14 & 2.1.15

### Expected behavior
Test should be executed without exception.

### Actual behavior
Tests fail with the following exception:

Can't invoke public java.lang.Object[][] com.qmetry.qaf.example.test.DeviceTests.deviceLocations(): either make it static or add a no-args constructor to your class

### Is the issue reproducible on runner?

- [ ] QAS
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample

[test.zip](https://github.com/qmetry/qaf/files/4039191/test.zip)

> Please, share the test case (as small as possible) which shows the issue

**Comment by amitbhoraniya** [comment]
Hi @wildcat111,

Recently in QAF we added support for [Test Data Filter](https://qmetry.github.io/qaf/latest/data_driven_filter.html) and DataProvider Interceptor. That looks culprit for your issue. I have raised a pull request for your issue.

**Comment by wildcat111** [comment]
For anyone facing this issue, I am able to use version 2.1.13 with selenium 3.141.59.  I did have to add the selenium-support dependency version 3.0.0 as mentioned here by @cjayswal https://github.com/SeleniumHQ/selenium/issues/4096#issuecomment-309080451. 
 Without this dependency I kept getting compilation errors for many of the standard selenium imports.
