### ISSUE TITLE
Need to update `driver.actualCapabilities` when switching between drivers

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf#313]
https://github.com/qmetry/qaf/blob/390a821bcb6f75708e37df0fa9e1fb7fa623d25b/src/com/qmetry/qaf/automation/core/QAFTestBase.java#L209

When switching between drivers current implementation takes care of driver specific resource are loaded but not updating property `driver.actualCapabilities`

**Comment by amitbhoraniya** [comment]
Hi Chirag,

How to manage driver specific `remote.server` and `remote.port` properties while switching between drivers? For different driver I want to use different `remote.server` url.

**Comment by cjayswal** [comment]
You should be able to achieve that by setting property before getdriver call in code.
