### ISSUE TITLE
BDD: Parameterized background is not working in qaf-cucumber  

### ISSUE THREAD

**Issue by AkshataShirol** [qmetry/qaf#319]
### QAF Version
2.1.15

### Steps To Reproduce
    1.Create scenarios with background having parameters
Ex: Feature: Online Application

Background: 
Given a customer "<Username>" logs in to application

Scenario: .....

    2. Run via Cucumber runner or testNG runner, its not taking the value of <Username> 
    3. Its not working with external data file and examples.

### Expected behavior

Should take the value from external data file or examples
### Actual behavior
Its not taking the <Username> value when parameters are added to the background steps

### Is the issue reproducible on runner?
yes
- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
@AkshataShirol  this should be reported under [qaf-cucumber/issues](https://github.com/qmetry/qaf-cucumber/issues )

**Comment by AkshataShirol** [comment]
@cjayswal  Created. https://github.com/qmetry/qaf-cucumber/issues/1

Closing this issue
