### ISSUE TITLE
Need Information: Qmetry Report

### ISSUE THREAD

**Issue by shibupanda** [qmetry/qaf#323]
It's a great framework and really appreciate team efforts.
Only thing left for me is reporting.

Is there any configuration needs to be done somewhere to get the reports as I didn't see any qmetry dashboard in my project after successful execution.

**Comment by cjayswal** [comment]
Make sure that your project contains `dashboard` directory and `dashboard.htm` file. If not you can get it from [qaf-report](https://github.com/infostretch/qaf-report). You can open dashboard.htm in Firefox, Safari or Edge browser to view execution report. Furthermore, you don't need to wait for all tests to get complete. During execution you can see results of completed tests.

**Comment by cjayswal** [comment]
@shibupanda please let us know if you need further help. If there is no issue and it works fine this can be closed.

Please post your question or discussions in [users group](https://groups.google.com/forum/#!forum/qaf-users) or in [stackoverflow with qaf tag](https://stackoverflow.com/questions/tagged/qaf).

**Comment by shibupanda** [comment]
Thanks I will reopen if will face any.
