### ISSUE TITLE
NeedInfo: Support for Headless Browser

### ISSUE THREAD

**Issue by KarthikSmarsh** [qmetry/qaf#326]
Needed information about support for Headless browser in QAF framework. Could you please suggest headless browsers that can be run in linux containers.

**Comment by raviguptasmarsh** [comment]
Can QMetry use "HTMLUnitDriver" ?

**Comment by raviguptasmarsh** [comment]
Another option is that chromedriver supports headless but it can be done using: 

ChromeOptions options = new ChromeOptions();
options.addArguments("headless");
options.addArguments("window-size=1200x600");
WebDriver driver = new ChromeDriver(options);
driver.get("http://seleniumhq.org");

Is there a way to add "options" using QMetry ?

**Comment by raviguptasmarsh** [comment]
Another option to run automation on a UI less linux server is using:

ChromeDriverService service = new ChromeDriverService.Builder()
    .usingChromeDriverExecutable(new File("/path/to/chromedriver"))
    .usingAnyFreePort()
    .withEnvironment(ImmutableMap.of("DISPLAY",":20"))
    .build();

WebDriver driver = new ChromeDriver(service, chromeOptions);

Is there a way to do this in QMetry?

**Comment by cjayswal** [comment]
Yes you can. either you can run chrome or firefox in headless mode or use phantomJS driver. All you need to do is set capability accordingly. phantomjs can be used as custom driver, use drivername `phantomjsDriver` and set `driverClass` in capabilities.

For help and discussion post in qaf community [users group](https://groups.google.com/forum/#!forum/qaf-users).

**Comment by chemerson** [comment]
samples please!!
