### ISSUE TITLE
NeedInfo: Can ChromeDriver be instantiated instead of RemoteWebdriver

### ISSUE THREAD

**Issue by raviguptasmarsh** [qmetry/qaf#327]
### Steps To Reproduce
When extending  WebDriverBaseTestPage<WebDriverTestPage>, we basically use RemoteWebDriver in that class when we perform driver.get("https://google.com").

Is there a way where I can instantiate ChromeDriver instead of RemoteWebDriver ?

Asking this because for retrieving the performance logs,

only ChromeDriver is supported and RemoteWebDriver seems to have a bug.

########
**This works(Non-QMetry version using ChromeDriver):**
ChromeOptions options = new ChromeOptions();
LoggingPreferences logPrefs = new LoggingPreferences();
logPrefs.enable(LogType.PERFORMANCE, Level.INFO);

DesiredCapabilities caps = DesiredCapabilities.chrome();
caps.setCapability("goog:loggingPrefs", logPrefs);
options.merge(caps);

WebDriver driver = new ChromeDriver(options);
driver.get("https://www.google.com/");
List<LogEntry> entries = driver.manage().logs().get(LogType.PERFORMANCE).getAll();

###########
**This does not(QMetry):**
public class LoginPage extends WebDriverBaseTestPage<WebDriverTestPage> {
       driver.get("https://www.google.com/");
       List<LogEntry> entries = driver.manage().logs().get(LogType.PERFORMANCE).getAll();
}

where,
chrome.additional.capabilities={"chromeOptions":{"args":["start-maximized"]}, "goog:loggingPrefs":{"performace":"ALL"}}

**Comment by cjayswal** [comment]
you need to make sure that required capability provided. There are two ways:

1. If you are unsure about capability, using main method print capabilities and get idea what to set as using property 
2. set capability through code using [driver listener](https://qmetry.github.io/qaf/latest/qaf_listeners.html#webdriver-listener). 

### Example for solution 1:

```
public static void main(String[] args) throws IOException {
		ChromeOptions options = new ChromeOptions();
		LoggingPreferences logPrefs = new LoggingPreferences();
		logPrefs.enable(LogType.PERFORMANCE, Level.INFO);

		DesiredCapabilities caps = DesiredCapabilities.chrome();
		caps.setCapability("goog:loggingPrefs", logPrefs);
		options.merge(caps);
		System.out.println(JSONUtil.toString(caps.asMap()));
}
```
This print below for for me:
```
{"browserName":"chrome","goog:loggingPrefs":{"prefs":{"performance":{"name":"INFO","value":800,"resourceBundleName":"sun.util.logging.resources.logging"}}},"platform":"ANY","version":""}
``` 
### Example for solution 2:
Implement and register driver listener. Set addition capabilities in `beforeInitialize`.
```
	@Override
	public void beforeInitialize(Capabilities desiredCapabilities) {
		LoggingPreferences logPrefs = new LoggingPreferences();
		logPrefs.enable(LogType.PERFORMANCE, Level.INFO);
		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("goog:loggingPrefs", logPrefs);
		desiredCapabilities.merge(caps);
	}
```

**Comment by raviguptasmarsh** [comment]
@cjayswal Thanks for this information.

However, the issue that we are facing is that Performance logging is not supported by RemoteWebDriver(which QAFExtendedWebDriver extends). Only ChromeDriver can render the performance logs, it seems.

Is there a way QAFExtendedWebDriver can be used with ChromeDriver instead ?

**Comment by raviguptasmarsh** [comment]
Had raised an issue with selenium as well but they closed it saying it is non-trivial amount of work.
https://github.com/SeleniumHQ/selenium/issues/8086

**Comment by cjayswal** [comment]
When you are using driver name `chromDriver` it creates chromeDriver only. To access underlying driver you can use following way. 

```
ChromeDriver chromeDriver = (ChromeDriver)driver.getUnderLayingDriver();
```

Keep in mind, when you configure remote driver for example `chromeRemoteDriver` you will not have under laying driver.

**Comment by cjayswal** [comment]
@raviguptasmarsh, did you tried using under laying driver as above example?

Please post your question or discussions in [users group](https://groups.google.com/forum/#!forum/qaf-users) or in [stackoverflow with qaf tag](https://stackoverflow.com/questions/tagged/qaf).

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
