### ISSUE TITLE
Chrome additional capabilities are not considered while creating second driver

### ISSUE THREAD

**Issue by ischandra** [qmetry/qaf#332]
### QAF Version : 3.0.0-RC3
> Note: only the latest version is supported

### Steps To Reproduce
    1.  Add chrome additional capabilities in application.properties
       Example : chrome.additional.capabilities ={'cap1':'cap1Value','cap1':'cap1Value'}
    2.  Create driver. Additional capabilities taken into consideration.
    3.  Create another driver using CommonStep.switchDriver("chrome2Driver);

### Expected behavior
Second chrome driver should consider additional capabilities.

### Actual behavior
Second chrome driver gets created with default capabilities. does not consider additional capabilities.

### Is the issue reproducible on runner?

- [] QAS
- [x] Maven
- [ ] Gradle
- [] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Related to #241
