### ISSUE TITLE
TestNG viewer in eclipse is empty

### ISSUE THREAD

**Issue by ischandra** [qmetry/qaf#333]
### QAF Version
> 3.0.0-RC3

### Steps To Reproduce
    1. Run any TestNG method as Run As --> TestNG Test

### Expected behavior
TestNG viewer should show test details.

### Actual behavior
Its empty.No results show.

### Is the issue reproducible on runner?

- [] QAS
- [x] Maven
- [ ] Gradle
- [] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by raviguptasmarsh** [comment]
Facing the same issue with 3.0.0-RC-3
