### ISSUE TITLE
ApplicationProperties  getStringVal method returns list if property provided multiple times

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf#334]
### QAF Version
3.0.0-RC2+

### Steps To Reproduce
    1. Add any application property multiple times, let say  `element.default.metadata`
    2. Now retrieve string value using `getStringVal()` method, for example ApplicationProperties.ELEMENT_GLOBAL_METADATA.getStringVal();

### Expected behavior
Should return String value, which is last value assigned to the property

### Actual behavior
Returns list

Works fine till 3.0.0-RC1

**Comment by raviguptasmarsh** [comment]
When should we expect this bug fix ? Will it be part of 3.0.0-RC4 release ?

**Comment by cjayswal** [comment]
Yes, release candidate will be available by next weekend.
