### ISSUE TITLE
Multiple parsing issues with 3.0.0-RC3

### ISSUE THREAD

**Issue by raviguptasmarsh** [qmetry/qaf#335]
### QAF Version
3.0.0-RC3

Scenario 1:
csv file example:
summary,file-format,amount-rows,with-data
Create Users is FALSE (XLSX),xlsx,1,"Create Users":"FALSE"

Getting this Exception:
java.lang.RuntimeException: com.qmetry.qaf.automation.testng.DataProviderException: Error while fetching data from resources/data/orchestrator/orchestrator_bulk_users_profiles_smoke_ddt.csv
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:111)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.qmetry.qaf.automation.testng.DataProviderException: Error while fetching data from resources/data/orchestrator/orchestrator_bulk_users_profiles_smoke_ddt.csv
	at com.qmetry.qaf.automation.util.CSVUtil.getCSVDataAsMap(CSVUtil.java:183)
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.getData(QAFInetrceptableDataProvider.java:323)
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.interceptedDataProvider(QAFInetrceptableDataProvider.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 10 more
Caused by: org.json.JSONException: Bad character ':' (58). at 77 [character 78 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.CDL.rowToJSONArray(CDL.java:121)
	at com.qmetry.qaf.automation.util.StringUtil.getArrayFromCsv(StringUtil.java:559)
	at com.qmetry.qaf.automation.util.StringUtil.parseCSV(StringUtil.java:364)
	at com.qmetry.qaf.automation.util.CSVUtil.getCSVDataAsMap(CSVUtil.java:160)
	... 19 more

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

How to pass special characters from csv dataFile now ?

**Comment by raviguptasmarsh** [comment]
Also cannot leave a variable value empty in the csv

summary,file-format,with-data,amount-rows
one valid email address (XLSX),xlsx, ,1

This variable is not even set for the test:
And generate 'xlsx' into file 'fileName' for '1' users and profiles with data '{${with-data}}'[0.005s ] 

Report looks like this:
And generate 'xlsx' into file 'fileName' for '1' users and profiles with data '{${with-data}}'[0.005s ] 
Unable to invoke JavaStep with given arguments: generateBulkUserProfileWithData[xlsx, fileName, 1, {${with-data}}]
at 



All the above 2 scenarios were working fine in 2.14-RC1

**Comment by raviguptasmarsh** [comment]
Scenario 3:
Not able to use special characters in the bdd steps as well e.g:

Given store "!@#$%^&*()_+-= {}[]\\|;':\\\",./<>?~`/\\'" into 'message'
And generate file having '1' messages and type '${type}' into 'batchFileName' with custom message '${message}'

This step is not found.

**Comment by raviguptasmarsh** [comment]
Scenario 4:
If we have in one of the properties file a key like this:

test.key = !@#$%^&*()_+-= {}[]\|;':\",./<>?~`/\'

Then this cannot be used directly in the bdd step file:
And use '${test.key}' to create a user

**Comment by cjayswal** [comment]
> 
> 
> Scenario 2:
> Cannot leave a variable value empty String in the csv. It takes null and not a whitespace value which was the case earlier.
> 
> summary,file-format,with-data,amount-rows
> one valid email address (XLSX),xlsx,,1
> 
> This variable is not even set for the test:
> And generate 'xlsx' into file 'fileName' for '1' users and profiles with data '{${with-data}}'[0.005s ]
> 
> Report looks like this:
> And generate 'xlsx' into file 'fileName' for '1' users and profiles with data '{${with-data}}'[0.005s ]
> Unable to invoke JavaStep with given arguments: generateBulkUserProfileWithData[xlsx, fileName, 1, {${with-data}}]
> at
> 
> Workaround:
> As of now based on your implementation code, I've added \ followed by a comma at the end for every line in the csv so that we can use the older implementation code:
> 
> summary,file-format,with-data,amount-rows
> one valid email address (XLSX),xlsx,,1,,
> 
> This was working fine in 2.14-RC1

This behavior is as per design with 2.1.14+ available from 2.1.14-RC3. Refer release notes from [2.1.14-RC3](https://github.com/qmetry/qaf/releases/tag/2.1.14-RC3) `Updated CSV, XML and Excel data provider to return objects instead of Strings`

**Comment by cjayswal** [comment]
> 
> 
> Scenario 4:
> If we have in one of the properties file a key like this:
> 
> test.key = !@#$%^&*()_+-= {}[]|;':",./<>?~`/'
> 
> Then this cannot be used directly in the bdd step file:
> And use '${test.key}' to create a user

`;` is list separator for value(s) provided in property file. if value contains `;` you need to add escape char `\`, for example:

```
test.key = !@#$%^&*()_+-= {}[]|\;':",./<>?~`/'
```

**Comment by cjayswal** [comment]
> Scenario 3:
> Not able to use special characters in the bdd steps as well e.g:
> 
> Given store "!@#$%^&*()_+-= {}[]\|;':\",./<>?~`/\'" into 'message'
> And generate file having '1' messages and type '${type}' into 'batchFileName' with custom message '${message}'
> 
> This step is not found.

Do you mean that this was working with older version and not working with latest? 
In above case your value contains special char `\`which is used as escape char so you if your value has `\` you need to provide as `\\`. I tried below example and it worked for me

```
Given store "!@#$%^&*()_+-= {}[]\\|;':\",./<>?~`/\\'" into 'message'
```

**Comment by raviguptasmarsh** [comment]
> 
> 
> > Scenario 2:
> > Cannot leave a variable value empty String in the csv. It takes null and not a whitespace value which was the case earlier.
> > summary,file-format,with-data,amount-rows
> > one valid email address (XLSX),xlsx,,1
> > This variable is not even set for the test:
> > And generate 'xlsx' into file 'fileName' for '1' users and profiles with data '{${with-data}}'[0.005s ]
> > Report looks like this:
> > And generate 'xlsx' into file 'fileName' for '1' users and profiles with data '{${with-data}}'[0.005s ]
> > Unable to invoke JavaStep with given arguments: generateBulkUserProfileWithData[xlsx, fileName, 1, {${with-data}}]
> > at
> > Workaround:
> > As of now based on your implementation code, I've added \ followed by a comma at the end for every line in the csv so that we can use the older implementation code:
> > summary,file-format,with-data,amount-rows
> > one valid email address (XLSX),xlsx,,1,,
> > This was working fine in 2.14-RC1
> 
> This behavior is as per design with 2.1.14+ available from 2.1.14-RC3. Refer release notes from [2.1.14-RC3](https://github.com/qmetry/qaf/releases/tag/2.1.14-RC3) `Updated CSV, XML and Excel data provider to return objects instead of Strings`

Then is there a way to pass empty whitspace string from the dataprovider ?

**Comment by raviguptasmarsh** [comment]
Also @cjayswal , about scenario 1. This looks like an issue currently.

**Comment by cjayswal** [comment]
Regarding use case 1, any of following should work:

1. Use single quote to quote String value `"Create Users":"FALSE"`
```
 Create Users is FALSE (XLSX),xlsx,1,'"Create Users":"FALSE"'
```
2. Use double quote to quote String value. in that case use `"` as escap `"` as per CSV standards

```
 Create Users is FALSE (XLSX),xlsx,1,"""Create Users"":""FALSE"""
```

**Comment by raviguptasmarsh** [comment]
> 
> 
> Regarding use case 1, any of following should work:
> 
>     1. Use single quote to quote String value `"Create Users":"FALSE"`
> 
> 
> ```
>  Create Users is FALSE (XLSX),xlsx,1,'"Create Users":"FALSE"'
> ```
> 
>     1. Use double quote to quote String value. in that case use `"` to escap `"` as per CSV standards
> 
> 
> ```
>  Create Users is FALSE (XLSX),xlsx,1,"""Create Users"":""FALSE"""
> ```


Let's say I want to pass a json from the csv:

summary,file-format,with-data,amount-rows
without Profile(CSV),csv,{"Create Users and Profiles":"TRUE","Profile External ID":"2"},1

Then in such case, if I use single quotes then, I am losing out the double quotes for the strings
{Create Users and Profiles:TRUE,Profile External ID:2}

How to escape these double quotes so that my json structure is intact ?

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
