### ISSUE TITLE
No tests are selected to run when using only "exclude" group tags in testNG suite file

### ISSUE THREAD

**Issue by raviguptasmarsh** [qmetry/qaf#336]
### QAF Version
3.0.0-RC3 (This issue seems to have been introduced in 2.1.15)

### Steps To Reproduce
Create a suite file which has only exclude tag. Like below:

> 

<test verbose="2" name="test" parallel="methods"
		thread-count="1">

		<parameter name="scenario.file.loc" value="scenarios/api/test" />

		<groups>

			<run>

				<exclude name="auditLog" />

				<exclude name="Email_Archive" />

			</run>

		</groups>

		<classes>

			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />

		</classes>

	</test>

### Expected behavior
Scenarios with groups other than these group names should run

### Actual behavior
No tests run. 
When no exclusion/inclusions are made, everything runs fine. Also, when exclude and include both are used, it behaves as expected.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

@cjayswal , are we missing something here or is this really an issue ? Please help in resolving this issue as this is a blocker for us for upgrading. 

Came across this method in MetaDataScanner:
![image](https://user-images.githubusercontent.com/48204350/82069086-79eb4280-96f0-11ea-85b7-ece3170c6922.png)

Looks like the includeMethod() of QAFMethod selector is never called when using only exclude tags in ttestNG.

Also, in my log I get the message:
![image](https://user-images.githubusercontent.com/48204350/82069234-a1daa600-96f0-11ea-945e-02a9ff282ad7.png)

However, it does not seem to work for me.

**Comment by cjayswal** [comment]
Try using [exclude property](https://qmetry.github.io/qaf/latest/scenario_metadatata_filter_include_exclude_prop.html)

**Comment by raviguptasmarsh** [comment]
@cjayswal But exclude can be different on suite to suite basis. Having single "include" "exclude" in a property file will become applicable for all the suite files. It was working fine till 2.1.14. Is it possible to resolve this ?

**Comment by cjayswal** [comment]
Refer [different ways to set property](https://qmetry.github.io/qaf/latest/different_ways_of_providing_prop.html).

**Comment by raviguptasmarsh** [comment]
@cjayswal : Can you correct me here. I am using the exclude property now in a suite configuration file and trying to exclude a group. 

<test verbose="2" name="CallBackAPI" parallel="methods"
		thread-count="1">
		<parameter name="scenario.file.loc" value="scenarios/api/callback" />
		<parameter name="exclude" value="{'groups': ['auditLog', 'Email_Archive']}" />
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
</test>



SCENARIO: test scenario
META-DATA: {"Story_ID":["0000"],"author":"Test","description":"test","groups":["auditlog","P1","SMOKE"],"Component":["CallBackAPI"],"module":"test","status":"Review"}
 


But it is still getting selected for execution.  Looks like the property is still not being set as expected.

**Comment by raviguptasmarsh** [comment]
Thanks @cjayswal . This solves my issue.

**Comment by raviguptasmarsh** [comment]
us

**Comment by Pratish89** [comment]
> Using the QAF feature to exclude tests as testNG feature is not working.

How did you solve if you have used the QAF feature to exclude tests?
