### ISSUE TITLE
Dashboard.htm file is complete blank.

### ISSUE THREAD

**Issue by vikhyat07** [qmetry/qaf#343]
### Steps To Reproduce
    1. Execute the test case in eclipse oxygen
    2. Once the execution is completed open the dashboard.htm file by right click and select the chrome browser within eclipse ide.
    

### Expected behavior
The dashboard.htm should display full report.

### Actual behavior
Dashboard.htm is opened but the the are no report points, completely blank only trends, overview and trend chart is displayed with out any data.
The same project is working perfectly fine in intellij ide and the said report will also open without any issues.

One observation, the difference between the two ide is, report launched from intellij ide will open using http://localserver:63342 where as in eclipse is opening from the project folder and not able to render the data points from test results folder.

I have checked the test results folder on both ide and there is no difference in json file data generation.

![Screenshot_20200528-174336_Chrome](https://user-images.githubusercontent.com/64070288/83119557-d562fa80-a10a-11ea-8a90-bebd2c058168.jpg)

### Is the issue reproducible on runner?

- [ ] QAS
- [yes ] Maven
- [ ] Gradle
- [ ] Ant
- [yes ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by amitbhoraniya** [comment]
If you open dashboard.html using http-server(like Intellij inbuilt do that) then it doesn't require any configuration  But if you open report using file system then following configuration required in browser.

**Microsoft Edge**

Edge browser does not require any configuration to open dashboard.

**Firefox**

1. Go to `about:config`
2. Set `security.fileuri.strict_origin_policy`:`false`

**Chrome**

Start Chrome with below command and open dashboard.htm file.
```shell
chrome.exe --allow-file-access-from-file
```

**Safari**

1. Go to `Develop` menu.
2. Select `Disable Local File Restictions` option.

**Comment by vikhyat07** [comment]
Sorry this didn't work.
I followed below Steps.
In command prompt navigated to chrome folder and ran the command which you have stated for Chrome and the browser was launched and then  from project folder, I have draged and dropped the dashboard.htm file to chrome but there's  no change again same result as stated in screen shot earlier.

In edge also produced worse result then chrome like complete grid is vanished no data.

This is very frustrating issue for eclipse when intellij is able to open this without any setting then why eclipse had to struggle?

Please let me know is there any settings required for eclipse to launch the report from the ide.

**Comment by amitbhoraniya** [comment]
@vikhyat07

Give a try to Firefox Browser. Refer this [stackoverflow](https://stackoverflow.com/questions/57049482/report-is-not-displaying-in-dashboard-html-page-for-qmetry) issue.

Above configuration should work. Still you are looking for some alternate way.... Use [Web Server for Chrome extension](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en) and open dashboard.

**Comment by vikhyat07** [comment]
Thanks for the info.
This is very secured network and the client will no allow to install any extension for Chrome.

Please let me know any solution for eclipse.

**Comment by amitbhoraniya** [comment]
As I told Give a try to firefox, if you are still looking solution for chrome start chrome with below command. Make sure all existing process of chrome is killed.
```
chrome.exe --allow-file-access-from-files
```

**Comment by amitbhoraniya** [comment]
For help and discussion post in qaf community [users group](https://groups.google.com/forum/#!forum/qaf-users).

**Comment by vikhyat07** [comment]
Yes I got the command for Chrome and tested with other command it works...but try to understand the inconvenience here..
When you run the test and are able to launch the report from intellij ide but eclipse struggles here and every run of you have to kill the process of chrome and run the command for just too check the report is a big issue.This is very secured environment and no one wants to play with disabling the security of browsers....hence

**Comment by amitbhoraniya** [comment]
Eclipse open dashboard.htm as a file protocol, while IntelliJ internally start web server for you. So it works without any configuration in IntelliJ. If you want to view dashboard using file protocol, then above configuration is must.

Is there any reason to reopen this issue ??

**Comment by shirish17** [comment]
Hi Friends,
Please suggest for me the report is still blank. I did followed all the above steps but still dahsboard.htm is not showing blank report

Steps performed:
1. Download the test project from QAF git repository
https://github.com/qmetry/qaf-blank-project-maven
Run the test project
Run got success
Open the dahsboard.htm in Chrome, Firefox browser. The report is blank

2. Run the commands in Chrome and firefox as suggested
**Chrome:** 
chrome.exe --allow-file-access-from-files

Firefox:
Go to about:config
Set security.fileuri.strict_origin_policy:false

3. Also as per report setup mentioned on git repository followed the steps:
https://github.com/infostretch/qaf-report
Download and extract into your project root. After execution or during execution open dashboard.htm in browser

Please suggest on urgent basis if any steps I missed.

**Comment by mysvasi** [comment]
hi All , 

 I am facing issue in dashboard html where report json files are generating in test-output folder but report is not seen in dashboard.html . any workaround for this. it was working fine but now only shown the old reports in dashboard.
