### ISSUE TITLE
Pick set of smoke/ focused data driven scenarios globally

### ISSUE THREAD

**Issue by AkshataShirol** [qmetry/qaf#344]
We need a support to pick set of smoke/ focused data driven scenarios globally without updating feature files while running regression

Actual: we are updating each scenarios in the feature file while we are running smoke set. Which is very difficult when the feature file increases

Expected: we need a solution to setup the smoke set for data driven scenarios at run time without updating feature file every time we run our tests.

**Comment by cjayswal** [comment]
This can be achieved using [test data filter](https://qmetry.github.io/qaf/latest/data_driven_filter.html) and [global test data configuration](https://qmetry.github.io/qaf/latest/maketest_data_driven.html#configureoverride-dataprovider) together. Let say smoke/focused/regression as test type. We can add additional column with test data, `TestType` and use appropriate to run test with only records having provide TestType by setting filter at testcase level using meta data as below for smoke:

`filter=TestType=='smoke'`

Now to apply this for all data driven tests, assuming that test data for all data driven tests has `TestType` column,

`global.testdata.filter=TestType=='smoke'`

For none data drive test cases, you can have meta-data  `TestType`  and you can add [meta-data filter](https://qmetry.github.io/qaf/latest/scenario_metadatata_filter_include_exclude_prop.html).

**Comment by cjayswal** [comment]
please provide more details and reopen if solution above doesn't address to the question.
