### ISSUE TITLE
how to integrate with Spring when use testng xml to run cucumber test case

### ISSUE THREAD

**Issue by MoonLikeSinging** [qmetry/qaf#346]
### QAF Version
> 1.21

### Steps To Reproduce
 1.  Use testng xml to run cucumber test case.
 2. In test step, Autowired the Spring data jpa repository.
     

### Expected behavior
Spring can be worked like I use testng with @test tag.

### Actual behavior
Spring didn't start.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
>  Please check the details in [stackoverflow](https://stackoverflow.com/questions/62372583/how-to-di-when-i-use-testng-xml-to-run-cucumber-test-case/62373049?noredirect=1#comment110318460_62373049).

```
@ContextConfiguration(classes = H2DBConfig.class)
public class TestByTestNg extends AbstractTestNGSpringContextTests {

    private UserRepository userRepository;

    @Autowired
    public void setUserRepository(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @Test
    public void test() {

        User u = new User();
        u.setAddress("成都");
        u.setAge(12);
        u.setCity("成都");
        u.setName("德莱文");

        userRepository.save(u);

        List<User> users = userRepository.findAll();
        for (User user : users) {
            System.out.println(user.toString());
        }
    }
}
```
If I use testng to with @test tag to run the same script, it's worked well.

**Comment by amitbhoraniya** [comment]
[Here](https://github.com/amitbhoraniya/qaf-guice-example) in sample example, I have integrated QAF with Google Guice. You can use same approach to integrate QAF with Spring.

https://medium.com/@amitbhoraniya/qaf-and-guice-754dc998c6f9

**Comment by ganeshgowtham** [comment]
> [Here](https://github.com/amitbhoraniya/qaf-guice-example) in sample example, I have integrated QAF with Google Guice. You can use same approach to integrate QAF with Spring.
> 
> 
> 
> https://medium.com/@amitbhoraniya/qaf-and-guice-754dc998c6f9
> 
> 

Thanks let me go be a try.

**Comment by ganeshgowtham** [comment]
> [Here](https://github.com/amitbhoraniya/qaf-guice-example) in sample example, I have integrated QAF with Google Guice. You can use same approach to integrate QAF with Spring.
> 
> 
> 
> https://medium.com/@amitbhoraniya/qaf-and-guice-754dc998c6f9
> 
> 

Thanks, let me give a try.

**Comment by cjayswal** [comment]
Refer [documentation](https://qmetry.github.io/qaf/latest/qaf_cucumber.html). closing inactive issue. Please post your questions in users group if required further help.
