### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by KrzysztofMadejski** [qmetry/qaf#353]
### QAF Version
3.0.0

1. Would be good to proof-read whole documentation. It's very often hard to understand. 
    One of the minor issues: You are using "In-built" or "in built" wording, it should say "built-in". 
2. I often see captions that's framing a solution, but not framing a problem. Ie. on https://qmetry.github.io/qaf/latest/maketest_data_driven.html there is a section called "Meta data". Meta data is not a problem I could have. The problem statement would be better framed as "Customize data providers". And then in the description solution could be provided "To customize data providers one can use following meta-data:"

**Comment by KrzysztofMadejski** [comment]
https://qmetry.github.io/qaf/latest/bdd-syntax.html is not using `End` to close Scenario, whereas https://qmetry.github.io/qaf/latest/scenario.html mentions it as necessary. How does it work in the end? 

When I don't specify end and I have an undefined entry such as `Then not defined` I'm not getting any error. This is weird.

**Comment by amitbhoraniya** [comment]
Its a standard and preferred way to end your scenario with `END` keyword, but its not a mandatory. If next scenario start with `SCENARIO` keyword, then framework automatically consider that first scenario is ended.

**Comment by KrzysztofMadejski** [comment]
Shouldn't end of file also signalize that the scenario has ended? Should I come with an example?

**Comment by amitbhoraniya** [comment]
Definately, If you are facing any issue or Something should work expected but not working as expected then you can create an issue and provide steps to reproduce.

**Comment by cjayswal** [comment]
@KrzysztofMadejski thanks for your time. Regarding built in and in built, i understand it is sometimes [confusing](https://ell.stackexchange.com/questions/16886/built-in-in-built-inbuilt-and-builtin-im-confused). "in-built" in documentation refers to "designed into the framework, and an integral part of framework."  Please feel free to raise a pool request for any improvement.

**Comment by cjayswal** [comment]
closing inactive thread.
