### ISSUE TITLE
Unable to Use IMethodInterceptor

### ISSUE THREAD

**Issue by shivaprasad2634** [qmetry/qaf#355]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.I am using BDD to execute my test cases, to prioritize test cases I configured a class extending ImethodInterceptor from Testng (to reOrder Test case execution).
    2.the tests still run in default order i.e., the priority order assigned after calling BDDScenarioFactory
    3.is there any way to prioritize the test cases through code? currently, I only see using parameter "priority" in metaData is the way but I want to prioritize using coding not by defining in scenario's metadata

### Is the issue reproducible on runner?

- [x] QAS
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
It dependents on your implementation. BTW, Did you registered your implementation to take effect? Make sure that you registered listener.

For help and discussion, post in qaf community [users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow](https://stackoverflow.com/questions/tagged/qaf).

**Comment by shivaprasad2634** [comment]
Hi chirag... I did register it in config file of testng under listeners. And i saw it reordering it and returned the reordered list using debug mode of eclipse. But some how the frame work is overriding my preference

**Comment by cjayswal** [comment]
For further details refer post in user group.
