### ISSUE TITLE
Not able to keep the browser open after execution of all the steps in a scenario

### ISSUE THREAD

**Issue by rizwanaabdulkalam** [qmetry/qaf#357]
### QAF Version
> 3

### Steps To Reproduce
    1. Run a scenario in feature file (QAF)
    2. All the steps gets executed
    3. After the final step, the driver gets closed automatically

Is there any way to keep the driver/browser open after the execution of all the steps?

**Comment by amitbhoraniya** [comment]
There is `selenium.singletone` qaf [application property](https://qmetry.github.io/qaf/latest/properties_list.html).  Possible value can be Tests or Methods or Groups. 

If `selenium.singletone=Methods`, then after each and every test method, driver will quit.
If `selenium.singletone=Tests`, then after execution of TestNG test, driver will quit.
If `selenium.singletone=Groups`, then after execution of group, driver will quit.

**Comment by rizwanaabdulkalam** [comment]
Hi Amit, thanks for this suggesstion. However, my requirement is something like this:
Execute all the steps > Then keep the browser open so that I can execute some steps manually 
Execute all the steps > Issue occurs > Keep the browser open so that the issue can be analysed manually

I want to prevent the browser from closing at all. Is there any way I can achieve it?
Right now I am doing this in debug mode.

Thanks
Rizwana

**Comment by cjayswal** [comment]
There are two ways:

1. Put a break point and Run in debug mode.
Or
2. Use existing web driver seesion. Create webdriver seesion and use it. Refer https://qmetry.github.io/qaf/latest/using_running_driver_session.html

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
