### ISSUE TITLE
Get warning when data field in excel is a range and contains Chinese characters.

### ISSUE THREAD

**Issue by MoonLikeSinging** [qmetry/qaf#360]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1. Prepare an excel which column's data is a range contains Chinese characters.
    2. Run the test case use this excel as test data.

### Expected behavior
If support Chinese character is better.

### Actual behavior
Get Warning:  Cannot read name ranges for -NW�N�X�O - setting to empty like this

### Is the issue reproducible on runner?

- [x] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
>Range in excel like below:
<img width="259" alt="ss" src="https://user-images.githubusercontent.com/28696706/106257798-01b1b680-6258-11eb-8716-89ed8eeb9ae0.png">

**Comment by cjayswal** [comment]
Is the problem only when using excel? Does it works with other data-providers?

**Comment by MoonLikeSinging** [comment]
> Is the problem only when using excel? Does it works with other data-providers?

Yes, should be only using excel.

**Comment by cjayswal** [comment]
@MoonLikeSinging, I tried with qaf-3.1.0-RC2 with following data and it worked fine. Will you try with qaf-3.1.0-RC2?
<img width="82" alt="image" src="https://user-images.githubusercontent.com/110619/147961795-f526cf8a-3c22-4a4d-9270-438e3a6def2f.png">

<img width="89" alt="image" src="https://user-images.githubusercontent.com/110619/147962166-29259065-0686-4d60-a0e2-fbcbef8b5012.png">

**Comment by MoonLikeSinging** [comment]
thanks， close this as fixed.
