### ISSUE TITLE
ResultUpdator will only update one entry in meta-info.json under test-results folder when do parallel suite execution

### ISSUE THREAD

**Issue by WendyZ123** [qmetry/qaf#361]
### QAF Version
3.0.0

### Steps To Reproduce
     1.Add `JsonReporter` as result updator
   
    result.updator=com.qmetry.qaf.automation.report.JsonReporter
    disable.qaf.testng.reporter=true
    qaf.json.reporter=true

    2.set suitethreadpoolsize to 3 in pom file

**Pom plugin settings:**
`<?xml version="1.0" encoding="UTF-8"?>
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <version>${mvnSurefirePlugin}</version>
   <configuration>
      <suiteXmlFiles>
         <suiteXmlFile>config/master.xml</suiteXmlFile>
      </suiteXmlFiles>
      <properties>
         <property>
            <name>suitethreadpoolsize</name>
            <value>3</value>
         </property>
      </properties>
      <reportsDirectory>${test.results.dir}</reportsDirectory>
      <systemPropertyVariables>...</systemPropertyVariables>
   </configuration>
</plugin>`

    3.in master suite, config 3 suite files: test1.xml, test2.xml, teste.xml

**master.xml**
`<suite name="master-suite" verbose="0"> 
<suite-files> 
<suite-file path="test1.xml"/> 
<suite-file path="test2.xml"/> 
<suite-file path="test3.xml"/> 
</suite-files> 
</suite>`

**test1.xml**
`<suite name="Test1 Suite" verbose="0" parallel="methods" thread-count="2">  
    <test name="test1" enabled="true">
        <groups>
            <run>
                <include name="test1"/>
            </run>
        </groups>
        <classes>
            <class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory2"></class>
        </classes>
    </test>
</suite>`
test2.xml and test3.xml are similar as test1.xml

    4.execution: run command "mvn test"

### Expected behavior
There should be three entries displayed in meta-info.json for each test suite
(My assumption based on new report folder structure)
{
  "reports": [
    {
      "name": "Test1 Suite",
      "dir": "test-results/20210129113859AM/json/test1Suite",
      "startTime": 1611887956726
    },
   {
      "name": "Test2 Suite",
      "dir": "test-results/20210129113859AM/json/test2Suite",
      "startTime": 1611887956726
    },
   {
      "name": "Test3 Suite",
      "dir": "test-results/20210129113859AM/json/test3Suite",
      "startTime": 1611887956726
    }
  ]
}

### Actual behavior
Only display one entry in meta-info.json (under test-results folder)
{
  "reports": [
    {
      "name": "Test3 Suite",
      "dir": "test-results/20210129113859AM/json/test3Suite",
      "startTime": 1611887956726
    }
  ]
}

### Is the issue reproducible on runner?
Yes

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> test case: open up a chrome browser and load github page: https://github.com/

**Comment by mysvasi** [comment]
Above issue seeing in 3.1.0 - any solution - meta-info.json
