### ISSUE TITLE
I am facing issue like session id is null.

### ISSUE THREAD

**Issue by Dakshesh123** [qmetry/qaf#362]
I am facing issue like session id is null. 
Browser is launched successfully for second scenario but not able to find elements.
Getting error like: Session ID is null, Using Webdriver after calling quite()??

_Originally posted by @Dakshesh123 in https://github.com/qmetry/qaf/issues/135#issuecomment-772713827_

**Comment by cjayswal** [comment]
Please provide details about your current implementation and steps to reproduce the issue.

**Comment by Dakshesh123** [comment]
Getting driver instance from cusalaunchURL() in HomePage class:
**getTestBase().getDriver().get(pageProps.getPropertyValue("env.baseurl")); 
driver.manage().window().maximize();**
========================================================
public class HomePage extends WFBaseTestPage {
	
	static final Log logger = LogFactory.getLog(CreateEventStep.class);
	static CreateEventPage createEvent = new CreateEventPage();
	static DBMethods dbMethods = new DBMethods();
	static EventDetailsPage eventDetails = new EventDetailsPage();
	static EventHistoryPage eventHistory = new EventHistoryPage();
	static CommonMethods commonMethods = new CommonMethods();
	static HomePage homePage = new HomePage();
	static CCDREventPage ccdrEvent= new CCDREventPage();
	static SubmitForReview submitForReview = new SubmitForReview();
	static ObjectMethods obj = new ObjectMethods();
	static ReportMethods report = new ReportMethods();

	public void  cusalaunchURL() {

		getTestBase().getDriver().get(pageProps.getPropertyValue("env.baseurl")); 
		driver.manage().window().maximize();
		waitForPageToLoad();
		obj.wait(1000);
		Reporter.log(getPageName().concat("Url Entered"));

	}
}
========================================================

TestSteps:

@QAFTestStepProvider
public class CreateEventStep extends WFBaseTestCase {

	static final Log logger = LogFactory.getLog(CreateEventStep.class);
	static CreateEventPage createEvent = new CreateEventPage();
	static DBMethods dbMethods = new DBMethods();
	static ReportMethods report = new ReportMethods();
	static EventDetailsPage eventDetails = new EventDetailsPage();
	static EventHistoryPage eventHistory = new EventHistoryPage();
	static CommonMethods commonMethods = new CommonMethods();
	static HomePage homePage = new HomePage();
	static CCDREventPage ccdrEvent= new CCDREventPage();
	static SubmitForReview submitForReview = new SubmitForReview();
	static ObjectMethods obj = new ObjectMethods();
	static AddPage addPage = new AddPage();
	
	@QAFTestStep(description="Navigate to Customer Accomodation application and Create New event through CCDR Event {0}")
	public void navigateToCustomerAccomodationApplicationAndCreateNewEventThroughCCDREvent(String str0){
		homePage.cusalaunchURL();
		homePage.clickonmainmenu();
			homePage.clickonccdrevent();
			ccdrEvent.clickoneventid(str0);
			ccdrEvent.ClickOnCreateNewEvent();
	}
}

========================================================
This is the test execution config:
![TestExecutionConfig](https://user-images.githubusercontent.com/16461898/106851676-af034f00-66dc-11eb-921f-326de3aca707.png)

========================================================
application.properties

#this is where to start the browser before navigating to the test instance.
#env.baseurl=https://cust-acco-ui.apps.tmpe-hra-n-01.cf.wellsfargo.net/ 
#env.baseurl=https://ca02729-customeraccommodations.apps.tmpe-hra-n-01.cf.wellsfargo.net/

#[resources]  
env.resources= resources/cusa-pcf
#env.resources= resources/full;resources/common
resources.load.subdirs=1
#To support mutliple locales
#load.locales=en
#default.locale=en


#set from where to load bdd step
step.provider.pkg=com.wellsfargo.www.full.steps

#[driver]
#remote.server=localhost
#remote.port=4444
driver.name=chromeDriver

webdriver.chrome.driver=./server/chromedriver.exe
#system.webdriver.ie.driver=./server/IEDriverServer.exe
#system.webdriver.edge.driver=./server/MicrosoftWebDriver.exe
#system.webdriver.gecko.driver=./server/geckodriver.exe

# Allow configuration of chrome capabilities, ex:
#chrome.additional.capabilities={"chromeOptions":{"args":["--user-agent=Mozilla/5.0 (Windows NT 6.1\\; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36 "]}}
#iexplorer.additional.capabilities={"ignoreProtectedModeSettings":true,"ignoreZoomSetting":true}
#chrome.additional.capabilities={"chromeOptions":{"args":["--start-maximized"]}}

#############ALM Integration #################

#result.updator=com.wellsfargo.eqe.integration.alm.ALMUpdator
#qc.service.url=https://ent-almqc.wellsfargo.com/qcbin
#qc.domain=PVSI
#qc.project=Deposits_MicroServices_2020
##provide test-set id or cycle id 
#qc.testset.name=2201
##Mapper implementation for test-case mapping with ALM 
#qc.testcase.mapper=com.wellsfargo.eqe.integration.alm.AlmIDFromTestNameMapper
#qc.data.source=false
#
#############QC Update properties #################

#Default wait timeout for checkpoint (assert/verify) and wait methods as well as for find element
selenium.wait.timeout=2000

selenium.success.screenshots=1
#set 1 to suppress success log, when 0 it will also show verification success message
report.log.skip.success=1

selenium.singletone=Methods

#This configuration is set to retry of test execution
retry.count=0

#[listener] qaf listeners (inclucing driver, element, step listeners) to be registered

#qaf.listeners=com.wellsfargo.esqa_core.listeners.SendKeysClearListener
#qaf.listeners=com.wellsfargo.eqe.ws.listeners.QAFWSLogger

#[web-services]
#To deal with certificate issues - do not use if required certificate authontication
#https.accept.all.cert=true

#for certificate authentication

#system.javax.net.ssl.keyStore=<keystor file> 
#required if pfx file PKCS12
#system.javax.net.ssl.keyStoreType=PKCS12 
##encrypted.system.javax.net.ssl.keyStorePassword=<base64 encrypted keystore passwrd> 
#system.javax.net.ssl.trustStore=<trust store> 
#encrypted.system.javax.net.ssl.trustStorePassword=<base64 encrypted trust store password>

#To troubleshoot and debug use following property 
#system.javax.net.debug=ssl 

#system.javax.net.ssl.keyStore=resources/certificates/idpfkeystore.pfx
##required if pfx file PKCS12
#system.javax.net.ssl.keyStoreType=PKCS12 
#encrypted.system.javax.net.ssl.keyStorePassword=aWRwZjEyMw==
#system.javax.net.ssl.trustStore=resources/certificates/idproof.service.wellsfargo.net.jks
#encrypted.system.javax.net.ssl.trustStorePassword=aWRwZjEyMw== 


############# driver name reference #########

#firefoxDriver
#iExplorerDriver
#chromeDriver
#operaDriver
#androidDriver
#iPhoneDriver
## required to set driveClass capability
#appiumDriver

## remote driver
#firefoxRemoteDriver
#iExplorerRemoteDriver
#chromeRemoteDriver
#operaRemoteDriver
#androidRemoteDriver
#iPhoneRemotDriver
## no need to set driveClass capability
#appiumRemoteDriver

## proxy settings
#system.http.proxyHost=proxy.wellsfargo.com
#system.http.proxyPort=8080


#Custom styling CSS for testNG
system.org.uncommons.reportng.stylesheet==./resources/customreportng.css

chrome.additional.capabilities={"goog:chromeOptions":{"args":[], "useAutomationExtension":false}} 
-----------------------------------------------------------------------------------

Please check this details and let me know if you want other information.

**Comment by cjayswal** [comment]
Looks like problem is because of static variable declaration in testcase. Avoid class variable in class for testcase/teststep unless it's constants or doesn't have any state. Try to keep test case as independent as possible. Tobe brief, remove all static page declaration from you test class and initialize page class as and when required. For example,

```java
public class CreateEventStep{

private static final Log logger = LogFactory.getLog(CreateEventStep.class);


@QAFTestStep(description="Navigate to Customer Accomodation application and Create New event through CCDR Event {eventId}")
public static void navigateToCustomerAccomodationApplicationAndCreateNewEventThroughCCDREvent(String eventId){
        HomePage homePage = new HomePage();
	homePage.cusalaunchURL();
	homePage.clickonmainmenu();
	homePage.clickonccdrevent();

        CCDREventPage ccdrEvent= new CCDREventPage();
	ccdrEvent.clickoneventid(str0);
	ccdrEvent.ClickOnCreateNewEvent();
}
```

I am not sure why you have all other page objects created in the home page. It should have code/ implementation specific to one page and should look like below:
```java
public class HomePage extends WFBaseTestPage {
//page specific elements

   public void  cusalaunchURL() {
	driver.get("/"); 
	driver.manage().window().maximize();
	waitForPageToLoad();
	obj.wait(1000);
	Reporter.log(getPageName().concat("Url Entered"));
   }
}
```

---------------------------------------
Furthermore you can leverage [page design features](https://qmetry.github.io/qaf/latest/page_design_concepts.html) available only with QAF. Above page implementation can be enhanced as below:

```java


public class HomePage extends WebDriverBaseTestPage<WebDriverTestPage> {
    //page elements those are identifier for the page will be used by wait for page to load.
    @PageIdentifier
    @FindBy(locator = HOME_PAGE_UNIQUE_ELE_LOC)
    private QAFWebElement homepageIdentifier;
  
   //other page specific elements
    @FindBy(locator = MAIN_MENU_LOC)
    private QAFWebElement mainMenu;
    @FindBy(locator = CCDREVENT_LOC)
    private QAFWebElement  ccdrevent;

//other page specific elements


    @Override
    protected void openPage(PageLocator arg0, Object... arg1) {
        driver.get("/");
    }
    public QAFWebElement getMainMenu() {
        return mainMenu;
    }
}


public class CCDREventPage extends WebDriverBaseTestPage<HomePage> {
//page elements those are identifier for the page will be used by wait for page to load.
    @PageIdentifier
    @FindBy(locator = HOME_PAGE_UNIQUE_ELE_LOC)
    private QAFWebElement homepageIdentifier;
  
   //other page specific elements
    @FindBy(locator = MAIN_MENU_LOC)
    private QAFWebElement mainMenu;
    @FindBy(locator = CCDREVENT_LOC)
    private QAFWebElement  ccdrevent;


    @Override
    protected void openPage(PageLocator arg0, Object... arg1) {
        parent.getMainMenu().click();
	parent.getCcdrevent().click();
    }

}

```
use launch page to launch the page.
```java
        CCDREventPage ccdrEvent= new CCDREventPage();
        ccdrEvent.launchPage(null);
```

**Comment by Dakshesh123** [comment]
Now I am getting the error like:
/**
* Auto-generated code snippet by QMetry Automation Framework.
*/
@QAFTestStep(description="Navigate to Customer Accomodation application and Create New event through CCDR Event {0}")
public void navigateToCustomerAccomodationApplicationAndCreateNewEventThroughCCDREvent(String str0){
	//TODO: remove NotYetImplementedException and call test steps
	throw new NotYetImplementedException();
}

**Comment by cjayswal** [comment]
This looks more related to step and step provide package configuration. Check and ensure you have correct configuration of step provider package. 
Right place to post "how to" question or discussions is [users group](https://groups.google.com/forum/#!forum/qaf-users) or  [stackoverflow with qaf tag](https://stackoverflow.com/questions/tagged/qaf).

**Comment by SelHet** [comment]
I am also having same problem, while executing more than one tests. All tests execute fine, if ran individually. But when executing all tests together only first test gets executed and the in the second test driver gives up the browser Session ID after "get" command of CommonStep while try to locate a webelement on the page. I observed this behavior only when I extend "WebDriverTestCase" class in my test class.
FYI : I am not using BDD. Its all java classes and methods.
Versions: Qmetry : 3.1.0 & Selenium 4

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
