### ISSUE TITLE
Can we invoke a standalone qaf project or test run config xml from jenkins build ?

### ISSUE THREAD

**Issue by BhargavGvya** [qmetry/qaf#365]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [x] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Yes you can run from Jenkins or any other continuous integration tool.
Please post your question in users group.
