### ISSUE TITLE
Compatibility issue between QAF 3.0.0 and Cucumber 6.0.0

### ISSUE THREAD

**Issue by phTrung** [qmetry/qaf#368]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    Run Cucumber scenario with an excel data provider

### Expected behavior
The test should run has many times as there are sets of data

### Actual behavior

Exception in thread "main" java.lang.NoClassDefFoundError: io/cucumber/core/gherkin/Location

In Cucumber version 6, the Gherkin folder is at the same level as the core. QAF simply lacks compatibility with Cucumber.

### Is the issue reproducible on runner?

- [ ] QAS
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Feature: Create and Delete Group
  @smoke
  @dataFile:src/test/resources/features/UserData.xls
  @sheetName:Groups
  Scenario: Create New User Group
    Given I click on create group button
    When The create user group pop up appears
    Then I enter the group name ${Group Name}
    Then I enter the group description ${Description}
    Then I add user to the group
    Then I click on the create group button
    And The group must be created with a confirmation message

**Comment by cjayswal** [comment]
Thanks for reporting. I hope you are using [qaf-cucumber](https://github.com/qmetry/qaf-cucumber). If so this issue needs to move to qaf-cucumber repository. 

Regarding cucumber support qaf-cucumber tested with and supports cucumber 5.1.3. It is unfortunate that cucumber team changes package structure again and again without considering compatibility which impacts to end users.

**Comment by phTrung** [comment]
Thank you for your reply, in this case I will recreate the issue to qaf-cucumber.
