### ISSUE TITLE
Can We integrate WebDriver Manager ?

### ISSUE THREAD

**Issue by vivek-driscolls** [qmetry/qaf#370]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Yes, you can call appropriate method in `beforeSuite` of TestNG listener or `beforeInitialize` of driver listener. for example:
```
        WebDriverManager.chromedriver().setup();
```
You didn't provided any details. Are you facing any issue? If this is general question, it is recommended to post in [users group](https://groups.google.com/g/qaf-users) or in [stack-overflow](https://stackoverflow.com/questions/tagged/qaf) with qaf tag.

**Comment by cjayswal** [comment]
Duplicate #293

**Comment by cjayswal** [comment]
Feature will be available in 3.0.1 release. It can be tried with [ 3.0.1-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/qmetry/qaf/3.0.1-SNAPSHOT/).
