### ISSUE TITLE
Hi , I using Winappdriver  with QAF - BDD . where to write customize teardown() method which should execute after each scenario ? please information with example.

### ISSUE THREAD

**Issue by AvinashKaran** [qmetry/qaf#371]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Are you facing any issue? If this is general question or required help, it is recommended to post with details in [users group](https://groups.google.com/g/qaf-users) or in [stack-overflow](https://stackoverflow.com/questions/tagged/qaf) with qaf tag.

**Comment by AvinashKaran** [comment]
Yes Chirag , the issue is , while using qaf-bdd , inbuilt teardown()[execute after each scenario ] method close only web browser after each scenario. But , for Winapp driver it does not close windows app . So I want to close windows app after each scenario ?
What do we achieve in qad driver ?

**Comment by cjayswal** [comment]
Make sure you have provided property `selenium.singletone=Methods`. If your test implementation is in Java then test class needs to extend `WebDriverTestCase`.

It is recommended to post questions with details (your current configuration, relevant code, execution logs, etc) in [users group](https://groups.google.com/g/qaf-users) or in [stack-overflow](https://stackoverflow.com/questions/tagged/qaf) with qaf tag.

**Comment by AvinashKaran** [comment]
Below issue is also posted in users group 

I am using QAF-BDD with winappdriver to test windows based application. ( Ex. notepad etc..)
below is the code sample.

Requirement,(What I need ) : When we execute below suite , after each scenario notpad should be closed.
basically current session should be quit . So, to do that I need to write session.quit(). 
Is there any such kind of hook like cucumber having @After which trigger after each scenario ?
Note:  " selenium.singletone=Methods " works fine for Web application.

testNG-notpad.xml
<suite name="Suite" parallel="false" thread-count="4" verbose=1>
        <test name="notepad_test">
              <Parameter name="scenario.file.loc" value="scenario/AviTest.bdd" />
              <Parameter name="step.provider.pkg" value="src.steps" />
        <groups>
            <run>
               <include name="WindowsApp">
             </run>
          </groups>

     <classes>
           <class name = com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
      </classes>
 </test>
</suite>
         


feature file : AviTest.bdd
-----------------------------------------
SCENARIO: Verify new option in File Menu in notepad
META-DATA: {"DESCRIPTION": "Verify new option", "Groups" : [ "WindowsApp"]}
Given note pad opened
When file menu selected
Then verify new option 
END

SCENARIO : second scenario
META-DATA: {"DESCRIPTION": "Verify secondScenario", "Groups" : [ "WindowsApp"]}
Given second given statement
When second when statement
Then verify statment
END


Step definition : notepadStep.java
------------------------------------------------------
class notepadStep{
WindowsDriver session = null; 

@QAFTestStep(description="note pad opened")
public void notepadOpened(){
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("app,","C:\\Windows\\System32\\notepad.exe);
session = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);

System.out.println("Given Statement");
}
@QAFTestStep(description=" file menu selected")
public void fileMenuSelected(){
System.out.println("When statement");
}

@QAFTestStep(description="  verify new option")
public void verifyNewOption(){
System.out.println("Then Statment")'
}

}

**Comment by cjayswal** [comment]
Refer #227 and [post in qaf-users](https://groups.google.com/g/qaf-users/c/OCC5b60itlQ/m/BuEnwn43AQAJ) group.

**Comment by AvinashKaran** [comment]
Thank you Chirag I'll try it. Thanks a lot for support. 

Thanks,
Avinash.
