### ISSUE TITLE
How to read web table rows and columns share me sample code 

### ISSUE THREAD

**Issue by ssuneel** [qmetry/qaf#373]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Are you facing any issue? If this is general question or required help, it is recommended to post with details in [users group](https://groups.google.com/g/qaf-users) or in [stack-overflow](https://stackoverflow.com/questions/tagged/qaf) with qaf tag.
