### ISSUE TITLE
Can we use "and" when we add the tags in testNG files? For BDD2 or for Gherkin based approach

### ISSUE THREAD

**Issue by kulin24** [qmetry/qaf#376]
### QAF Version - 3.0.0
> Note: only the latest version is supported

### Expected behavior
The user wants to include two combinations of the tags, for example, the user wants to mention that @tag1 and  @tag2, scenarios that have both of these tags should be picked up for execution. Is this possible to filter out using this condition?

**Comment by cjayswal** [comment]
Refer [meta-data filter](https://qmetry.github.io/qaf/latest/scenario_metadatata_filter_include_exclude_prop.html) documentation. 
It is recommended to post questions with details (your current configuration, relevant code, execution logs, etc) in [users group](https://groups.google.com/g/qaf-users) or in [stack-overflow](https://stackoverflow.com/questions/tagged/qaf) with qaf tag.

**Comment by kulin24** [comment]
Sure, will do that going forward, thanks a lot @cjayswal. Appreciate your quick response.
