### ISSUE TITLE
Error message is displaying as "code":"CO.INVALID_API_KEY","message":"Invalid API key."while trying to  publish results in qmetry 

### ISSUE THREAD

**Issue by SaranyaRajendran01** [qmetry/qaf#379]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by SaranyaRajendran01** [comment]
Please let me know if any access has to be provided for Qmetry API key if we are publishing results in qmetry from CI-CD integration
![QmetryError](https://user-images.githubusercontent.com/73221573/129719770-0915c18f-c25d-44d4-8148-b70bb23fdf74.PNG)

**Comment by cjayswal** [comment]
Please contact to qmetry support team for any query related to qmetry test management tool.

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
