### ISSUE TITLE
Test case specific data driven parallelism property does not working

### ISSUE THREAD

**Issue by hirengit** [qmetry/qaf#38]
**Test written in java**
`package com.p1;

import java.util.Map;

import org.testng.annotations.Test;

import com.qmetry.qaf.automation.testng.dataprovider.QAFDataProvider;
import com.qmetry.qaf.automation.ui.WebDriverTestCase;

public class TestDataDrivenParallel extends WebDriverTestCase {

```
@QAFDataProvider(dataFile = "resources/logindata1.txt")
@Test(groups = { "SMOKE" }, description = "Google Search")
public void test1(Map<String, String> data) {
    System.out.println(Thread.currentThread().getId());
}

@QAFDataProvider(dataFile = "resources/logindata2.txt")
@Test(groups = { "P1", "P2" }, description = "Yahooo Search")
public void test2(Map<String, String> data) {
    System.out.println(Thread.currentThread().getId());
}
```

}
`

**property setting**
global.datadriven.parallel = 1
test1.parallel=0

**Comment by cjayswal** [comment]
It will required to have to separate data-provider with and without parallel and attach dynamically.
