### ISSUE TITLE
Facing some issue - Unknown option: -surefire.testng.verbose

### ISSUE THREAD

**Issue by SurendraRedd** [qmetry/qaf#385]
### QAF Version
> Note: only the latest version is supported

### Is the issue reproducible on runner?
yes

- [x] QAS
- [x ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Refer the screenshot attached in the issue
![image](https://user-images.githubusercontent.com/37290660/137540129-f6601f2b-eea3-4b9d-a6c8-00385c55fab6.png)

**Comment by cjayswal** [comment]
Provide more details, share the steps to reproduce  the issue.

For QAS issue/support visit [QAS support portal](https://qmetrysupport.atlassian.net/servicedesk/customer/portal/1)
