### ISSUE TITLE
How to update Log4j from 1.2.17 to 2.17  please guide me on this

### ISSUE THREAD

**Issue by ssuneel** [qmetry/qaf#398]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
User can use whatever version for that dependency library in there project.  For log4j, **minimum supported version** by QAF  is `1.2.14`. If anybody want to use log4j 2.x they can use it at project level!

Normally when you provide higher version of  any library lower version automatically ignored by dependency management tool. If group and artifact name changed you can add exclusion. For example in maven:

```
<dependency>
   <groupId>com.qmetry</groupId>
   <artifactId>qaf</artifactId>
   <version>${qaf.version}</version>
   <exclusions>
      <exclusion>
         <groupId>log4j</groupId>
         <artifactId>log4j</artifactId>
      </exclusion>
   </exclusions>
</dependency>
<!-- https://mvnrepository.com/artifact/org.apache.logging.log4j/... -->
<dependency>
   <groupId>org.apache.logging.log4j</groupId>
   <artifactId>log4j-core</artifactId>
   <version>2.16.0</version>
</dependency>
```
