### ISSUE TITLE
Automation file which needs admin access

### ISSUE THREAD

**Issue by ganeshgowtham** [qmetry/qaf#400]
Hi Chirag

I am facing issues while automating the host file in windows operating system using the Selenium.

I want to update host file in c:\windows\system32\drivers\etc which needs local admin rights

Tried following things, But in vain.

1. Tried Commons VFS libarry from Java to authenticate by passing local admin rights but getting access denied while overriding content
2. We are getting User access Control pop up which hides all the Applications from machine while updating content manually  and  when tried through Robo keys and other windows automation tools like UFT but unable to move focus or control to that pop up
3. we tried to open command prompt as a admin and then tried to open particular file with admin rights but not accepting admin credentials through command line

**Comment by cjayswal** [comment]
This is not right place for Q & A. It is recommended to post questions with details in [users group](https://groups.google.com/g/qaf-users) or in [stack-overflow](https://stackoverflow.com/questions/tagged/qaf) with qaf tag.

**Comment by cjayswal** [comment]
closing inactive issue. Please post your questions in users group if required further help.
