### ISSUE TITLE
How to use TestNG ITestContext in a test script?

### ISSUE THREAD

**Issue by zarashima** [qmetry/qaf#402]
It looks like that when passing ITestContext in the test method following with testNG convention, like: 

`public void testWithGivenWhenThen(ITestContext context)`

Then qaf will treat this context parameter like test data, and will throw out: `java.lang.RuntimeException: java.lang.RuntimeException: No data provider found` error

So is there anyway I can use testNG context in this case?

Thanks

**Comment by cjayswal** [comment]
you can access from configuration manager using `ApplicationProperties.CURRENT_TEST_CONTEXT.key`

```
import static com.qmetry.qaf.automation.core.ConfigurationManager.getBundle;

@Test
public void testWithGivenWhenThen() {
   ITestContext context = (ITestContext) getBundle().getObject(ApplicationProperties.CURRENT_TEST_CONTEXT.key);
   ...
}
```

**Comment by zarashima** [comment]
Thanks for your answer. Get it working
