### ISSUE TITLE
PoiExcelUtil.getTableDataAsMap returning RuntimeException: Lable Data2 for ending data range not found in sheet DataTable when all Data Key starts from same column

### ISSUE THREAD

**Issue by patelvinay11** [qmetry/qaf#404]
### Steps To Reproduce
    1. call PoiExcelUtil.getTableDataAsMap("testdata.xlsx","Data2","DataTable");
    2. use [testdata.xlsx](https://github.com/qmetry/qaf/blob/master/test/resources/testdata.xlsx)
    3. update testdata.xlsx to start the data for Data2 from C19 or B19 or A19, instead of I19.
    4. Run a test.

### Expected behavior
return data object

### Actual behavior
line 242: Cell tableEnd = findCell(sheet, tableName, startCol + 1, startRow + 1); returning null, so it's throwing RuntimeException: Lable Data2 for ending data range not found in sheet DataTable
Note: test is working only if data starts from any column after D19 only.
I think fix is required in findCell method in PoiExcelUtil class, as Data sheet can start of any column should not impact the outcome.

### Is the issue reproducible on runner?

- [] QAS
- [ ] Maven
- [ ] Gradle
- [] Ant
- [x] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Not required as code is already available to debug in qaf.

**Comment by cjayswal** [comment]
Most probably it's missing label to indicate range start and range end for [data-table](https://qmetry.github.io/qaf/latest/excel.html#excel-data-table). You need to have label for both start and end cell. share  testdata.xlsx (with dummy data) you are using.

**Comment by patelvinay11** [comment]
@cjayswal : I tried that with a little change as mentioned in step 3 of reproduce steps.
Attaching the file that i am trying for you so you can debug.
[testdata.xlsx](https://github.com/qmetry/qaf/files/8052207/testdata.xlsx)

Note: test is working only if data starts from any column after D19 only.

**Comment by patelvinay11** [comment]
@cjayswal: Also, wanted to know how I can use my custom data provider class with CucumberScenarioFactory. I am able to use my custom data provider with BDD2TestFactory2 by adding @dataProvider and @dataProviderClass in feature file but same is not working with CucumberScenarioFactory.

**Comment by cjayswal** [comment]
Thanks for reporting issue. I am able to reproduce issue with provided data file.
Regarding custom data provider, it is not supported with `CucumberScenarioFactory`.

**Comment by patelvinay11** [comment]
@cjayswal : Thanks Chirag. Since custom data provider is not supported with CucumberScenarioFactory. Please help expedite the fix for this.

**Comment by cjayswal** [comment]
You can use `BDD2TestFactory2`. If you have step implemented using cucumber, it is supported with [qaf-cucumber](https://github.com/qmetry/qaf-cucumber#using-qaf-cucumber-with-qaf-bdd-runner) dependency. When using `BDD2TestFactory2`, If you don't have cucumber step implementation, you don't need any cucumber specific dependency. 

If you are dependent on cucumber runner for one or other reason, you also can have mix of both, that means few feature file configured to run with `BDD2TestFactory2` and other can be configured to run with cucumber runner using `CucumberScenarioFactory`.
