### ISSUE TITLE
my tests suite are not running from xml file where seeing the error messages and same issue in jenkins also - [ERROR] com.qmetry.qaf.automation.step.client.TestNGScenario.getMethod()Ljava/lang/reflect/Method

### ISSUE THREAD

**Issue by mysvasi** [qmetry/qaf#405]
### QAF Version 3.0.0 and TestNG 7.4.0
> Note: only the latest version is supported

### Steps To Reproduce
    1. run the test through suite.sml or jenkins 
    2. seeing the error 
     **[ERROR] com.qmetry.qaf.automation.step.client.TestNGScenario.getMethod()Ljava/lang/reflect/Method;**

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Please help me to resolve this issue

**Comment by cjayswal** [comment]
Try with  qaf latest release `3.0.1` or `3.1.0-RC2`

**Comment by cjayswal** [comment]
@mysvasi will you try using [3.1.0](https://mvnrepository.com/artifact/com.qmetry/qaf/3.1.0) and update the issue with details if not resolved?
