### ISSUE TITLE
Cannot run Chrome Headless in QAF 3.1

### ISSUE THREAD

**Issue by streamlinxSDET** [qmetry/qaf#407]
### Steps To Reproduce
    1. Setup project using QAF 3.0 using chrome driver (using Ant + Ivy) 
    2. set this property: chrome.additional.capabilities={\"chromeOptions\":{\"args\":[\"--headless\",\"--window-size=1920,1080\"]}}
    3. Test runs without issue and chrome run headless
    4. Switch to QAF 3.1
    5. Run test

### Expected behavior
Chrome runs headless in QAF 3.1 honoring capabilities as outlined here: https://qmetry.github.io/qaf/latest/setting_driver_capabilities.html

### Actual behavior
`chrome.additional.capabilities` appear to be ignored

### Is the issue reproducible on runner?

- [ ] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Additional notes:
* Running on Linux
* Guessing the change in QAF 3.0.1 to utilize https://bonigarcia.dev/webdrivermanager/ introduced the issue
* looks like by default `manage.driver.execute=true`. This this overrides the specific chrome driver I have installed: `webdriver.chrome.driver = lib/chrome/99.0.4844.51/linux/chromedriver` and invokes downloading and setting up driver.
* Setting `manage.driver.execute=false` gives this error and running:
```
Unable to Create Driver Instance for chrome: java.lang.NoSuchMethodException: org.openqa.selenium.chrome.ChromeDriver.<init>(java.net.URL, org.openqa.selenium.Capabilities)
   [testng] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
   [testng] System info: host: 'nimitz-2', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-35-generic', java.version: '1.8.0_312'
   [testng] Driver info: driver.version: unknown
```
* Tested QAF 3.1 with selenium 3.141.59 and 4.0.0. But that did not resolve the issue either.
* To repeat, using QAF 3.0 runs without issue. Switching to QAF 3.1 introduces the regression.
* My guess is this set of changes introduced the issue (QAF 3.0.1): https://github.com/qmetry/qaf/commit/54e87842f0ce7860d9696ae9c87429aed030b43d

**Comment by cjayswal** [comment]
did you tried setting chrome driver with system prefix? For instance instead of  `webdriver.chrome.driver` try setting property`system.webdriver.chrome.driver`

**Comment by streamlinxSDET** [comment]
Results of testing:
* QAF 3.0.0 using `webdriver.chrome.driver` and `system.webdriver.chrome.driver` both work without issues. `chrome.additional.capabilities` is honored and I am able to run QAF tests headless
* Testing using QAF 3.1.0: using either `webdriver.chrome.drive` or `system.webdriver.chrome.driver` gave the same result: `chrome.additional.capabilities` was ignored and the chrome browser was not opened headless.

So this did not resolve the issue.

**Comment by cjayswal** [comment]
Below works fine for me with qaf `3.1.0`. 
```
chrome.additional.capabilities={"goog:chromeOptions":{"args":["--headless","--window-size=1920,1080"]}}
```
Capabilities value is depends on driver version, in my case 
browserVersion:100.0.4896.127
ChromeDriver: 100.0.4896.60

**Comment by streamlinxSDET** [comment]
Thank you, @cjayswal ! That was the final piece to solve the issue for me.

Here is a Summary of changes needed for anyone else that may be struggling with a similar issue.

In QAF 3.0.0. This config allows me to run headless and use a driver I installed locally:
```
webdriver.chrome.driver = <path to library>
chrome.additional.capabilities={"chromeOptions":{"args":["--headless","--window-size=1920,1080"]}}
```
But in QAF 3.1.0 to get everything working headless with a local driver, I needed this configuration:
```
# Turn off fetching driver
manage.driver.executable=false

# Added 'system' namespace
system.webdriver.chrome.driver = <path to library>

# Added 'goog:' prefix
chrome.additional.capabilities={"goog:chromeOptions":{"args":["--headless","--window-size=1920,1080"]}}
```
I tested several variation of these settings and I needed all three of these changes to get QAF 3.1.0 working headless for the 99.0.4844.51 version of chromedriver
