### ISSUE TITLE
New test execution entry(job id) is not added for each execution in Test Execution list on left pane in QMetry Report

### ISSUE THREAD

**Issue by samafs19** [qmetry/qaf#408]
### QAF Version: LATEST
> Note: only the latest version is supported

### Steps To Reproduce
    1. Download and import a sample QAF blank maven project from Git (https://github.com/qmetry/qaf-blank-project-maven)
    2. Run the testrun_config.xml as TestNG (couple of times)
    3. Open the report

### Expected behavior
Each run is expected to create a new list/entry on left pane (new job id)

### Actual behavior
All the tests are displayed underneath old job id (same old execution) though they are from different run/execution.

### Is the issue reproducible on runner? I've used Maven as the sample project.

- [x] QAS
- [x] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
qaf-project-maven-master\config\testrun_config.xml
![image](https://user-images.githubusercontent.com/102273765/159836262-57204c77-8e66-42f9-8245-0dfa293ab4f2.png)
![image](https://user-images.githubusercontent.com/102273765/159836394-627bb553-83ff-4eda-824d-5fde77eba0f1.png)

**Comment by samafs19** [comment]
I've executed same test case as TestNG test via config xml three times and in QAF Demo (job id 3) all three test runs were displayed.
Expected is one job id to be created for each test run where the details show all test cases underneath that testNG run.

**Comment by samafs19** [comment]
Underneath 'test-results' folder, I see only 1 folder is created with date and time of first execution and 'meta-info.json' also has first test execution entry.
This may be the reason that I'm not able to see different job ids in report result for each run.
What can be done to fix it? Attaching the pom which is in the sample project and I have been using.
[pom.zip](https://github.com/qmetry/qaf/files/8347000/pom.zip)

**Comment by cjayswal** [comment]
It depends how you are executing! 
If you are using maven and running from IDE as TestNG test, maven environment variables doesn't get updated for each execution. In such case either run as maven test or Check TestNG IDE plugin preference and uncheck maven configuration parameters to TestNG.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/110619/163843897-6c128a35-b190-43d6-a007-6aca1aa630d7.png">

**Comment by samafs19** [comment]
Thank you... it worked as expected now!
