### ISSUE TITLE
include tag in config xml is not working 

### ISSUE THREAD

**Issue by samafs19** [qmetry/qaf#409]
### QAF Version - LATEST
> Note: only the latest version is supported

### Steps To Reproduce
    1. Download and import a sample QAF blank maven project from Git (https://github.com/qmetry/qaf-blank-project-maven)
    2. Update the config by adding include tag as below -
         <suite name="QAF Demo" verbose="0">
	   <test name="BDD Test" enabled="true">
	    <parameter name="step.provider.pkg" value="com.qmetry.qaf.example.steps"></parameter>
	    <parameter name="scenario.file.loc" value="scenarios/suite1.feature"></parameter>
		<groups>
			<run>
				<include name="Smoke"></include>
			</run>
		</groups>	
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory2"></class>
		</classes>
	   </test>	
      </suite>
    4. Run it as TestNGTest

### Expected behavior
xml is expected to execute the smoke test tag testcase

### Actual behavior
Nothing is being executed (attached console output)

### Is the issue reproducible on runner? I've used sample maven qaf project

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
![image](https://user-images.githubusercontent.com/102273765/159921469-04f9a541-bd80-4d23-8276-40057b89f79c.png)
![image](https://user-images.githubusercontent.com/102273765/159921584-aa38be2b-6755-4b72-ab50-7af399e641bb.png)

**Comment by samafs19** [comment]
If I remove the include tag then it works as expected. 
However, my feature file can have multiple scenarios and I may want to just include couple of them then this use-case will not work

**Comment by Pratish89** [comment]
try as parameter

<parameter name="include" value="{'groups':['Smoke',}" />

**Comment by samafs19** [comment]
It worked... Thank you!
