### ISSUE TITLE
Gherkin parser does does not include last step in scenario

### ISSUE THREAD

**Issue by mitchellhwright** [qmetry/qaf#41]
Looks like the AbstractScenarioFileParser is not adding the last step of a scenario in a feature file.  I believe line 264 in that class is the culprit.

In the following feature file the last step (*Then I ask it to say hi") is not included in the list of steps that the parseScenario() function creates.  It looks like the do while loop always terminates 1 step too early.

Feature: Switch Frame Test
  Scenario: Switch Frame Test
    Given I open browser to webpage "http://nunzioweb.com/iframes-example.htm"
    Then "iframe1" should exist
    Then I switch to "iframe1" frame by element
    Then I click on "iframe1.play"
    Then I ask it to say hi

**Comment by cjayswal** [comment]
@mitchellhwright can you provide qaf build details you faced this issue with?

**Comment by mitchellhwright** [comment]
I believe it happens with both 2.1.8 and 2.1.9.  The do while loop logic is similar for both.

**Comment by cjayswal** [comment]
qaf-2.1.8 doesn't have gherkin factory it must be one of 2.1.9RC-1, 2.1.9RC-2, 2.1.9RC-3 or 2.1.9

**Comment by mitchellhwright** [comment]
True.  Well it definitely happens in 2.1.9
