### ISSUE TITLE
How to execute scripts in different environments (i.e QA and UAT) please share me some samples 

### ISSUE THREAD

**Issue by ssuneel** [qmetry/qaf#412]
Hi,

Can someone share with me samples of how to execute scripts in different environments?

I have two properties files (i.e **env. properties** under **env1 & env2** under **resource-> environment** folder)
![image](https://user-images.githubusercontent.com/56713430/163326553-c5bb1130-f3fe-4da3-9f5e-fc6fb9f584d9.png)

Env1:-
env.properties - files contains
URL =  https://googleUAT.com/
UserName =qaUser@xxx.com
pwd = test123

Env2:-
env.properties - files contains
URL =  https://googleTST.com/
UserName =UatUser@xxx.com
pwd = test12342

when I try to user below line in XML file
parameter name="env.resources" value="resources/common;resources/env1" /

By default its always take env2 file values.

Please guide me how to processed further

**Comment by cjayswal** [comment]
Refer documentation [managing resources](https://qmetry.github.io/qaf/latest/managing_resources_for_different_env.html) and [configuration](https://qmetry.github.io/qaf/latest/creating_configuration_file.html).
In above case, it looks you are providing wrong path. From screen shot path is `resources/environment/env1` not `resources/env1`.

**Comment by cjayswal** [comment]
Closing as inactive
