### ISSUE TITLE
Can't start multiple drivers in multiple threads

### ISSUE THREAD

**Issue by ly061** [qmetry/qaf#414]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1. Login to Baidu
    2. Search something
    3. Set thread-count = 5
    
    

### Expected behavior

Each thread should initial one driver. For example, i have 3 cases, should start 3 drivers.

### Actual behavior

All the thread use the same one driver (it means only start 1 driver)

### Is the issue reproducible on runner?

- [x] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
![image](https://user-images.githubusercontent.com/45733102/167305704-6c75aa41-a77c-4628-bf2e-46c69153d4e8.png)
![image](https://user-images.githubusercontent.com/45733102/167305732-faf636d7-cf0a-414a-8407-dbc326e50482.png)
![image](https://user-images.githubusercontent.com/45733102/167305744-8df4f2b6-4d86-428c-9f73-c073a91ffe99.png)
![image](https://user-images.githubusercontent.com/45733102/167305813-43260ee6-ad40-4a69-b5be-41b297d9566d.png)

**Comment by cjayswal** [comment]
Refer [answer](https://stackoverflow.com/a/72167350/861594) to same question.
