### ISSUE TITLE
Testng Emailable report has missing details when MessageTypes is Pass or Info

### ISSUE THREAD

**Issue by nakulkhargonkar** [qmetry/qaf#419]
### Steps To Reproduce
    1. Updated ivy file from qaf rev="2.1.14" to 
    <dependency org="com.qmetry" name="qaf" rev="latest.integration" />
   <dependency org="com.qmetry" name="qaf-support" rev="latest.integration" /> 
   as shown in  https://github.com/qmetry/qaf-blank-project

    2. After running a test case the Messages Section in emailable report is missing. Where as Exception Section is present 

### Expected behavior
![image](https://user-images.githubusercontent.com/48121769/173334070-b6a71e56-2aa8-47ba-aff6-d8a675092d44.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/48121769/173334618-794385f1-3cf7-4840-81ac-b328a423d93d.png)

### Is the issue reproducible on runner?
- [x] Ant

**Comment by cjayswal** [comment]
you can try setting `report.log.testngoutput` property. It has default value `false`. 
```
report.log.testngoutput=true
```
Relates to #329

**Comment by nakulkhargonkar** [comment]
Thanks @cjayswal. 
It worked well.
