### ISSUE TITLE
StackOverFlow issue when relative elements are used in Selenium 4

### ISSUE THREAD

**Issue by ksitwala-perfecto** [qmetry/qaf#427]
### QAF Version - 3.1.0
> Note: only the latest version is supported

Other versions used - 
**Selenium - 4.1.0**

### Steps To Reproduce
    1. The Selenium 4 relative element methods are throwing StackOverFlowError, even after using Underlying RemoteWebDriver. Reference Code - 
```
                 RemoteWebDriver driver = (RemoteWebDriver) new WebDriverTestBase().getDriver().getUnderLayingDriver();
		WebElement eleRelative = driver.findElement(By.id("login_signup_btn"));
		WebElement login = driver
				.findElement(with(By.id("login_login_btn")).toLeftOf(eleRelative));
```

    3. StackOverFlow error is seen on the last findElement command where we use toLeftOf() method.
    

### Expected behavior
The relative element should work and there is no dependency issue as it works within QAF project if we use a Java template code and create a normal RemoteWebDriver. 

### Actual behavior

StackOverFlow Exception is being thrown if we use relative elements code. 

### Is the issue reproducible on runner? I believe it should be but have not tried. We have used Gherkin Factory runner.

- [] QAS
- [x] Maven
- [ ] Gradle
- [] Ant
- [x] Eclipse

We even tried overriding the QAFExtendedWebDriver code as you have commented, for reference - 
`private Response executeWithoutLog(CommandPayload payload) {
		// in order to compatibility with 3.x, compiled with 3.x. so method from 4.x super class will not be available. 
		// Once min version set to 4.0 we don't need executeSuper method.

		Response response = super.execute(payload);
               // Response response = executeSuper(payload);
		
		if (response == null) {
	        return null;
	    }
		Object value = getQafElementConverter().apply(response.getValue());
	    response.setValue(value);
		return response;
	}`

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
 RemoteWebDriver driver = (RemoteWebDriver) new WebDriverTestBase().getDriver().getUnderLayingDriver();
		WebElement eleRelative = driver.findElement(By.id("login_signup_btn"));
		WebElement login = driver
				.findElement(with(By.id("login_login_btn")).toLeftOf(eleRelative));

**Comment by cjayswal** [comment]
Looks like issue conflicting json library. 
I added below dependency and it worked without issue.

```
<!-- https://mvnrepository.com/artifact/org.json/json -->
<dependency org="org.json" name="json" rev="20220320"/>

```

**Comment by ksitwala-perfecto** [comment]
Thanks, @cjayswal - I have tested and confirmed that it works by changing the dependency version of this json library, appreciate your quick response.
