### ISSUE TITLE
POM file in distribution for maven has dependency misspelled

### ISSUE THREAD

**Issue by patelakhil** [qmetry/qaf#43]
Hi,

We are trying to add the QAF as maven dependency and the running the project is failing as the following dependency is misspelled:
<dependency>
      <groupId>javax.media</groupId>
      <artifactId>jai-core</artifactId>
      <version>1.1.3</version>
      <scope>compile</scope>
    </dependency>

Actually the jai-core is "jai_core" on maven central:
http://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/

We are getting following error:
The following artifacts could not be resolved: javax.media:jai-core:jar:1.1.3, com.sun.media:jai-codec:jar:1.1.3: Could not find artifact javax.media:jai-core:jar:1.1.3 in qaf (https://qmetry.github.io/qaf/dist) -> [Help 1]

Is there any workaround - our team is blocked.

**Comment by cjayswal** [comment]
Add repository entry from where artifacts can be found, in this case you need to add following repository in your pom:

``` xml
<repository>
			<id>jai</id>
			<url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases</url>
</repository>
```

Please refer [pom from blank maven project](https://github.com/qmetry/qaf-blank-project-maven/blob/master/pom.xml).

**Comment by cjayswal** [comment]
marking as invalidate as dependency not misspelled in pom.

**Comment by patelakhil** [comment]
Actually this kind of resources should be part of qaf.pom.

**Comment by cjayswal** [comment]
it was marked invalid as dependency not misspelled in pom.
