### ISSUE TITLE
Edge IE mode not working as expected in Qmetry

### ISSUE THREAD

**Issue by ashoksagi** [qmetry/qaf#435]
### QAF Version 3.1.0
> Note: only the latest version is supported

### Steps To Reproduce
    1. I want to run edge ie mode using qmetry. We are getting wired blank white IE page being opened when we click on login button in our application. Same website works fine when i executed it without qmetry. 
    2.below code works fine in stand alone. 
System.setProperty("webdriver.ie.driver", Global.WINDOWS_USER_HOME + "\\.cache\\selenium\\IEDriverServer\\win64\\" + IEversion + "\\IEDriverServer.exe");
										InternetExplorerOptions iExplorerOptions = new InternetExplorerOptions();
										iExplorerOptions.setCapability(InternetExplorerDriver.FORCE_CREATE_PROCESS, true);
										iExplorerOptions.setCapability(InternetExplorerDriver.IE_SWITCHES, "-private");
										iExplorerOptions.attachToEdgeChrome();
										iExplorerOptions.ignoreZoomSettings();
										iExplorerOptions.setCapability("ignoreProtectedModeSettings", true);
										iExplorerOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
						return new InternetExplorerDriver(new BrowserFactory().setInternetExplorerOptions());
    
Code used for Qmetry
	String IEversion = downloadWebDriver();
					System.setProperty("webdriver.ie.driver", Global.WINDOWS_USER_HOME + "\\.cache\\selenium\\IEDriverServer\\win64\\" + IEversion + "\\IEDriverServer.exe");
					
					ConfigurationManager.getBundle().setProperty("iexplorer.additional.capabilities", "{'initialBrowserUrl':'" + Global.IE_INITIAL_BROWSERURL + "','ignoreProtectedModeSettings': true,'ignoreZoomSetting': true,'ie.browserCommandLineSwitches':'-private','ie.edgechromium':true,'ie.edgepath':'C://Program Files (x86)//Microsoft//Edge//Application//msedge.exe','ie.forceCreateProcessApi':true}");
					

					Global.driver.set(new QAFExtendedWebDriver());	//set the Global.driver so that we can retrieve the screen shot image of a failure in Common.failed()
					return new QAFExtendedWebDriver();
Could you please take a look and let us know what is wrong with QAF 3.1.0?

### Is the issue reproducible on runner?

- [
![issue_edgeieqaf](https://user-images.githubusercontent.com/10450475/211413836-78189dd6-aceb-476e-8045-45cdeca2d1a8.png)
] QAS
- [X ] Maven
- [ ] Gradle
- [] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
refer https://stackoverflow.com/questions/75063314/edge-ie-mode-not-working-as-expected-in-qmetry/75089187#75089187
