### ISSUE TITLE
I am trying to update the versions of qaf and selenium also appium .

### ISSUE THREAD

**Issue by AshuAchhu** [qmetry/qaf#440]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1. Older version is qaf 3.0.1 , selenium 3.141.59 and appium is 7.4.1
    2. Now trying to update the qaf version 3.1.0 , selenium 4.2.2 and appium is 7.4.1 this is compatible for web scenario and api 
       but mobile scenario is not working.

Which appium version is compatible for above mentioned selenium and qaf version for appium driver?

### Actual behavior
[[1;34mINFO[m] Scanning for projects...
[[1;33mWARNING[m] 
[[1;33mWARNING[m] Some problems were encountered while building the effective model for com.qmetry:qaf-blank-project-maven:jar:0.0.1-SNAPSHOT
[[1;33mWARNING[m] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.poi:poi:jar -> duplicate declaration of version 5.2.2 @ line 179, column 13
[[1;33mWARNING[m] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.poi:poi-ooxml:jar -> duplicate declaration of version 5.2.2 @ line 184, column 17
[[1;33mWARNING[m] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 210, column 12
[[1;33mWARNING[m] 
[[1;33mWARNING[m] It is highly recommended to fix these problems because they threaten the stability of your build.
[[1;33mWARNING[m] 
[[1;33mWARNING[m] For this reason, future Maven versions might no longer support building such malformed projects.
[[1;33mWARNING[m] 
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m-----------------< [0;36mcom.qmetry:qaf-blank-project-maven[0;1m >-----------------[m
[[1;34mINFO[m] [1mBuilding qaf-blank-project-maven 0.0.1-SNAPSHOT[m
[[1;34mINFO[m] [1m--------------------------------[ jar ]---------------------------------[m
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mmaven-resources-plugin:2.6:resources[m [1m(default-resources)[m @ [36mqaf-blank-project-maven[0;1m ---[m
[[1;34mINFO[m] Using 'UTF-8' encoding to copy filtered resources.
[[1;34mINFO[m] skip non existing resourceDirectory C:\RT_BOT_v2.0223.2\_RUNS\64352c080037b16389b3f13f\src\main\resources
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mmaven-compiler-plugin:3.1:compile[m [1m(default-compile)[m @ [36mqaf-blank-project-maven[0;1m ---[m
[[1;34mINFO[m] No sources to compile
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mmaven-resources-plugin:2.6:testResources[m [1m(default-testResources)[m @ [36mqaf-blank-project-maven[0;1m ---[m
[[1;34mINFO[m] Using 'UTF-8' encoding to copy filtered resources.
[[1;34mINFO[m] skip non existing resourceDirectory C:\RT_BOT_v2.0223.2\_RUNS\64352c080037b16389b3f13f\src\test\resources
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mmaven-compiler-plugin:3.1:testCompile[m [1m(default-testCompile)[m @ [36mqaf-blank-project-maven[0;1m ---[m
[[1;34mINFO[m] Nothing to compile - all classes are up to date
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mmaven-surefire-plugin:2.9:test[m [1m(default-test)[m @ [36mqaf-blank-project-maven[0;1m ---[m
[[1;34mINFO[m] Surefire report directory: C:\RT_BOT_v2.0223.2\_RUNS\64352c080037b16389b3f13f\test-results\12_Apr_2023_07_10_am

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
ERROR StatusLogger Reconfiguration failed: No configuration found for '22d8cfe0' at 'null' in 'null'
Added "QAFMethodSelector"
include groups []
 exclude groups: [] Scanarios location:  
################# - TEST STARTED - #################
[IQT-259]_[64352c080037b16389b3f142]_MobileScenario_Test
Unable to get class com.qmetry.qaf.automation.step.client.TestStepExporter from jar /C:/Users/c.ashwinira/.m2/repository/com/qmetry/qaf/3.0.1/qaf-3.0.1.jar
Executed Step === Given I open mobile app
Driver not configured!... 
Using firefoxDriver as default value. Please configure driver to be used using 'driver.name' property
Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.'org.openqa.selenium.remote.DesiredCapabilities org.openqa.selenium.remote.DesiredCapabilities.edge()'
msg >>Timed out after 0 seconds: Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.
msg.getBytes() >>[B@769a58e5
ProcessedFiles.json Exists
ProcessedImages.json Created === C:\RT_BOT_v2.0223.2\_RUNS\64352c080037b16389b3f13f\test-results\12_Apr_2023_07_10_am\img\ProcessedImages.json
Json File Exist >>> true  File name =======> IQT259_64352c080037b16389b3f142_MobileScenari
IQT259_64352c080037b16389b3f142_MobileScenari >>> File is already processed
Pic Copied & File Generated !!!!
ProcessedFiles.json Exists
Json File Exist >>> true  File name =======> IQT259_64352c080037b16389b3f142_MobileScenari
IQT259_64352c080037b16389b3f142_MobileScenari >>> File is already processed
Pic Copied & File Generated !!!!
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.792 sec <<< FAILURE!
Preparing For Shut Down...
Result updator: Completed 1 Remaining 0 result to be update.

Results :

Failed tests:   [IQT-259]_[64352c080037b16389b3f142]_MobileScenario_Test(com.qmetry.qaf.automation.step.client.Scenario): Timed out after 0 seconds: Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  24.302 s
[[1;34mINFO[m] Finished at: 2023-04-12T12:41:06+05:30
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;33mWARNING[m] The requested profile "mobile" could not be activated because it does not exist.
[[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-surefire-plugin:2.9:test[m [1m(default-test)[m on project [36mqaf-blank-project-maven[m: [1;31mThere are test failures.[m
[[1;31mERROR[m] [1;31m[m
[[1;31mERROR[m] [1;31mPlease refer to C:\RT_BOT_v2.0223.2\_RUNS\64352c080037b16389b3f13f\test-results\12_Apr_2023_07_10_am for the individual test results.[m
[[1;31mERROR[m] -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
It's because compatibility of appium 7.4.1 with selenium 4. You should either downgrade selenium to 3.141.59 or try with appium 8.0.x or 8.1.x. 

Closing this issue, follow  https://stackoverflow.com/q/75993750/861594
