### ISSUE TITLE
Support XML node key in BDD step call where to JavaStep requires map

### ISSUE THREAD

**Issue by infoneershalin** [qmetry/qaf#54]
Allow passing entire Map object from BDD to JavaStep parameter.

**Comment by cjayswal** [comment]
This is supported by passing json map

**Comment by infoneershalin** [comment]
need support for passing external data from testdata xml.
so if xml has following structure : 

<root>
	<users>
		<user>
			<name>somename</name>
			<email>email@host.com</email>
		</user>
	</users>
</root>

Then user should be able to pass the map with '${users.user}' argument.

**Comment by cjayswal** [comment]
updated title to make it more appropriate
