### ISSUE TITLE
After updating 2.1.9 Jar files, lot of testcases are getting “skipped “.

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#56]
Please let us know on what condition/scenario the testcase will be “skipped “ ? because TC which gets skipped is again retried and either it gets pass / fail but it updated the TC count also in the summary report which becomes as duplicate entry point.

**Comment by infoneershalin** [comment]
TestCase can get skipped for multiple reasons.


1. If using bdd/kwd and when step is not found, testcase will get skipped.
2. If throwing SkipException, testcase will get skipped
3. If data key not found for data driven scenario then also testcase can get skipped
etc...

You can switch to qaf-2.1.10-RC2 which has resolved few issues #52 #42

**Comment by Priya335021** [comment]
Here the skip is for below condition:
When viewing the test results in dashboard.htm, with retry count as 1, for the 1st time failure it is showing as 'Skipped' and 2nd time it is either passed or failed. 
Test case total count is also increased by adding skipped test case number which is making duplicate entry in total test case count.

**Comment by amitbhoraniya** [comment]
Now in testng if any testcase is retried then earlier execution is reported as SKIPPED, so it adds skip count.

**Comment by cjayswal** [comment]
Can you explain problem with detailed information including step to reproduce, what is expected outcome and what is actual. It is preferred if you can create a test case for the issue and provide it. Logging issue in general without supportive information doesn't helps to understand and/or to provide resolution.

**Comment by VijayArul** [comment]
When we run our testcases in 2.1.7 we are getting a proper update in the Dashboard summary [ Passed +Failed = Total TC ] with retry as 1 [ if TC fails , it goes for an retry and update its status as either pass or fail aligned with the total testcase count ] 

But after upgrading the framework to 2.1.9 . we are noticing many testcases are getting skipped and the skipped testcases are again retried and update its status as either pass or fail . But here the skipped testcase also updates the total TC count as an duplicate entry . 
Skipped TCs:
- The testcases are getting skipped in many cases , one is  if the element is not able to be located [ But if element is not visible / located then the TC should be failed rather it gets skipped ] . Hence its not clear when the TC is getting skipped and when the TC gets failed .

**Comment by cjayswal** [comment]
if that is the case set retry.count to 0
