### ISSUE TITLE
Not working with groovy code,gettining "Classnotinitilization Error"

### ISSUE THREAD

**Issue by deepakg-webonise** [qmetry/qaf#58]
Thanks for such wonderful open source product. While exploring your open source framework we faced some issues. Below are details and objective of experiment. 

Objective : Using BDD approach , we need to execute our groovy files including step definition. Cucumber will be used for steps definition , gherkin can use as feature file while we are trying  groovy for scripting . 

Steps with QAF framework : 
1. Define application property file with basic require properties and step.provider.pkg definition . 
2. In "step.provider.pkg" define groovy step definition file but after execution of runner XML, it throws 'Class not Initialize " error . However, if we tried same with step definition in java file it worked perfectly. So do we support groovy ? or are we doing something wrong ? 

Please help us to move so we can leverage this seamless framework. Thanks again.

**Comment by cjayswal** [comment]
Can you please provide steps to reproduce?
It's working fine with groovy as well.

**Comment by deepakg-webonise** [comment]
Hi, 
I sent this to info@qmetry.com but missed to put it here. 
Objective : Using BDD approach , we need to execute our groovy files including step definition. Cucumber will be used for steps definition , gherkin can use as feature file while we are trying  groovy for scripting . 

Steps with QAF framework : 
1. Define application property file with basic require properties and step.provider.pkg definition . 
2. In "step.provider.pkg" define groovy step definition file but after execution of runner XML, it throws 'Class not Initialize " error . However, if we tried same with step definition in java file it worked perfectly. So do we support groovy ? or are we doing something wrong ? 

Please help us to move so we can leverage this seamless framework. Thanks again.

**Comment by cjayswal** [comment]
will you please your groovy file where you declaring  steps? We did tried to reproduce but its working fine at our end.

**Comment by amitbhoraniya** [comment]
This may be because groovy version conflicts in your classpath, In order to resolve conflict remove Groovy Libraries from your classpath as it already included in QAF dependencies. Refer below screenshot.

![image](https://cloud.githubusercontent.com/assets/4617600/21523941/49ff1c66-cd38-11e6-8cff-8362dba48847.png)

**Comment by cjayswal** [comment]
Closing inactive issue. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
