### ISSUE TITLE
Parallel configuration share parameters values.

### ISSUE THREAD

**Issue by hadasshani** [qmetry/qaf#59]
When user run the cucumber tests in parallel, sometimes driver tries to open the device that already used by another test thread.
If deviceName parameter was define for one test (in testng.xml) it is using the same parameter in another test configuration, even if it wasn't defined.
So the test is ignored with next output:
Unable to create driver instance in 1st attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Failed to execute command handset open: Cannot open device 9A90117A5FF7AEB655944A1D7FA8C70F3C2C81BD for user test_automation@gmail.com, device is in use.

Steps to reproduce:

Create feature file with several test scenarios
Create xml suite which will run those scenarios in 2 tests, for one test set the "deviceName" parameter
Run the xml suite

**Comment by cjayswal** [comment]
It looks you have provided same device id for different test configured to run in parallel. Please refer [testng_tags.xml.zip](https://github.com/qmetry/qaf/files/652030/testng_tags.xml.zip) which is modified from the config file you shared.
