### ISSUE TITLE
BDD Scenarios are getting skipped in QAS during execution

### ISSUE THREAD

**Issue by vn01156** [qmetry/qaf#62]
“Unable to execute script in QAS".
1. The Perfecto Lab and Dashboard is getting disconnected often in QAS. Attached screenshot on the Perfecto Issue disconnection. When trying to open in website this issue is not happening.
[PerfectoIssue.docx](https://github.com/qmetry/qaf/files/668225/PerfectoIssue.docx)

2. We are getting below issue when executing the automated scripts after @12 PM IST, and we are blocked. Is there is any Issues/downtime.?
[Skipping Issue.docx](https://github.com/qmetry/qaf/files/668224/Skipping.Issue.docx)

Issue1: Unable to Create Driver Instance for appium: java.lang.reflect.InvocationTargetException.
Issue2: Connect to heb.perfectomobile.com:443 [heb.perfectomobile.com/192.80.63.78] failed: Connection timed out: connect
Issue3: ERROR com.perfectomobile.selenium.util.PerfectoLabConnector - 
Failed to connect to Perfecto Lab for Eclipse plugin on host: localhost and port: 3287. 
Possible reasons are: The code doesn't run in Eclipse or the Perfecto Lab view is not open. In these cases use the MobileDriver constructor that receives the host, user and password.
“Unable to execute script due to slowness in perfecto performance”
Issue4: Error communicating with the remote browser. It may have died.

Attached screenshot for the above mentioned skip issues.

**Comment by cjayswal** [comment]
Regarding **Issue1:** Unable to Create Driver Instance for appium: You should check you have proper driver configuration. For example: 
`driver.name=appiumDriver` with provided driverClass capability (either android or ios) along with other capabilities. or `driver.name=appiumRemoteDriver` (in this case of remote driver you will not be able to cast underplaying driver to android or ios driver) 

> With 2.1.8 or higher  use `driverClass` capability instead of `driver.class`. Refer release notes.

All other issues are not relevant to framework and related to either network or cloud or IDE plugin.

**Comment by vn01156** [comment]
I am using driver.name=appiumDriver in configuration file and 2.1.7 version. 

But still facing the skipping issue daily. Due to this we are unable to run the created scripts. This is affecting our daily activities. Attached the screenshot today's run result.

[SkipIssue.docx](https://github.com/qmetry/qaf/files/675720/SkipIssue.docx)

**Comment by amitbhoraniya** [comment]
This looks purely configuration or cloud connection issue, will you please share your configuration files and other driver capabilities you are using.

**Comment by vn01156** [comment]
Please find the attachment and below details.

driver.additional.capabilities={'deviceName':'ZY2233DBS5','automationName':'Appium','platformName':'android','driver.class':'io.appium.java_client.android.AndroidDriver','applicationName':'H-E-B'}

[application.txt](https://github.com/qmetry/qaf/files/676771/application.txt)

**Comment by cjayswal** [comment]
@vn01156 Will you please update on this issue?

**Comment by cjayswal** [comment]
Closing inactive issue. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
