### ISSUE TITLE
Reporter.log(message,Messagetypes) don't have option to set to log to standard output

### ISSUE THREAD

**Issue by SaiPriyanka** [qmetry/qaf#63]
Problem: 
- Can't see Reporter.log (html logs) in eclipse console .
I see their is existing support for TestNG , but qmetery Utility Class" Reporter.log "don't have an option to set to log standard output as it is supported in testNG, as this helps debugging easier when working with TestNG Eclipse plugin.
Existing support in testng has something that can be set to boolean if required "http://testng.org/javadocs/org/testng/Reporter.html"
log(java.lang.String s, boolean logToStandardOut)

**Comment by amitbhoraniya** [comment]
This can be configured through log4j. Set console log level at debug in log4j property, alternately you can set log level debug for `com.qmetry.qaf.automation.core.QAFTestBase` .

**Comment by cjayswal** [comment]
Hi Sai, 
Please let us know if you need furthermore help or we can close this issue.

**Comment by cjayswal** [comment]
Closing issue as not hearing back, please configure log4j for this purpose. If you are looking something else then reopen issue with details.
