### ISSUE TITLE
"Your connection is not secure" issue while launching script in Firefox.

### ISSUE THREAD

**Issue by vn01159** [qmetry/qaf#67]
How to resolve this issue. One of the approach we have tried is below in java but its not working. unable to proceed ahead after "Confirm Security Exception" page. I have uploaded the screen shot of issue page.
First I have created a profile in firefox named "automationtest" and then
Following desired capabilities we have set for Firefox:

       ProfilesIni allProfiles = new ProfilesIni();
	FirefoxProfile myProfile = allProfiles.getProfile("automationtest");
	myProfile.setAcceptUntrustedCertificates(true);
	myProfile.setAssumeUntrustedCertificateIssuer(false);
	WebDriver myProfilename = new FirefoxDriver(myProfile); // FirefoxProfile
	myProfile = new FirefoxProfile();

Required help on this issue.
Firefox version-50.0.1
Selenium server-3.0.1
geockdriver-0.11.1
![addexception](https://cloud.githubusercontent.com/assets/24671017/21676726/e91d8bb4-d35c-11e6-8673-5c92245ff08e.PNG)

**Comment by vn01159** [comment]
Hi, 
Any one  please help with issue mentioned above.

**Comment by amitbhoraniya** [comment]
Profile "automationtest" which you have created that should have accepted certificate.
If not then manually start firefox with "automationtest" profile and manually accept that certificate.

**Comment by cjayswal** [comment]
This issue is more specific to driver rather than the framework and should be posted to driver specific forum.

**Comment by vn01159** [comment]
Thanks Amit.

Its working fine.I am able to launch script in Firefox but unable to open the reasons of failure from the failed test steps. On clicking failed test steps we are getting the below screen:
![unable to the failure reason](https://cloud.githubusercontent.com/assets/24671017/22023535/8b956874-dcec-11e6-96a9-a42de59de7d4.PNG)

Any idea how to resolve this any one ?

**Comment by amitbhoraniya** [comment]
This report may not be related to Firefox driver, so can you identify and create a new issue with step to reproduce.

**Comment by cjayswal** [comment]
Closing as original issue get resolved. You may create separate issue for another problem with supportive information like detailed description, step to reproduce, expected and actual outcome, exception trace if any, logs etc.
