### ISSUE TITLE
 Getting Error "Error communicating with the remote browser. It may have died."

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#69]
Getting Error "Error communicating with the remote browser. It may have died."

Experiencing this issue in parallel execution with chrome driver when the thread count is configured as more than 1 in config xml files.

Platform: Windows

Tried below solutions, but nothing had worked out.
1. Updated windows reg edit tcp maximum ports
2. Made the test step methods as thread safe by adding synchronized modifier

Frequency of this error is more when the thread count increases. Please help us on this.

**Comment by vn01159** [comment]
Hi,

Can any one help me with the above issue? I am also facing the same issue.

**Comment by amitbhoraniya** [comment]
Are you trying to start all chrome instance on same local machine or are you using selenium grid or clouds to execute parallel testcases?

**Comment by Priya335021** [comment]
I am trying to start 3 to 4 chrome instances in same local machine.

**Comment by cjayswal** [comment]
Can you share more information like, exception stack trace, configuration file, driver name you are using etc? 
In order to run test on chrome in local environment make sure you have set up following properties:

``` properties

driver.name=chromeDriver
webdriver.chrome.driver=<location of chrome driver>
```

**Comment by Priya335021** [comment]
**1. Attached the config file which was used to execute and it is executed as TestNG suite.** 
[testNgConfig.txt](https://github.com/qmetry/qaf/files/710182/testNgConfig.txt)

**2. Driver name has updated as below in application.properties file**
driver.name=chromeDriver
webdriver.chrome.driver=lib\\chromedriver.exe

**3. Stack trace on TestNG results:**

```
Error communicating with the remote browser. It may have died.
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'PC296953', ip: '10.251.3.40', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed), userDataDir=C:\Users\335021\AppData\Local\Temp\scoped_dir7620_16517}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=55.0.2883.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: f390abe713b8c153dc87389bbdca4c0f

```

**Comment by cjayswal** [comment]
It looks like you have driver and browser version compatibility issue. 
Your chrome version looks 55 which is not supported by chrome driver version 2.25.
[Download latest chromedriver] (https://sites.google.com/a/chromium.org/chromedriver/downloads) and check. You are using chromedriver version 2.25 and latest is 2.27 that supports Chrome v54-56.

**Comment by Priya335021** [comment]
With chromedriver version 2.27 also, we are getting the same issue. 
PFB the stack trace.
`Error communicating with the remote browser. It may have died.
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'PC296953', ip: '10.251.3.40', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), userDataDir=C:\Users\335021\AppData\Local\Temp\scoped_dir18288_27192}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=55.0.2883.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: c79c56b12ba3df21744885a37288f151`

Below Config file has been used.
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Homepage and Browse.com Smoke test suite" parallel="tests" thread-count="3">

	<parameter name="env.resources" value="resources/qa;resources/testdata"></parameter>
	<parameter name="step.provider.pkg" value="com.automation.web"></parameter>
	<parameter name="wd.command.listeners"
		value="com.automation.web.listener.SeleniumWebDriverListener"></parameter>
	<parameter name="scenario.file.loc" value="scenarios/Homepage and browse.bdd" />

	<test verbose="2" name="HomePage Browse in Chrome 1">
		<parameter name="driver.name" value="chromeDriver" />
		<parameter name="webdriver.chrome.driver" value="lib\\chromedriver\\chromedriver227\\chromedriver.exe" />
		<groups>
			<run>
				<include name="Header Validation" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
	</test>
<test verbose="2" name="HomePage Browse in Chrome 2">
		<parameter name="driver.name" value="chromeDriver" />
		<parameter name="webdriver.chrome.driver" value="lib\\chromedriver\\chromedriver227\\chromedriver.exe" />
		<groups>
			<run>
				<include name="Order Quantity" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
	</test>
	<test verbose="2" name="HomePage Browse in Chrome 3">
		<parameter name="driver.name" value="chromeDriver" />
		<parameter name="webdriver.chrome.driver" value="lib\\chromedriver\\chromedriver227\\chromedriver.exe" />
		<groups>
			<run>
				<include name="Login" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
	</test>
</suite> 
`

**Comment by Priya335021** [comment]
config XML file has not uploaded properly before.. Hence attaching here.
[config.txt](https://github.com/qmetry/qaf/files/713672/config.txt)

**Comment by meetparag81** [comment]
Hello All thanks for your reply.
@cjayswal , I am using chrome browser = Version 68.0.3440.106 (Official Build) (64-bit) for that I am using Chrome Driver 2.41 driver exe, is that correct or should I need to use Chrome Driver 2.40?
Note that I can run the script on chrome browser = Version 65 without any error related to browser
Should I  downgrade  my chrome browser to 65?
Let me confirm
