### ISSUE TITLE
Support to define component with locator repository

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf#73]
Self descriptive locator has capability to provide meta-data with the locator. There can be a way where user can define component class in meta-data that can be used to create element from the locator by the framework.

**Comment by narendrarajput** [comment]
How to use `component-class` to init List of Component?

I have tried below code but its not working as expected.

My locator is
```properties
productdetail.grid={"locator":"xpath=//*[@content-desc='product_list']","desc":"product detail","component-class":"com.flipkart.component.SearchResultComponent"}
````

My java code
```java
List<QAFWebElement> productList = getDriver().findElements("productdetail.grid");
for (int i = 0; i < productList.size() - 1; i++) {
    ((SearchResultComponent) productList.get(i)).getProductName());
}
```

It throws java.lang.ClassCastException. com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement cannot be cast to com.flipkart.component.SearchResultComponent.

I am using qaf version 2.1.13.
