### ISSUE TITLE
Some scripts taking more hours than expected time, is there any cutoff time there to limit execution of a test script

### ISSUE THREAD

**Issue by githubdilip** [qmetry/qaf#77]
Few test scripts executed more than 7 hours, even though there is some error like error communicating with the server and element is not visible, which usually will be executed within 5 minutes. 

Is there any cutoff time available in QAF so that we can limit the test execution which will avoid such kind of   issues.

**Comment by cjayswal** [comment]
Did you tried specifing “timeOut” attribute of @Test annotation? For example:
**in java**
```
@Test ( timeOut = 150000 )
```
**in BDD**
```
META-DATA: {"timeout":150000 }
```
Closing issue as not bug or feature request. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
