### ISSUE TITLE
How to send the QAF execution summary as email ?  

### ISSUE THREAD

**Issue by VijayArul** [qmetry/qaf#78]
How to send the QAF execution summary report as email for the project team ? is there any provision through framework ? Do we have any documentation for this ?

**Comment by cjayswal** [comment]
You can enable default TestNG listeners which will generate `emailable-report.html` or write your custom implementation. You should utilize CI for that purpose.

**Comment by cjayswal** [comment]
Closing inactive issue. Please post question in user group.
