### ISSUE TITLE
How to create a mutiple chrome webdriver instances

### ISSUE THREAD

**Issue by nimy111** [qmetry/qaf#80]
As a part of my project I need to create multiple sessions so I am trying to create multiple webdriver instance to create multiple session. When I try to create a new instance using new WebDriverTestCase().getDriver(), it is opening in the same chrome browser instead of opening in new window.  

Is there any method available in QAF to create multiple chrome driver instances in multiple windows instead of opening in the same window

**Comment by cjayswal** [comment]
Will you please explain your use case, What you are trying to achieve? Do you want to run your test in parallel or within the test you need to open multiple browser session?

**Comment by nimy111** [comment]
Within the test I need to open multiple browser session. As per my test scenario, I need to test the error message once I reached the threshold by opening multiple sessions and login. 
I have tried to open tabs and open windows but both of the method are sharing the same session instead of creating multiple sessions.

**Comment by cjayswal** [comment]
It looks like performance test and not a functional test for that you should use performance testing tools like JMeter. 

If that is not the case you can create new driver using `UiDriverFactory.get(ArrayList<LoggingBean> commandLog, String[] stb)` and make sure you are calling `UiDriverFactory.tearDown(UiDriver driver)` for each created driver instance once you are done.

**Comment by hadasshani** [comment]
Is there a way to configure the multiple devices from the properties file?
Will I have 2 separate reports? I need one flow report

**Comment by cjayswal** [comment]
@hadasshani yes you can have multiple devices configured in properties.
Closing inactive issue. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
