### ISSUE TITLE
Custom Data Provider support for BDD Scenarios

### ISSUE THREAD

**Issue by amitbhoraniya** [qmetry/qaf#82]
Currently to make bdd scenarios data driven, user has to use one of the following formats
- CSV Data Provider
- Excel Data Provider
- JSON Data Provider
- XML Data Provider
- DATABASE Data Provider
- Text Data Provider

Custom data provider can be helpful in
- For NoSQL database
- File formats which QAF data provider does not support
- To provide a structured data after processing  on raw data
- Or any ther custom logic for testdata

**Comment by cjayswal** [comment]
Feature available with 2.1.12-RC2

**Comment by amitbhoraniya** [comment]
👍

**Comment by amitbhoraniya** [comment]
Here is an example for custom data provider for reference. [CustomDataProviderExample.zip](https://github.com/qmetry/qaf/files/1559358/CustomDataProviderExample.zip)
