### ISSUE TITLE
Test case pass fail scenarios count mismatch on Dashboard.

### ISSUE THREAD

**Issue by maheshchaudhar** [qmetry/qaf#86]
Description: QAS dashboard not showing accurate pass failed scenarios count and percentage. for example, actual failed scenarios are 7 but dashboard shows 4 as failed scenarios count. Attached screenshot for reference.
![defect1](https://cloud.githubusercontent.com/assets/11026791/23120909/4735cb76-f784-11e6-9fdc-538df2e83428.PNG)
![defect2](https://cloud.githubusercontent.com/assets/11026791/23120912/4ae54f8a-f784-11e6-8b05-688d0302facf.PNG)

**Comment by cjayswal** [comment]
Hi mahesh,
Can you provide more details and steps to reproduce?

**Comment by cjayswal** [comment]
Don't forget to mention qaf version.

**Comment by maheshchaudhar** [comment]
Hi Chirag,

We are getting this issue mostly when we execute data-driven scenarios in parallel. Also this issue is not consistent sometimes it works fine. But most of the time we are facing this issue  when we execute scenarios using saucelab & Jenkins.  

QAF Version: 2.1.10-RC2

Let me know if you need more information.

**Comment by cjayswal** [comment]
Will you please check with 2.1.10 or 2.1.11-RC1.

**Comment by cjayswal** [comment]
@maheshchaudhar, Will you update us with your observation with latest build of QAF?

**Comment by maheshchaudhar** [comment]
Hi Chirag,

I didn't observed this issue in latest QAF build. Thanks for the update.
