### ISSUE TITLE
Unable to create driver instance in 1st attempt with retry timeout of 60 seconds

### ISSUE THREAD

**Issue by bernaxa** [qmetry/qaf#88]
Hello,

When using the QAF/Maven framework through proxy I receive this error:

`Unable to create driver instance in 1st attempt with retry timeout of 60 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.Unable to Create Driver Instance Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'xxxxxxx', ip: 'x.x.x.x', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: QAFExtendedWebDriver`

With direct wifi, without proxy, the code is executed correctly.

I can access to the "remote.server" defined in the "application.properties" from a browser through proxy.

I've also tried to configure the proxy in
•	Eclipse Neon.2 network connections
•	Default VM arguments of the JRE definition
•	VM arguments of the Maven / TestNG run configurations.

Thanks

**Comment by amitbhoraniya** [comment]
Have you tried with configure proxy in desired capabilities?

**Comment by bernaxa** [comment]
sorry, where exactly? 

thanks

**Comment by bernaxa** [comment]
Hello @amitbhoraniya,

I don't see where to specify the proxy in desired capabilities. The application.properties doesn't seem to have any parameter to do it.

Do you mean to modify any of the QAF classes ? 

Thanks

**Comment by amitbhoraniya** [comment]
Refer this documentation: [Setting Driver Capabilities](https://qmetry.github.io/qaf/latest/setting_driver_capabilities.html)
For example:
```properties
chrome.additional.capabilities={"proxy":{"proxyType":"MANUAL","autodetect":false,"httpProxy":"localhost:8080"}}
```

**Comment by bernaxa** [comment]
Hello @amitbhoraniya,

I've tried your suggestion, and following the documentation, I configured the driver.additional.capabilities (for all drivers) in application.properties, but it doesn't work:

I've tried 4 options
1)
driver.additional.capabilities={'proxy':{'proxyType':'manual','httpProxy':'http://192.168.62.4:3128','sslProxy':'http://192.168.62.4:3128'}}

2)
driver.additional.capabilities={'proxyType':'manual','httpProxy':'http://192.168.62.4:3128','sslProxy':'http://192.168.62.4:3128'}

3)
driver.additional.capabilities={"proxy":{"proxyType":"manual","autodetect":false,"httpProxy":"http://192.168.62.4:3128","sslProxy":"http://192.168.62.4:3128"}}

4)
driver.additional.capabilities={webDriverProxy: 'http://192.168.62.4:3128'}

Thanks

**Comment by cjayswal** [comment]
Try setting system properties for proxy. you can use `system` prefix to specify system property in properties file, for example:
```
system.http.proxyHost=<host>
system.http.proxyPort=<port>
```

Closing issue as not qaf bug or feature request. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).

**Comment by MrudulaTCS** [comment]
Hi,
Even after including these statements in the application.properties file, am still facing the same issue.
Could you please specify what exactly needs to be in the given in the host and port values.

And is there any other changes to done in the code, to run initialise driver from a private network which has proxy restirctions.

Regards,
Mrudula
