### ISSUE TITLE
How to run failed test cases alone using Jenkins CI.

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#89]
Using Qmetry Studio and QAF 2.1.10. Project is directly linked from Git to Jenkins CI.
In Jenkins job, configured the target name as "runtests" (ANT target). It is creating testng-failed-qas.xml in corresponding test results folder.

Let me know how to trigger the failed cases alone using Jenkins CI after the full run of all test cases.

**Comment by mishalhshah** [comment]
There is target named as "run-tests-failed" for executing the failed cases.
you can check seleniumtestrunner.xml where above mentioned target is written.

**Comment by Priya335021** [comment]
yes. But, in case of Jenkins CI, where to configure this command "run-tests-failed" to run failed test cases?

We cant create second job in Jenkins with this target name, since for each job the work space is different. There wont be link for second and first job's work space.

**Comment by mishalhshah** [comment]
Remove the “runtests” command . Instead of that you just need to configure single command "run-tests-failed". It will run first and if failed test cases are there , it will execute the failed test cases.

There is no need to create second job, from single job it will server your purpose.

Thanks,
Mishal  Shah

**Comment by Priya335021** [comment]
Able to run failure test cases with command "run-tests-failed" but only when not renaming the testng-failed-qas.xml. 
Commented below step and executed.
"<rename src="${output.dir}/testng-failed-qas.xml" dest="${output.dir}/testng-failed.xml" />"
