### ISSUE TITLE
Passing APIKey parameter for webservive Rest API URL via post method

### ISSUE THREAD

**Issue by vn01156** [qmetry/qaf#93]
We are trying to automate Rest API Service using QAS. 

We have gone through and worked on the existing WebService + Web automation Example and can able to see successful response for the same.

When we are tried to implement the same to our service URL. After posting the data, the script is throwing an exception as mentioned in the attachment.
[Issue_Log.txt](https://github.com/qmetry/qaf/files/814013/Issue_Log.txt)

Please Guide here.

**Comment by cjayswal** [comment]
From the log i can see `java.net.UnknownHostException`. Make sure you are providing correct URL or it's accessible.

For such help or implementation issues we recommend to have in [stackoverflow-tagged-qaf ](http://stackoverflow.com/questions/tagged/qaf) or [linked-in group](https://www.linkedin.com/groups/4014456).

**Comment by cjayswal** [comment]
Closing inactive issue. Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
