### ISSUE TITLE
Dynamic sheetName in excel data provider

### ISSUE THREAD

**Issue by kulin-sitwala** [qmetry/qaf#94]
How to pass dynamic sheetName from properties or Jenkins for scenarios?

I tried doing it by adding meta data value of sheetName in the iTestListener onTestStart() method. But even though meta data is added the scenario is not loading the data from the specified sheet.

**Comment by cjayswal** [comment]
Is this your case of data-driven test? You should provide parameter in meta-data. For example:
`sheetName="${my.parameter}"` 

Alternate is you can check how to [override-dataprovider](https://qmetry.github.io/qaf/latest/maketest_data_driven.html#configureoverride-dataprovider).

**Comment by kulin-sitwala** [comment]
Thank You for your quick help.

1. I tried passing the meta data as a parameter but it is not working.

`Scenario Outline: Test scenario
	Given I test test data "${args[0]}"

Examples: {'datafile' : 'src/main/resources/data/exceldata/testData.xls' , 'sheetName':'vf4'}
`
This example is working fine. But in the below mentioned example the parameter is not parsed.

`Scenario Outline: Test scenario
	Given I test test data "${args[0]}"

Examples: {'datafile' : 'src/main/resources/data/exceldata/testData.xls' , 'sheetName':'${sheetName}'}`

**Error:** Worksheet ${sheetName} not found.

2. I also tried using this global.testdata parameter in application.properties file in following manner:

global.testdata=dataFile="src/main/resources/data/exceldata/testData.xls";sheetName="vf4"

But in this manner it is not loading the excel data at all.

Please find the different combinations of scenario syntax that I used with this property:

- `Scenario Outline: Test_scenario
	Given I test test data "${args[0]}"

Examples: {}`

- `Scenario: Test_scenario
	Given I test test data "${args[0]}"
`

- `Scenario Outline: Test_scenario
	Given I test test data "${args[0]}"

Examples: {'datafile' : 'src/main/resources/data/exceldata/sales/appointments.xls'}
`

In all of the above cases the intended sheet is not getting loaded.

Can you please help me if I am doing something wrong.

**Comment by kulin-sitwala** [comment]
I am not sure if this information will help you guys further or not. But the difference in Quantum is that we are using 'com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory' class to execute feature files inplace of this we use BDDFactory normally.

**Comment by cjayswal** [comment]
Doesn't matter, you can use BDDFactory as well when using Quantum or  GherkinScenarioFactory without Quantum. Quantum provides PerfectoMobile specific steps and listener implementation.

**Comment by kulin-sitwala** [comment]
@mishalhshah and @amitbhoraniya Thanks for your help. You can close this issue you gave me the workaround solution for this.

**Comment by cjayswal** [comment]
Reopening to track

**Comment by mehulkumarpatel** [comment]
dataFile and sheetName keys are not overridden when given in MetaData tag with $ properties in QAF reports
![test1](https://user-images.githubusercontent.com/5569357/44779509-4b84a700-ab9d-11e8-9dad-39e338ac3712.PNG)
![test2](https://user-images.githubusercontent.com/5569357/44779511-4d4e6a80-ab9d-11e8-91f7-a6f7151c359b.PNG)
