### ISSUE TITLE
Getting same device in parallel execution of threads in multiple devices

### ISSUE THREAD

**Issue by kulin-sitwala** [qmetry/qaf#97]
**Condition:** There are two iPad Air 2 devices in my Perfecto cloud. I need to execute 5 scenarios in parallel using 2 iPad devices. Following is the testNG configuration file for the same.

`<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Appium Demo Suite" verbose="0" parallel="tests">
	<listeners>
		<listener class-name="com.quantum.listerners.QuantumReportiumListener" />
	</listeners>

	<parameter name="driver.name" value="perfectoDriver" />

	<test name="IOS iPad air 2 Test" enabled="true" parallel="methods"	thread-count="2">
		<parameter name="driver.capabilities.model" value="iPad Air 2"></parameter>
		<parameter name="env.resources" value="src/main/resources/ios" />
		<groups>
			<run>
				<include name="@TestScenarios" />

			</run>
		</groups>
		<classes>
			<class
				name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>
</suite>`

**Issue**: Sometimes the two threads take the same devices and then fail at the time of execution.
This happens randomly, sometimes the devices are different and the execution is completed as expected.

See the console logs when two different threads in parallel gets the same device:

`pool-1-thread-1: Initializing Driver...browser_str:perfectoDriver,base_url:,sel_server:https://sap.perfectomobile.com/nexperience/perfectomobile/wd/hub,port:80 
pool-1-thread-2: Initializing Driver...browser_str:perfectoDriver,base_url:,sel_server:https://sap.perfectomobile.com/nexperience/perfectomobile/wd/hub,port:80 
pool-1-thread-2: Driver: perfectoDriver 
pool-1-thread-1: Driver: perfectoDriver 
pool-1-thread-2: Received eclipse host: sap.perfectomobile.com 
pool-1-thread-2: Interactive connector session execution Id: kulin.sitwala@sap.com_Eclipse_17-03-22_05_37_08_833 
pool-1-thread-1: Received eclipse host: sap.perfectomobile.com 
pool-1-thread-1: Interactive connector session execution Id: kulin.sitwala@sap.com_Eclipse_17-03-22_05_37_08_833 
pool-1-thread-1: Processing request Request[_requestType=DEVICE_INFO,_itemId=CE972E8699E543988DAEC9F6282DEEF038600C41,_parameters=[ParameterValue[_name=responseFormat,_value=xml]],_stringParameters=<null>,_encoding=<null>] 
pool-1-thread-2: Processing request Request[_requestType=DEVICE_INFO,_itemId=CE972E8699E543988DAEC9F6282DEEF038600C41,_parameters=[ParameterValue[_name=responseFormat,_value=xml]],_stringParameters=<null>,_encoding=<null>] `

See in the request above for both the threads "itemId=CE972E8699E543988DAEC9F6282DEEF038600C41" is the same. Ideally this needs to be different.

**Desired Behavior**: For both the threads the request to two different devices should be made. This is happening sometimes.

Following is the console log for the same two threads in parallel getting different devices.(This is the expected outcome every time)

`pool-1-thread-1: Initializing Driver...browser_str:perfectoDriver,base_url:,sel_server:https://sap.perfectomobile.com/nexperience/perfectomobile/wd/hub,port:80 
pool-1-thread-2: Initializing Driver...browser_str:perfectoDriver,base_url:,sel_server:https://sap.perfectomobile.com/nexperience/perfectomobile/wd/hub,port:80 
pool-1-thread-1: Driver: perfectoDriver 
pool-1-thread-2: Driver: perfectoDriver 
pool-1-thread-2: Received eclipse host: sap.perfectomobile.com 
pool-1-thread-2: Interactive connector session execution Id: kulin.sitwala@sap.com_Eclipse_17-03-22_05_37_08_833 
pool-1-thread-1: Received eclipse host: sap.perfectomobile.com 
pool-1-thread-1: Interactive connector session execution Id: kulin.sitwala@sap.com_Eclipse_17-03-22_05_37_08_833 
pool-1-thread-1: Processing request Request[_requestType=DEVICE_INFO,_itemId=F38C38AB6541C1938E440C0B918373E6C0585DDC,_parameters=[ParameterValue[_name=responseFormat,_value=xml]],_stringParameters=<null>,_encoding=<null>] 
pool-1-thread-2: Processing request Request[_requestType=DEVICE_INFO,_itemId=CE972E8699E543988DAEC9F6282DEEF038600C41,_parameters=[ParameterValue[_name=responseFormat,_value=xml]],_stringParameters=<null>,_encoding=<null>] `

Please let me know if you need any more details to reproduce this issue.

**Comment by cjayswal** [comment]
Is this the case where the same device allocated to more than one thread by cloud and one of the thread throws exception? if so you can use `driver.init.retry.timeout` and set timeout to retry for the driver creation. Any case it must required another device available.

**Comment by kulin-sitwala** [comment]
Yes, both the threads were allocated the same device by the cloud. As per my analysis from the console this is happening exactly when both the threads send request to the same device. 

Both the threads are able to create driver even with the same device. The exception is thrown in the test case at the time of performing operation on the device, we get "device is busy" or "some other operation is running on the device error". And then the test case fails.

I tried increasing the driver.init.retry.timeout to 60 seconds but as the driver for both the threads is getting created it is not making any difference.

And yes both the devices (iPads) were available in the cloud and the same code sometimes works as expected when both threads sends requests to two different devices.

**Comment by anjalibangoria** [comment]
This does not look like QAF issue. As both thread are different still picking same device by perfecto cloud. QAF is not responsible for device picking in cloud.

**Comment by kulin-sitwala** [comment]
Resolved with the help of perfecto team.
