### ISSUE TITLE
waitForAjaxToComplete is deprecated in QAF Release 2.1.10?

### ISSUE THREAD

**Issue by sabariish** [qmetry/qaf#98]
There is no mention of the replacement method for the same. Could not find anything in the javadocs as well. We need advice on the applicable replacement. We have numerous occurrences for this method in our code base.

**Comment by cjayswal** [comment]
Yes, it is deprecated. Most of the case it is internally handled for actions, assertions and verification. If you found that removing that impacts to your test let us know.

**Comment by sabariish** [comment]
We see failures now in our tests due to this. 
e.g: We click on a radiobutton on the page, domelements get refreshed however script fails with object not found error. This happens because there is an AJAX calls which is happening on the browser after the radiobutton.click(), but there is not subsequent wait allowed for it to complete before proceeding to next statement.
However if we add below lines explicitly after the click(), tests work fine:
		WaitService waitService = new WaitService ();
		waitService.waitForAjaxToComplete();
Please review.

**Comment by cjayswal** [comment]
Thanks for update Sabarish. I am marking this as defect. We are thinking not to remove that method. Please let us know your and your teams recommendation.
